cloudflare/quiche

- src/frame.rs
> frame: remove unnecessary ()

- examples/client.rs
- examples/http3-client.rs
- examples/http3-server.rs
- examples/qpack-decode.rs
- examples/qpack-encode.rs
- examples/server.rs
- src/h3/mod.rs
- src/h3/qpack/mod.rs
- src/lib.rs
- src/octets.rs
- src/packet.rs
Commit messages should be fairly self-explanatory. FYI @LPardue there's a few h3-related changes here on how errors from the transport layer and `octets` are handled/reported.
> Some error handling improvements

- src/h3/mod.rs
This fixes a couple of regressions from recent HTTP/3 changes.
> Regression fixes for HTTP/3

- src/h3/mod.rs
- src/h3/stream.rs
This refactors how data is read from transport streams and buffered
at the HTTP/3 layer, as well as simplifies the HTTP/3 stream state
machine.
Instead of reading and buffering a fixed amount of bytes from readable
streams, only the amount of bytes required to complete the current state
is read from the transport. Data is still buffered in the HTTP/3
stream's state in order to deal with partial reads, but is now read
directly into the stream buffer to avoid one intermediate copy.
The stream's buffer is resized accordingly to the number of bytes
required by the next state. However the allocated memory for the buffer
is reused across states to avoid unnecessary allocations (an allocation
is only required if the new state requires more data than the current
state).
As for the state machine, …
> h3: refactor stream buffering and state machine

- src/h3/stream.rs
Since we don't buffer DATA frames anymore, there's no point in resizing
the state buffer.
---
This depends on https://github.com/cloudflare/quiche/pull/59.
I can now run the `http3/5000000` benchmark without running our of memory :)
> h3::stream: don't resize state buffer for DATA frames

- src/lib.rs
- src/stream.rs
Instead of always picking the first writable stream from the streams map
(depending on the HashMap iteration order, so not necessarily the stream
with the lower ID), keep track of writable streams in a separate FIFO
queue, and round-robin them.
This preserves the order of stream writes to what the application
decides (i.e. the order of stream_send() calls), and increases stream
concurrency and significantly reduces deviation in response times
between concurrent requests.
For example, running 250 identical HTTP/3 requests concurrently using
h2load shows the following before the change:
```
finished in 78.66s, 3.18 req/s, 3.12MB/s
requests: 250 total, 250 started, 250 done, 250 succeeded, 0 failed, 0 errored, 0 timeout
status codes: 250 2xx, 0 3xx, 0 4xx, 0 5xx
traffic: 245.25MB (257165011) …
```
> schedule writable streams fairly

- src/lib.rs
- src/stream.rs
If an empty STREAM frame was received on a stream that was not already
readable, the stream wouldn't become readable and the fin flag wouldn't
be propagated to the application.
This changes the recv buf push logic to store the range buffer generated
by an empty STREAM frame with the fin flag set.
We don't store non-fin empty range buffers, or duplicate fin range
buffers (other range buffers that don't match the fin offset would get
rejected anyway), since an attacker could potentially cause resource
exhaustion by sending lots of empty STREAM frames that don't consume
flow control.
> stream: propagate fin from empty STREAM frames

- src/h3/mod.rs
- src/h3/stream.rs
A peer can influence the size of the state buffer (e.g. with the
payload size of a GREASE frame), so we need to limit the maximum
size to avoid DoS.
In the future we might want to have a dynamic limit set by the
application, but for now a static one will do.
> h3: limit size of stream state buffer

- examples/http3-server.rs
The http3-server example doesn't respond at all to non-GET requests. This is not helpful to clients as it could be confused with some other (transport) error.
Since the example is simple, we just default to responding to these kinds of requests with a 405 Method Not Allowed.
> examples: respond to non-GET requests with 405

- src/build.rs
Builds that enable the `no_bssl` feature (e.g. the docs.rs build, or  anything that does `cargo build --features no_bssl` return an unreachable code warning because of an early return. 
This change substitutes the conditional compile for a build-runtime-check.
> build: avoid unreachable code warning for no_bssl feature buids

- examples/client.c
- examples/http3-client.c
- include/quiche.h
It should be similar to SSL_get0_alpn_selected
> ffi: fix quiche_conn_application_proto function signature

- src/lib.rs
- src/stream.rs
> stream: use u64 to represent stream limits

- examples/http3-server.rs
The build_response() never returns an error, so there's no point in
using Result as return value. This in turn removes a couple of layers of
indentation from handle_request().
> http3-server: minor clean-up

- src/h3/frame.rs
- src/h3/mod.rs
- src/h3/stream.rs
This changes the poll() function such that frames received on a stream
are handled immediately, rather than being queued for later processing.
This simplies the general architecture of the HTTP/3 implementation, and
removes a slight potential for abuse, since the stream's frame queue
didn't have a limit. In addition this removes the need to loop through
all streams when poll() is called, to handle previously queued frames.
Benchmarks show some improvement, though this also enables further
optimizations in the future:
```
http3/128000            time:   [3.1744 ms 3.3412 ms 3.4806 ms]
change: [-19.469% -10.427% -0.5146%] (p = 0.04 < 0.05)
Change within noise threshold.
http3/256000            time:   [11.336 ms 11.527 ms 11.689 ms]
change: [-10.013% -7.8772% -5.7020%] (p = 0.00 < 0.05) …
```
> h3: streamline poll()

- src/lib.rs
- src/stream.rs
We currently iterate over all streams in many cases (e.g. to create readable/writable streams iterators, checking for streams that need to send MAX_STREAM_DATA, ...), but in most cases a more efficient option would be to keep track of streams that need some action separately from the main stream map, and simply iterate over that list.
The overall improvement is pretty fantastic:
```
http3/128000            time:   [1.1004 ms 1.1867 ms 1.2631 ms]                         
change: [-72.075% -69.050% -65.596%] (p = 0.00 < 0.05)
Performance has improved.
http3/256000            time:   [2.7900 ms 2.8375 ms 2.8781 ms]                          
change: [-77.717% -77.201% -76.668%] (p = 0.00 < 0.05)
Performance has improved.
http3/512000            time:   [4.4683 ms 4.5074 ms 4.5411 ms] …
```
> Optimize stream iterators

- src/lib.rs
Spec says that we need to restart idle timer when sending an
ACK-eliciting packet, but only if we haven't sent an ACK-eliciting
packet since last receiving a packet.
---
TODO:
> (re)start the idle timer when sending an ACK-eliciting packet

- src/stream.rs
When the SendBuf maximum offset matched the stream's max data limit, we
would fail to propagate the fin flag properly into the output range
buffer.
> stream: fix off-by-one max data check in SendBuf::pop()

- src/stream.rs
Before, we would propagate the fin flag from zero-length writes by
creating an empty RangeBuf and queueing it into the SendBuf.
However due to the `out_len > 0` loop check, SendBuf::pop() would fail
to process the empty buffer if the `max_data` parameter matched the
amount of data stored in SendBuf.
As an example, assume that SendBuf has two buffers:
1. "hello", off=0, len=5, fin=false
2. "",      off=5, len=0, fin=true
(the second buffer being zero-length).
If SendBuf::pop() is called with `max_data = 5`, the second buffer would
not be removed from the queue, and the fin flag wouldn't be returned.
Instead make SendBuf::pop() match the output buffer's maximum offset
against the known final offset, this way we don't need to actually queue
the fin=true empty range buffer in the first place.
> stream: properly propagate fin from zero-length writes

- examples/client.c
- examples/client.rs
- examples/http3-client.c
- examples/http3-client.rs
- examples/http3-server.c
- examples/http3-server.rs
- examples/server.rs
- include/quiche.h
- src/ffi.rs
- src/lib.rs
- tools/http3_test/src/runner.rs
> rename disable_migration -> disable_active_migration

- src/octets.rs
> octets: fix macro parameter expansion inside unsafe block

- src/lib.rs
Currently if idle timer is lower than loss timer, but loss timer is not
None, we will pick the loss timer over the idle one, so we might end up
never timing out the connection if there are outstanding packets that
have not been acknowledged.
> pick lowest between idle and loss detection timers

- .travis.yml
- src/lib.rs
Requires a slight tweak to a test.
> deps: update BoringSSL submodule

- .travis.yml
To distinguish from MacOS build, I added `xcode11.2`.
> Add iOS build to CI

- .gitmodules
some countries can't access to G source
> update submodle boringssl url from G source to github mirror

- src/lib.rs
We shouldn't send 1-RTT packets before the handshake is completed (i.e.
before receiving the Finished message) as per RFC8446, section 4.4.4.
This is already enforced a few lines later for normal packets, but the
error and probe cases were missed.
> don't send 1-RTT packets before the handshake is complete

- extras/nginx/nginx-1.16.patch
Not sure what's up with the whitespace changes, but git created the patch, so :man_shrugging:
> extras/nginx: sync patch

- src/frame.rs
- src/lib.rs
- src/recovery.rs
This takes us a bit closer to the current draft, though there are still a bunch of things we don't do.
> recovery: merge crypto timeout and PTO

- src/lib.rs
Before we would only consider bytes of valid QUIC packets to limit the
amount of sent bytes before address validation, however this is way too
strict, as to avoid amplification we just need to count *any* bytes
received from clients.
Notably Firefox pads Initial packets at the datagram level, rather than
within QUIC packets, which would appear to us as invalid packets so
wouldn't be counted towards the anti-amplification allowance.
> relax the anti-amplification byte count

- extras/docker/Dockerfile
> Consolidate COPY in Dockerfile

- src/h3/mod.rs
- src/lib.rs
- src/stream.rs
Drop state of streams that are completed to save memory. We still need
to track completed streams though, to prevent a peer from reusing closed
ones.
> collect memory from completed streams

- .travis.yml
This should hopefully speed CI builds up a bit.
> travis: enable cache for cargo

- src/lib.rs
- src/recovery.rs
This makes PTO consistent with loss detection, which is already per
packet number space.
Besides aligning the implementation to the -recovery draft, this also
fixes some recovery bugs that were introduced in 5c99278, which caused
some packets to not be retransmitted when lost during the handshake.
---
I tested this manually using the http3-client and http3-server examples, and qvalve with the following scripts:
```
> h1 drop
```
```
< i1 drop
```
```
< h2 drop
```
Though it's pretty obvious the recovery code needs tests. I'll make a separate PR for that once I figure out how to do it.
> recovery: PTO per packet number space

- src/lib.rs
There's no need to add a PING frame to the PTO probe if the packet is
already ack-eliciting anyway.
> avoid sending a PING frame if the packet is already ack-eliciting

- .travis.yml
- tools/qlog/Cargo.toml
- tools/qlog/README.md
- tools/qlog/src/lib.rs
Adds just a qlog data model crate and some unit tests.
> tools: add a new crate for qlog data model

- src/h3/mod.rs
When "close()" is called (e.g. due to an internal error) the connection
(both transport and HTTP/3 one) might be in a broken state, so we should
avoid doing any work that might cause undefined behavior.
> h3: return early from poll() when the connection is closing

- include/quiche.h
> Fix coding style

- .travis.yml
- Group similar platform builds into one.
- Total number of build is reduced from 10 to 6
- When possible build everything as debug to utilize
build cache as much as possible
Result: total CI build time is reduced from 28 min (master) to 21 min.
> Travis: update build config

- src/cc/reno.rs
> reno: reset to MINIMUM_WINDOW in collapse_cwnd()

- src/recovery.rs
We already check if an acked packet number has already been acked by
comparing it to the lowest unacked packet number we hold. However this
means that we will still need to loop through all acked packets.
By doing the check earlier, we can break out of the loop without having
to check all following packet numbers. Given that we process acked
packet numbers from largest to lowest, we can assume that as soon as we
find an already-acked packet number all following numbers are also
already acked.
> recovery: do lowest unacked packet number check earlier

- src/lib.rs
Currently we only take into consideration the stream's flow control
capacity when limiting stream writes. However we really should also
take the connection's flow control cap, as well as the congestion
window size.
This should prevent excessive buffering (buffer bloat) on bad network
conditions (this is also potentially a DDoS vector, as a bad client
might force us to buffer data).
Of course the cwnd can decrease at any moment, so we might still end up
buffering more than what we can actually send, but this is already the
case anyway, so it doesn't get any worse.
---
I did some tests and this doesn't seem to affect throughput on good network conditions. We might want to test with more packet loss though.
> limit stream send capacity with connection flow control and cwnd too

- tools/apps/src/lib.rs
When doing a large amount of requests, quiche-client is quite chatty,
even though I only care about the final report (and the response data).
> apps: silence or downgrade some logs in the client

- src/lib.rs
When sender is on 32bit architecture and sends a file bigger than
4Gbytes (>= 2^32), send_capacity() rolls over at 2^32 and may return
incorrect (very small) capacity. This patch will make sure
send_capacity() returns a correct size on 32bit architecture where
usize is 32bit.
It can happen when quiche sender is on 32bit platform.
> Fix when sending a large data in 32bit arch

- tools/apps/src/lib.rs
> apps: clearer error message when dumping responses

- src/cc/reno.rs
- src/lib.rs
- src/recovery.rs
This is implementation of Delivery rate estimation according to draft
https://tools.ietf.org/html/draft-cheng-iccrg-delivery-rate-estimation-00
> Implementation of Delivery rate estimation

- src/lib.rs
Instead of limiting the output buffer capacity, account for the maximum
packet size in `left` itself. This way we only have one way to limit the
packet size instead of two.
> refactor calculation of output packet size limit

- src/h3/mod.rs
Previously, when sending HEADERS and DATA frames,
we used separate send_stream() calls for the type,
length and payload. This change combines the
type and length send into one but keeps payload
sending separate in order to avoid unnecessary
copies of a potentially large amount of bytes.
> h3: condense frame type and length sends

- clippy.toml
- src/lib.rs
- src/stream.rs
This implements sending `DATA_BLOCKED` and `STREAM_DATA_BLOCKED` frames.
> Data blocked

- src/lib.rs
Processing of packets with an invalid payload length will fail
"naturally" during packet decryption, so we don't need an explicit check
for this.
But add a test just to make sure that remains true.
> don't explicitly check that payload length fits in the input buffer

- src/lib.rs
As per the comment, this needs to be done as early as possible, so that
we still increase the limit in case of errors and the like. This is
fine, as we only need to keep track of how many bytes the peer sent to
us, whether valid QUIC bytes or not.
This makes it possible to convert a couple other cases where incoming
packets are ignored to use `drop_pkt_on_err()` for consistency.
After this, we _might_ want to remove
db5e6acd59a4d15eb6f79a68d315a60bd729570e, though not sending
CONNECTION_CLOSE on the first invalid packet received might still be a
good idea (e.g. for DDoS prevention purposes).
> increase anti-amplification limit earlier

- tools/apps/src/lib.rs
I wanted to add some tests that use querystring parameters and noticed that we actually fail to respond to anything that includes one. 
This change adds a few basic improvements to the area of request processing: it validates the scheme, it reconstructs and validates the URL of the object, and finally pulls out just path element of the URL which is used to retrieve the file.
A follow up PR can build on this by pulling out the querystring element now the groundwork is laid down.
> tools: improve HTTP/3 request processing

- src/lib.rs
- src/recovery.rs
- src/recovery/delivery_rate.rs
- src/recovery/reno.rs
Just a few small recovery fixes and improvements.
> Recovery fixes

- tools/apps/src/bin/quiche-client.rs
- tools/apps/src/bin/quiche-server.rs
- tools/apps/src/lib.rs
add --cc-algorithm=<name> option to configure which
congestion control algorithm to use when sending data.
> apps: add --cc-algorithm option

- src/lib.rs
We are not supposed to process incoming 1-RTT packets before the
handshake is completed, so we explicitly check for this situation
when processing incoming packets.
However since f902b76 this is already done by BoringSSL. Notably, it
won't set the read 1-RTT traffic secrets until after the handshake is
completed (but write secrets will be available earlier in order to
support 0.5 RTT on the server). So we don't need to check for this on
the quiche side as the packet will not be decryptable due to lack of
keys.
Note that the "early_1rtt_packet" test still passes after this change,
but if the BoringSSL update from f902b76 is reverted, then the test will
fail (as expected).
> don't explicitly check for early 1-RTT packets

- src/lib.rs
When accepting early data, the server needs to be able to send data in
the 0.5 RTT before the handshake is completed, otherwise there would be
no difference from normal 1-RTT data handling.
Note that this doesn't handle the HTTP/3 case right now. That is, hTTP/3
control streams are still only opened after the handshake is completed
when not in 0-RTT.
---
Will need some more testing to make sure it doesn't accidentally start sending 1-RTT data too early.
> allow sending 0.5 RTT data when 0-RTT is used

- README.md
- remove 32bit targets (#521)
- add Xcode version tested (#520)
> build: update iOS instruction

- src/h3/mod.rs
This is to address issue #530 . Please review. Thanks.
> update doc for h3 Connection::send_response

- src/lib.rs
Same idea of #525 but we need a little change because
after we normally send MAX_DATA the next call of
should_update_max_data() returns false so no way to
trigger retransmit.
The change is to have a similar way of updating
MAX_STREAM_DATA. The connection is marked as full and
trigger to send MAX_DATA when self.almost_full is true.
> retransmit MAX_DATA when lost

- src/tls.rs
This is required to fix accepting early data, that was broken by the
last BoringSSL update (but only for some implementations for some
reasons, so this wasn't caught at the time). BoringSSL also needs to be
updated as well, because the logic from the previous update was wrong.
The "early data context" is used by BoringSSL to decide whether early
data should be accepted or not. In theory this should include the
transport parameters and HTTP/3 SETTINGS in wire format, so that early
data can be accepted on a connection only if they match the ones from
the original connection.
However this is slightly annoying as it would require re-encoding
transport parameters _excluding_ the ones that shouldn't be remembered
when using 0-RTT, as well as exposing some kind of API to allow the
HTTP/3 layer …
> tls: configure early data context

- src/lib.rs
> correctly log local TPs to qlog

- src/lib.rs
- src/stream.rs
Featuring fixes by @LPardue.
This implements a very simple scheme for stream prioritization at the
transport layer. Each stream can be prioritized with an urgency level (a
number from 0 to 255 where lower is more important), as well as an
"incremental" flag.
Internally, instead of keeping a single queue for all scheduled streams,
an ordered map of lists is used instead. Each list holds the streams
that are scheduled at a given urgency level. When flushing data, the
non-empty list with the lower urgency level is used first.
Each urgency list is in turn split into two queues, one for
non-incremental streams, that are flushed fully in a FIFO order, and one
for incremental ones that are round-robined. Non-incremental streams at
the same urgency level take priority.
Currently priority is only …
> stream: initial support for prioritization

- src/lib.rs
Also slightly refactor existing check to avoid repeating the same
constant over and over.
Fixes #565.
> reject invalid STREAMS_BLOCKED frames

- src/lib.rs
This depends on https://github.com/cloudflare/quiche/pull/571
> bundle ACK with PTO probes

- src/lib.rs
When the type field in a long header packet is corrupted from Handshake
to Initial, the payload length field is instead interpreted as token
length which leads to failure when we try to actually parse the payload
length.
Instead use the `drop_pkt_on_err()` trick when parsing the payload
length fails.
Fixes #614.
> ignore failure to parse payload length

- src/recovery/mod.rs
- src/recovery/reno.rs
Implements https://github.com/quicwg/base-drafts/pull/3917
> cc: use bytes counting in reno congestion avoidance

- src/h3/ffi.rs
- src/recovery/mod.rs
Fix a build failure with rust 1.46.0
> build: rust 1.46.0

- src/lib.rs
No functional change, just cosmetic. It still looks kind of gross, but
IMO better than before.
> refactor open AEAD selection

- src/frame.rs
- src/lib.rs
- tools/qlog/src/event.rs
As per the new clippy warnings.
> use matches! macro

- .github/workflows/deploy.yml
* Clone submodules as well
* Don't set name explicitly (to be consistent with other jobs)
> ci: fix Docker deployment

- .github/workflows/deploy.yml
- .github/workflows/nightly.yml
- .github/workflows/stable.yml
The only missing build now is Android. Haven't figured out how to add that yet.
> More GitHub Actions

- src/frame.rs
- src/lib.rs
- src/stream.rs
This updates the `SendBuf` API so that data can be written directly to the output packet buffer, rather than have to allocate an intermediate buffer, copy the data to that, and then copy the intermediate buffer to the output packet. Refer to the specific commits for more details.
The overall changes are somewhat intricated, so they need to be reviewed and tested carefully...
The next step will be allocating `RangeBuf`s with consistent sizes.
> SendBuf emit API

- src/lib.rs
In order for packet encryption to work properly, the payload needs to be
at least 4 bytes. When that is not the case, PADDING frames are added to
reach the minimum length.
It might happen however that there is no space left in the packet to add
this padding. Before commit 33ac0f21db8f1d1ffb4efed84202bceff496c0e5 we
would simply add the padding anyway, however in that commit, the
relevant code was changed to use push_frame_to_pkt!() to add the frame
to the packet, which will prevent adding more bytes than allowed. This
in turn lead to the padding not being added in some cases (e.g. when the
server is blocked by the anti-amplification limit).
Instead of forcing the frame to be added even if there is no space,
simply return early on if we can't write enough bytes.
> ensure there is enough space for the minimum payload length

- .github/workflows/stable.yml
- src/build.rs
Add aarch64/arm for linux support to build.rs and CI.
> build/CI: cross build for ARM

- .github/workflows/stable.yml
iOS and Windows: use `matrix` for building multiple targets in parallel.
> CI: Use matrix for building multiple targets

- src/h3/frame.rs
- src/h3/mod.rs
- src/h3/stream.rs
- src/lib.rs
> H3 dgram setting

- src/lib.rs
The references returned by these methods are keeping the lock alive, so
the following call blocks.
---
This should hopefully be the last one... until we had more that is.
> fix deadlock in qlog logs

- src/lib.rs
This can be useful to applications to know when to stop sending /
expecting new data to / from a connection.
> add Connection::is_draining() method

- include/quiche.h
> ffi: fix poll() return value in include file

- src/h3/qpack/encoder.rs
I assume this the comment refers to this [section](https://tools.ietf.org/html/draft-ietf-quic-qpack-19#section-4.5.1.1).
> Cleanup QPACK comment in the code: Required Insert Count

- Cargo.toml
- tools/qlog/Cargo.toml
So that we can cut a new release
> qlog: bump version

- src/h3/mod.rs
- src/h3/stream.rs
This is forbidden, so we should be strict about this. A couple of tests
depended on this behavior being allowed, so they need to be updated.
> h3: forbid DATA frames before HEADERS

- README.md
cloudflare-quic.com is more official.
> README: update mention of test server

- src/h3/mod.rs
Instead of delegating this to the application, make sure the connection
is closed with the appropriate error code, like in the other error
cases.
> h3: close connection when processing HEADERS fails

- extras/nginx/nginx-1.16.patch
Update NGINX patch with latest HTTP/3 fixes.
> Sync NGINX patch

- src/h3/frame.rs
Previously, quiche would parse SETTINGS frames with any valid size.
There are only a few settings parameters defined in the core HTTP/3
specification, and although we should accomodate extensions or GREASE,
it seems unlikely that we'll receive legitimate frames that are large.
This change adds an implementation limit for the size of SETTINGS
frames. Frames larger than the limit will trigger a connection error.
> h3: limit the size of SETTINGS frame that quiche is willing to parse

- .github/workflows/stable.yml
- README.md
- tools/android/build_android.sh
- tools/android/build_android_ndk19.sh
> enable 'ffi' feature in docs / scripts that need it

- src/recovery/cubic.rs
- src/recovery/hystart.rs
- src/recovery/mod.rs
- src/recovery/reno.rs
Current hystart++ implementation has a few issues:
- hystart.on_packet_acked() returns a new cwnd/ssthresh and
decide if it need to enter LSS. However during slow start
and congestion avoidance, it will confuse CC's ABC
based cwnd/ssthresh calculation, resulting higher cwnd growth
with HyStart++ during slow start and LSS episode.
(CUBIC and Reno)
- hystart LSS cwnd calculation is not ABC based,
can result in higher cwnd growth then expected (no
L x MSS upper limit)
- Reno slow start: mixed use of bytes_acked in slow start
and congestion avoidance. It will result in miscalcuation
of cwnd.
Changes:
- hystart: remove on_packet_acked() and add try_enter_lss()
for checking if CC can enter LSS. cwnd/ssthresh will be
changed from the caller. Also added in_lss() for a
shortcut of checking the …
> cc: fix hystart++ bugs and excessive cwnd growth

- README.md
> Fixes issue #844.

- src/lib.rs
A connection send capacity is limited by the size of the flow and
congestion windows. However, cwnd is not reduced between stream_send()
calls, which might cause more data than necessary to be buffered.
Instead of using the current available cwnd size for each call, buffer
the value and reuse it over a single "flight".
> limit send capacity over multiple stream_send() calls

- src/h3/mod.rs
- src/lib.rs
Currently the `recv_send()` function in the testing module coalesces
multiple packets into the same buffer. This is problematic because it
can potentially coalesce multiple 1-RTT packets into the same pseudo UDP
datagram, which is not allowed.
This change reworks how packets are sent and received between client and
server in the tests, by splitting each flight into multiple buffers, one
for each UDP datagram, which more closely simulates what actually
happens on a network.
Incidentally it also removes the need for each test to have its own
buffer, which slightly simplifies writing tests.
---
Basically I was looking into implementing https://github.com/cloudflare/quiche/pull/802#issuecomment-758077314 but that would break many tests currently, so need to fix this first.
> refactor packet sending/receiving in testing framework

- src/lib.rs
- src/stream.rs
This also ensures that the stream's send buffer is considered "complete"
when all previously buffered data is dropped, by marking all the dropped
data as acked, so that the stream can be collected properly.
> send RESET_STREAM frame when stream's write-side is shutdown

- include/quiche.h
- src/ffi.rs
ffi users want to load self signed root chains too :)
> add load_verify_locations_from_file to ffi

- src/lib.rs
Sending packets with no frames is forbidden.
> reject packets with empty payloads

- src/lib.rs
Follow-up to 77064a32, which caused multiple probe packets of the same
type to be coalesced together.
> avoid coalescing probes of the same type

- src/h3/mod.rs
`send_body()` attempts to constrain writes to within stream capacity
limits. Previously, it would prevent writing a 0-length DATA frame if
the stream capacity would not allow it to send the frame overhead and at
least 1 byte of payload.
Assuming it is desirable to send 0-length DATA with fin=true when the
stream has capacity for only the frame overhead, the current behavior
adds at least an RTT for flow control to add 1 byte that won't actually
be used.
Assuming it is undesirable to send 0-length DATA with fin=false,
send_body would allow that if there was stream capacity.
This change reworks send_body to be more consistent when handling
0-length DATA frames. It returns Error::Done in any condition where
0-length with fin=false occurs, and Ok(0) when 0-length with fin=true
occurs.
> h3: update 0-length DATA frame send behavior

- src/lib.rs
Currently, incoming packets that can't be decrypted because the
corresponding read keys are not available yet are simply dropped. On the
server side this can happen with 0-RTT packets, for example if an early
handshake callback configured in BoringSSL delays installation of read
keys.
This change implements buffering a limited number of 0-RTT packets
received before the corresponding read keys are installed, for a short
period, so that they can be correctly processed at a later time. The
buffer is limited to 10 packets (no particular reason for this number,
though it is also what Chrome uses), and it should be drained as soon as
keys become available.
It can also happen that the server ends up rejecting 0-RTT anyway, in
which case the buffer is cleared as soon as the handshake is …
> buffer undecryptable 0-RTT packets

- tools/qns/run_endpoint.sh
Also includes some slight clean-up of the script.
> Fix QNS resumption test

- src/lib.rs
Commit 877bace8 added support for buffering undecryptable 0-RTT packets
and processing them when 0-RTT read keys become available.
One notable change was the fact that packets could be processed as part
of the `Connection::send()` method, which does call the `do_handshake()`
method for advancing the handshake state, but it doesn't try to parse
and configure the peer's transport parameters, unlike the
`Connection::recv()` method which tries to parse transport params when
receiving CRYPTO frames
This could cause a server to be unable to reply to buffered 0-RTT data
due to missing flow control credits.
This change moves the parsing and configuration of peer transport params
directly into the `do_handshake()` method, so that those actions are
always executed when the handshake is advanced.
> fix processing peer transport parameters during early data

- src/lib.rs
When we queue 0-rtt packets in undecryptable_pkts, check
the packet length (payload_len) and its actual buffer size
and return CryptoFail error if the packet size is smaller than its
length field in the packet payload.
This is to prevent the case that actual packet length is smaller
than the size in the payload (packet length field) which may
cause a runtime panic. Such packet is undecryptable in any way,
so drop it when received.
> check 0-rtt packet length when queueing

- src/lib.rs
Motivation:
We should validate that the version is valid that was used to create the Config object and if not fail.
Modifications:
- Add validation for the version
- Add some tests
Result:
Version is validated during config creation
> Validate that a valid version is specified when create a Config

- include/quiche.h
Seems we missed the header file...
> h3: make quiche_h3_recv_dgram signature consistent

- src/recovery/cubic.rs
- Update based on https://github.com/NTAP/rfc8312bis/pull/3
- Fix congestion avoidance test
> cc: CUBIC - redefine K equation

- src/recovery/cubic.rs
- Update based on https://github.com/NTAP/rfc8312bis/pull/24
- Fix congestion avoidance test
Based on #861.
> cc: CUBIC - AIMD approach for tcp friendly window

- src/lib.rs
For Initial packets we need to make the UDP datagram at least 1200
bytes following the transport spec. However when the last packet
in the datagram is Short and the datagram is not fully filled, we try
to do null padding at the end which causes a decryption failure on
the server because Short packet doesn't have an explicit length.
To avoid this issue, when Short packet is added in the same
datagram with Initial packet, add a PADDING frame to Short packet
to fill up the datagram size. If Short packet is not added,
we still add zero padding at the end of packet.
> Add PADDING frame to fill up the datagram with Initial packet

- src/lib.rs
Instead of using a static value of what the frame overhead _could_ be,
use the actual header length value that is available.
> calculate max CRYPTO frame length more accurately

- src/lib.rs
When there is no new data or ack to be sent, send_single()
sets app_limited=false and returns Error::Done. When
next ACK received, it mistakenly increases cwnd even though
current bytes-in-flight is much smaller than cwnd.
---
100MB download (quiche-client and quiche-server) case: (see cwnd)
master branch
```
[2021-05-27T06:19:58.546815000Z INFO  quiche_apps::client] connection closed,
recv=80932 sent=6803 lost=0 rtt=26.054978ms cwnd=368152
```
This PR
```
[2021-05-27T06:17:48.736729000Z INFO  quiche_apps::client] connection closed,
recv=80988 sent=5943 lost=0 rtt=27.08362ms cwnd=13500
```
> don't update app_limited when no new frame generated

- src/h3/mod.rs
Previously, if `quiche::h3::with_transport()` failed to initialize the
HTTP/3 connection for any reason, it would return an error and rely on
the caller to tidy up the QUIC connection. This is inconsistent with how
other parts of quiche's HTTP/3 layer deal with low level issues.
This change ensures the QUIC connection is closed before returning the
reason to the caller.
> h3: close QUIC connection when unable to initialize HTTP/3

- src/h3/mod.rs
- src/lib.rs
Adding to call set_ack_delay_exponent() in other places where Config is initialized.
> Fix more flappy test

- extras/nginx/nginx-1.16.patch
Fixes #980.
---
This turns @omarkilani's fix from #980 into a PR (based on top of https://github.com/cloudflare/quiche/pull/988 to avoid later conflicts), thanks!
> nginx: handle Content-Length correctly

- src/stream.rs
When processing incoming stream data, a whole bunch of logic is
dedicated to handling overlaps with data already received. This involves
looping over all buffered data.
However, when the incoming range buffer is past the buffered data range,
there is clearly no overlap, so the looping logic can be skipped.
> stream: in-order incoming data fast path

- README.md
Update example rust code to reflect a recent API changes.
> update README.md for new API changes

- src/recovery/cubic.rs
- src/recovery/mod.rs
- src/recovery/reno.rs
Some additional fixes to adaptive reordering thresholds.
> Adaptive reordering fixes

- src/lib.rs
This patch was written by prb@google.com and davidben@google.com.
> Fix typo in tests

- include/quiche.h
- src/ffi.rs
- src/lib.rs
> expose local_error to applications

- src/h3/mod.rs
- src/lib.rs
Regarding the `DATA` case, I think in the future we could change `send_body()` to not check the capacity and not slice the input buffer at all (so the frame header's length field will just be the full input buffer length), and then simply expect the application to do the right thing and write the remaining bytes once the stream becomes writable (applications _should_ be doing this already anyway to avoid dropping data, but they don't _have to_ do it), this way the capacity check would fall to the transport layer. The `send_headers()` case would still require "atomic" writes though.
Another idea would be to have a `stream_send_atomic()` method that either writes all data, or none of it, but that would require copying h3 headers/data into a single buffer, unless this is implemented in …
> add method to check if stream can hold more data

- src/lib.rs
- src/stream.rs
Let's just revert for now, we'll figure it out later (also see
https://github.com/cloudflare/quiche/pull/1049).
This reverts commit 6ee77a1f690f2a58d3c6a1c6e6b1e9aa09ac0790.
> Revert "zero-copy emit scatter API"

- src/recovery/cubic.rs
While the stored cwnd/ssthresh is in slow start state, don't try
rollback. This is not to delay to exit slow start when there is a loss.
> cubic: no rollback during slow start

- src/recovery/cubic.rs
Currently a fixed 10 packets threshold is used for detecting a small
loss. When cwnd is very high (more than 1000 packets, for example),
this makes the detection less sensitive. New approach is to make a
rollback threshold relative to cwnd (currently 20%) to make it work
with various size of cwnd in real time.
> cubic: proportional rollback threshold

- src/h3/mod.rs
Previously, if the connection-level flow control was 0 when we attempted
to create a new request stream via send_request() we would return the
result of stream_send() directly. This would cause an Error::Done to
be returned, which is not documented in the API.
Rather than have two different error types for a similar class of error,
with this change we ensure that Error::StreamBlocked is returned
consistently.
> h3: ensure StreamBlocked if send_request() blocked

- quiche/src/h3/mod.rs
This test didn't function as fully intended. With this change we ensure
the connection-level flow control gets filled before the request
attempt. Then ensure it is adequately increased by the server draining
some data out of the connection and emitting back MAX_DATA.
> h3: fix headers_blocked_on_conn() test

- quiche/include/quiche.h
- quiche/src/ffi.rs
> ffi: expose peer certificate to C API

- quiche/src/build.rs
When building the tarball from crates.io rather than from the git
repository, the target directory for the pkg-config file doesn't exist.
Note that when explicitly passing the --target option to cargo, this
changes the output directory from "target/<profile>/quiche.pc" (e.g.
"target/debug/quiche.pc") to "target/<target>/<profile>/quiche.pc" (e.g.
"target/x86_64-unknown-linux-gnu/debug).
Fixes #1142.
> build: fix pkg-config output path

- quiche/src/recovery/mod.rs
Previouly the pacing rate calculation is based on microseconds
level granularity. This updates the pacing rate calculation
granularity to the maximum allowed (nanoseconds) and simplifies
the formula by removing MICROS_PER_SEC constant.
> pacing: nanoseconds based calculation

- qlog/src/events/h3.rs
- qlog/src/lib.rs
- qlog/src/streamer.rs
- quiche/src/h3/frame.rs
- quiche/src/h3/mod.rs
- quiche/src/h3/stream.rs
- qlog: update HTTP/3 event definitions
- qlog: add add_event_data_now() method and tidy up docs
- h3: add qlogging support
> Add HTTP/3 qlogging support

- quiche/src/lib.rs
last_tx_data > tx_data can happen if tx_data decreases
when stopping the stream.
> fix overflow at delivery_rate_check_if_app_limited()

- quiche/src/lib.rs
- quiche/src/stream.rs
RFC9000 2.1: A stream ID that is used out of order results in all streams of that type with lower-numbered stream IDs also being opened.
> fix stream limit enforcement

- quiche/src/build.rs
Related to https://github.com/cloudflare/boring/pull/77
> MSVC generator hack should be only applied to MSVC

- .github/workflows/stable.yml
- quiche/src/build.rs
Related to https://github.com/cloudflare/quiche/pull/1254
> Using GNU ABI and fixing linking order suffice to build quiche with the MinGW toolchain

- quiche/src/h3/mod.rs
In an old version of the DATAGRAM poll event, it returned an HTTP/3 datagram
flow ID, which required peeking at the first 8 bytes of the QUIC frame
payload at the front of the queue.
When we changed to edge-triggered events, we changed the logic to
always return the placeholder value 0. However, we didn't change
the logic to avoid peeking at the data, which meant we left a
needless 8-byte allocation and copy.
This change removes the needless copy, replacing it instead with a check
of the queue length to determine if the edge-trigger should fire
or not.
> h3: avoid needless copy when checking dgram queue

- quiche/src/lib.rs
- quiche/src/tls.rs
In validating a peer's certificate chain, in case intermediate CAs are
present, it is necessary to retrieve the full chain exposed by the peer.
Only the root CA must be trusted present in the certificate store the caller
> tls: allow retrieving the full certificate chain exposed by the peer

- quiche/src/lib.rs
Previously, quiche would allow a sending endpoint to try and STOP_SENDING a locally-initiated stream, or RESET_STREAM a remotely-initiated stream. Both of these actions are semantically wrong, and prohibited by RFC 9000. On the receive side, quiche enforces these checks, meaning it is easy for an application to do the wrong thing and cause a connection to be terminated by the remote peer.
With this change, we add sender-side checks to prevent invalid behavior and instead return an error code.
Fixes #1317
> lib: prevent invalid unidirectional stream_shutdown

- quiche/src/lib.rs
Motivation:
There was some code-duplication which can be removed by adding function.
Modifications:
Add process_undecrypted_0rtt_packets
Result:
Share code / cleanup
> Add fn for processing undecrypted 0-rtt packets that can be reused

- quiche/src/tls.rs
Motivation:
We should just move map_result_ssl(...) to Handshake to be more consistent
Modifications:
Move map_result_ssl(...)
Result:
Cleanup
> Move map_result_ssl(...) function to Handshake.

- quiche/src/lib.rs
- quiche/src/recovery/mod.rs
- quiche/src/recovery/pacer.rs
Also clean-up comments somewhat.
> add config option to completely disable pacing

- quiche/src/tls.rs
Motivation:
We should set the local_error if the handshake fails with SSL_ERROR_SSL as we can't recover from it.
Modifications:
Set local_error when SSL_ERROR_SSL is received
Result:
Automatically close the connection on SSL_ERROR_SSL
> Set local_error if handshake fails with SSL_ERROR_SSL

- quiche/src/lib.rs
If a server does an app close after a connection is established, but before it has actually emitted the Handshake ack, the close will not be sent.
This is because, per spec, app close error codes must not be sent during the Handshake, however the app error prevents the handshake acknowledgement from being emitted.
This patch's test case may give a better example of how this issue may occur.
The resulting behavior of this patch is that the Handshake ack packet will be sent followed by a 1RTT with the connection_close.
Resolves #1118
I have been using this patch for a while without experiencing side effects, but there may be a better way of mitigating this issue.
> Fix server app close before 1RTT never getting sent

- quiche/src/lib.rs
This change provides a simple stateless reset detection that applications can prevent from using a connection that is supposed to be closed.
This PR completes the unfinished implementation on #1037
> Detect stateless reset

- README.md
Since it's public we might as well mention it :)
> README: add note about Android DNS over h3

- quiche/src/h3/mod.rs
- quiche/src/lib.rs
In PR #1170, we added a change to reduce the frequency of
STREAM_DATA_BLOCKED frames when using stream_send. Unfortunately, we
neglected to apply the same logic to the stream_writable() function.
The h3 layer explicitly calls stream_writable() when it can't write
the full amount of data passed to send_body(). stream_writable marks
the stream as blocked, howver, next the DATA frame gets truncated to
match the stream capacity before calling stream_send(). Inside, it
detects that capacity wasn't exceeded, so the stream isn't actually
and it gets unmarked blocked. It takes the *another* round of
send_body() to cause it to mark the stream as blocked via
stream_writable() and then it exits before any stream_send() (because it
literally can't send anything). This causes the first …
> lib: ensure stream_writable also checks blocked offset

- quiche/src/h3/mod.rs
Generally for framed streams (request or push streams) it is expected
to keep looping around reading as much data as possbile and returning
an Event when something worth an application's attention happened, such
as HEADERS, GOAWAY, DATA (although that is a special case of its own).
Internally, we run this loop inside process_readable_stream() and apps
can invoke it via the poll() method. If a stream presents an event,
poll() would check if the stream was finished, mark it if so, then return
the event. The next time poll() was called, the marking would cause a
Finished event to happen. This all works fine as long as a frame
triggers an event that breaks process_readable_stream()'s loop.
However, there can be several types of frame that don't need to be
bubbled up, like GREASE frames or …
> h3: exit process_readable_stream() gracefully

- Dockerfile
- apps/src/bin/quiche-server.rs
- apps/src/client.rs
- apps/src/common.rs
- qlog/src/events/mod.rs
- qlog/src/events/quic.rs
- qlog/src/lib.rs
- quiche/src/recovery/mod.rs
- tools/http3_test/src/runner.rs
Tests started failing clippy since rustc version 1.67
> Fix failing tests

- apps/src/common.rs
There are occaisons where the quiche-server will get blocked from
sending response headers. We already cater for this in the application
and store the request headers or body in order to retry once the
stream is reported as writable.
However, in the case of blocked headers, the response priority was
not stored and when the stream was unblocked, quiche-server did not
try to send_response_with_priority(). Together this meant that
responses that were blocked when attempting to send headers would
revert to a default priority.
With this change, we store the original priority that was intended
and make sure to use it on each retry attempt.
> apps: store response priority for retry after block

- quiche/src/h3/mod.rs
It can happen that the congestion window doesn't grow enough to accomodate a very large body buffer, in which case the corresponding stream is never reported as writable and it hangs.
Instead, just make sure the stream is reported when at least a few bytes can be sent. This uses the current write's "overhead" value, which is not necessarily accurate for future writes, but it should be good enough for our purposes.
> h3: reduce capacity requirement when sending partial body

- quiche/src/lib.rs
- quiche/src/tls.rs
Motivation:
We should downgrade the epoch to Initial if the remote peer cant decrypt yet, failing to do so might cause the remote peer to drop the frames on the floor and trying to resend.
Modifications:
Check if we need to downgrade to Intial and if so do it.
Result:
Remote peer can always handle frame
> Downgrade epoch to Initial if remote peer can't decrypt yet

- README.md
- quiche/src/lib.rs
> docs: Clarify using Config, especially params that can be zero

- quiche/src/lib.rs
Delivery rate app_limited flag should be updated based on checking buffered data size in send buffer.
> Update checking for delivery rate app_limited flag correctly

- quiche/src/h3/qpack/encoder.rs
- quiche/src/h3/qpack/huffman/mod.rs
Slightly better optimization of the Huffman encoding method, that emits bits in 8 byte chunks, instead of the current byte by byte implementation. The result is about twice as fast.
> Faster Huffman encoding

- quiche/src/lib.rs
- quiche/src/recovery/bbr/mod.rs
- quiche/src/recovery/pacer.rs
Fix BBR cwnd recovery logic during congestion episode.
> Fix BBR cwnd recovery logic and pacing

- quiche/include/quiche.h
- quiche/src/ffi.rs
- quiche/src/lib.rs
- quiche/src/recovery/mod.rs
- quiche/src/recovery/pacer.rs
Add support to provide API for setting max pacing rate.
> Provide an API to set max_pacing_rate

- qlog/src/lib.rs
- qlog/src/streamer.rs
- quiche/src/cid.rs
- quiche/src/flowcontrol.rs
- quiche/src/frame.rs
- quiche/src/h3/mod.rs
- quiche/src/h3/qpack/decoder.rs
- quiche/src/h3/qpack/mod.rs
- quiche/src/lib.rs
- quiche/src/packet.rs
- quiche/src/path.rs
- quiche/src/recovery/bbr/mod.rs
- quiche/src/recovery/cubic.rs
- quiche/src/recovery/delivery_rate.rs
- quiche/src/stream.rs
This PR was compiled with findings from:
```
cargo clippy --all-targets --all-features -- -Dwarnings
```
There were 3 other findings not included here because once those tests were fixed they started failing. Looking into that and hopefully there will be a subsequent PR fixing those as well.
> Clippy fixes

- apps/src/sendto.rs
Similar to #1483.
Fixes #1531.
> apps: fix Instant -> u64 conversion

- quiche/src/lib.rs
By default we return the maximum possible number of SCIDs that can be provided to the peer. However this is dangerous as each application will need to limit this anyway to avoid potential DoS, and in practice there doesn't seem to be much point in having different numbers of CIDs between a client and server, so this change limits the number to whatever is lowest between the clocally configured value and the peer's.
This also removes the `max_active_source_cids()` method as an application can still fetch the raw TP value from the stats if it needs to.
> automatically limit number of SCIDs that can be provded

- quiche/include/quiche.h
> ffi: remove declaration for non-existent function

- nginx/README.md
- nginx/nginx-1.16.patch
Haven't done this in a while... sync with internal repo.
> nginx: sync patch

- quiche/src/lib.rs
- quiche/src/stream.rs
Rather than use a custom BTree format, use the same RBtree that is used
for readable and writable stream tracking and prioritization.
~Note that this appears to break some path related tests, hence the draft status.~ Test errors were only observed in local dev due to one missing change that was fixed during final pass before opening PR.
> lib: migrate flushable to RBtree

- quiche/src/recovery/bbr2/mod.rs
- quiche/src/recovery/bbr2/pacing.rs
- quiche/src/recovery/bbr2/per_ack.rs
- quiche/src/recovery/bbr2/per_loss.rs
This is the same changes as https://github.com/cloudflare/quiche/pull/1521 which was automatically closed by GitHub and I can't reopen it anymore. It also needed some additional fixes due to other internal changes.
> bbr2: fixes and enhancements

- qlog/src/events/connectivity.rs
https://quicwg.org/qlog/draft-ietf-quic-qlog-quic-events.html#section-4.7
> qlog: add MTUUpdated event

- quiche/src/frame.rs
- quiche/src/lib.rs
> frame: reject NEW_CONNECTION_ID frames with invalid CIDs

- quiche/src/h3/frame.rs
We already had support for reading unknown frame times out of a stream, per the requirements of RFC 9114.
This change adds support for capturing the frame payload while reading rather than discarding it. This is useful for low-level or debug purposes.
We also add support for serializing "unknown" frames, allowing a raw type and an opaque payload to be converted to a wire format. Again this is useful for low-level or debug purposes.
Most HTTP/3 applications won't need these capabilities, so they are not exposed via any API changes.
> h3: extend support for unknown frames

- quiche/src/recovery/mod.rs
This ensure that when a PMTUD probe is lost we decrease the `bytes_in_flight` counter appropriately.
> recovery: ensure lost PMTUD probe bytes are removed from in-flight count

- quiche/examples/client.c
- quiche/examples/server.c
- quiche/include/quiche.h
- quiche/src/ffi.rs
Fixes #1699.
As discussed in that issue, it's fine to change the API.
> Expose stream application error in FFI

- apps/src/bin/quiche-server.rs
Attempting to attach to the quiche-server process fails due to an interrupted syscall when mio attempts to `poll` for new events. This PR will retry the `poll` call until it succeeds.
Terminal 1: `RUST_LOG=trace cargo run --bin quiche-server -- --cert ./apps/src/bin/cert.crt --key ./apps/src/bin/cert.key --listen 127.0.0.1:8085`
Terminal 2: `strace -p $(pgrep quiche-server)`
Before this patch, the quiche-server process fails due to the panic described above. With this patch, it succeeds and you can hit it as normal. We also see the `trace!`d log line
> apps: retry mio `poll()` call when it fails in quiche-server

- quiche/src/path.rs
We extracted them out of Stats and they have their own method
> Fix PathStats doc

- h3i/src/prompts/h3/headers.rs
> h3i: Don't panic on empty header block

- quiche/src/h3/mod.rs
The documentation already described what should happen but the code was
missing the check.
> h3: enforce send_response() before send_additional_headers()

- h3i/src/recordreplay/qlog.rs
- quiche/src/h3/mod.rs
> fix clippy warnings

- quiche/src/crypto/boringssl.rs
- quiche/src/crypto/mod.rs
- quiche/src/crypto/openssl_quictls.rs
Both BoringCrypto and OpenSSL provide APIs for HKDF, though not quite as nice as ring's, but no point in pulling a whole dependency just for that. This is also required (but not sufficient) for FIPS.
The change involves replacing the uses of `Salt` and `Prk` types exposed by ring, with raw `Vec<u8>` to store intermediate secrets, which can then be passed to BoringCrypto and OpenSSL via FFI.
Note that ring is still used to generate header protection keys, which will be replaced next.
> crypto: replace ring HKDF API

- quiche/Cargo.toml
- quiche/src/ffi.rs
- quiche/src/frame.rs
- quiche/src/tls/mod.rs
The major difference is use of unions and better compile times
> Replace winapi with windows-sys

- Cargo.toml
- Dockerfile
- apps/Cargo.toml
- h3i/Cargo.toml
- octets/Cargo.toml
- qlog/Cargo.toml
- quiche/Cargo.toml
Also bump edition to 2021 while at it.
> Cargo: unify some metadata across workspace

- .github/workflows/stable.yml
- Cargo.toml
- apps/Cargo.toml
- apps/src/bin/quiche-server.rs
- apps/src/client.rs
- apps/src/sendto.rs
- h3i/Cargo.toml
- tokio-quiche/Cargo.toml
- tokio-quiche/src/http3/driver/datagram.rs
- tokio-quiche/src/http3/driver/mod.rs
- tokio-quiche/src/lib.rs
- tokio-quiche/src/quic/router/mod.rs
- tokio-quiche/tests/fixtures/h3i_fixtures.rs
The nix version on the workspace is actually lower, so I downgraded the version used by apps too.
Only other incompatible thing was url, but that just require a slight change in how addresses are resolved.
> apps: more workspace dependencies

- quiche/src/lib.rs
Previously, it was common for quiche to log a connection_closed
event with a trigger value of "error". This was caused by some
simple checking of peer_error or local_error inside of the
quiche library when closing the connection.
This change tweaks the logic in mark_closed() just a little. If
the error was at the transport-level with the QUIC NO_ERROR code,
we'll mark it as "clean". Any other transport code remains
as "error". If the error was at the application-level, we are
not application protocol-aware and can't make any reliable guess
about what a code means, so it it better to omit the trigger.
> lib: change qlog connection_closed trigger value

- datagram-socket/src/datagram.rs
- tokio-quiche/src/http3/driver/mod.rs
`now_or_never()` can spuriously return None even if the underlying is Future is ready.  This is due to tokio's cooperative scheduler returning Pending if a task's coop budget is exhausted. We can avoid this by wrapping the future in a `tokio::task::unconstrained()`
> Fix now_or_never() spuriously returning None

- tokio-quiche/src/quic/mod.rs
- tokio-quiche/src/socket/connected.rs
We used to always apply maximum `SocketCapabilities` to UDP sockets passed into `connect_with_config()`. However, some NICs don't support hardware GSO and Linux currently doesn't provide a software fallback. To better support those setups, we now allow users to specify capabilities manually in our connected `Socket` struct. This matches the interface we have for server-side `QuicListener`s.
The default changes to not apply any capabilities to avoid surprises. Client-side usage doesn't benefit as much from the capabilities anyway.
**Note: this is a breaking change**
> tokio-quiche: Allow user-provided SocketCapabilities in connect

- quiche/Cargo.toml
- quiche/src/lib.rs
- quiche/src/path.rs
- quiche/src/recovery/congestion/bbr/mod.rs
- quiche/src/recovery/congestion/bbr2/mod.rs
- quiche/src/recovery/congestion/cubic.rs
- quiche/src/recovery/congestion/delivery_rate.rs
- quiche/src/recovery/congestion/recovery.rs
- quiche/src/recovery/congestion/reno.rs
- quiche/src/recovery/mod.rs
Followup to https://github.com/cloudflare/quiche/pull/1986, introduce trait that will be used to integrate the gcongestion implementation into quiche recovery.
See https://github.com/cloudflare/quiche/pull/1983 for followup changes.
> Introduce interface to integrate with gcongestion

- quiche/src/recovery/congestion/recovery.rs
- quiche/src/recovery/gcongestion/bandwidth.rs
- quiche/src/recovery/gcongestion/bbr.rs
- quiche/src/recovery/gcongestion/bbr/bandwidth_sampler.rs
- quiche/src/recovery/gcongestion/bbr/windowed_filter.rs
- quiche/src/recovery/gcongestion/bbr2.rs
- quiche/src/recovery/gcongestion/bbr2/drain.rs
- quiche/src/recovery/gcongestion/bbr2/mode.rs
- quiche/src/recovery/gcongestion/bbr2/network_model.rs
- quiche/src/recovery/gcongestion/bbr2/probe_bw.rs
- quiche/src/recovery/gcongestion/bbr2/probe_rtt.rs
- quiche/src/recovery/gcongestion/bbr2/startup.rs
- quiche/src/recovery/gcongestion/mod.rs
- quiche/src/recovery/gcongestion/pacer.rs
- quiche/src/recovery/gcongestion/recovery.rs
- quiche/src/recovery/mod.rs
- quiche/src/recovery/rtt.rs
See https://github.com/cloudflare/quiche/pull/1983 for the full chain of commits.
> [gcongestion] BBRv2 gcongestion implementation, not hooked into the recovery module yet.

- quiche/src/lib.rs
> add method to check if pacing is enabled after connection is created

- quiche/src/recovery/gcongestion/bbr/bandwidth_sampler.rs
The A0 point is used in bandwidth computations when BW over-estimation protections are enabled (the default).
Without this change, BW is under estimated in some edge cases.
> Fix inconsistency in BBR2 A0 point selection logic between cloudflare/quiche and google/quiche

- tokio-quiche/src/quic/io/worker.rs
If a server ACKs a packet containing a HEADERS frame in the same flight that the handshake completes, the Handshake IOW must have taken all packets out of the context's `incoming_pkt_receiver`.
That means that the first iteration of the `RunningApplication` work loop will no-op - since `did_recv` is false, that iteration won't call `h3::Connection::poll()`. We therefore unconditionally call `on_read()` before starting the `RunningApplication` work loop to prevent this case.
>  Unconditionally call process_reads() in RunningApplication phase

- quiche/src/lib.rs
- quiche/src/path.rs
- quiche/src/pmtud.rs
- quiche/src/recovery/congestion/bbr/mod.rs
- quiche/src/recovery/congestion/bbr2/mod.rs
- quiche/src/recovery/congestion/recovery.rs
- quiche/src/recovery/congestion/test_sender.rs
- quiche/src/recovery/gcongestion/recovery.rs
- quiche/src/recovery/mod.rs
This makes some of the internal state variables in pmtud.rs more
intuitive, and in general makes the code easier to reason about.
> Clean up PMTUD related variables + APIs, add unit tests to pmtud.rs

- quiche/src/lib.rs
This commit fixes two issues:
1. Fixes client-side PMTUD by ensuring probes are actually enabled after the handshake. The code was using `handshake_done_sent`, which is specific to the server. Credit for this fix goes to Rhett, as he discoverd this in https://github.com/cloudflare/quiche/pull/2050, but I needed to pull it in here to write tests for the second issue.
2. Ensures 1 probe per rtt by calling `set_should_probe(false)` after a probe has been sent. Previously, we would send a probe for the same size on every single iteration of quiche::send() so long as the congestion window allowed for it. This is bad for obvious reasons since it 1) wastes bandwidth and 2) blocks application data from being sent. If the flurry of initial probes results in ACKs because the PMTU is large enough, …
> Ensure 1 probe per rtt, fix client-side PMTUD, add better integration tests

- Cargo.toml
- h3i/Cargo.toml
- h3i/README.md
- h3i/examples/content_length_mismatch.rs
- h3i/src/actions/h3.rs
- h3i/src/client/async_client.rs
- h3i/src/client/connection_summary.rs
- h3i/src/client/mod.rs
- h3i/src/client/sync_client.rs
- h3i/src/frame.rs
- h3i/src/frame_parser.rs
- h3i/src/lib.rs
- h3i/src/main.rs
- h3i/src/prompts/h3/headers.rs
- h3i/src/prompts/h3/mod.rs
- h3i/src/prompts/h3/priority.rs
- h3i/src/prompts/h3/settings.rs
- h3i/src/recordreplay/qlog.rs
- tokio-quiche/src/quic/io/gso.rs
- tokio-quiche/src/quic/router/mod.rs
- tokio-quiche/src/socket/capabilities.rs
- tokio-quiche/tests/fixtures/h3i_fixtures.rs
Tests for internal services pass when using this commit
> Open source async h3i 

- tokio-quiche/src/http3/settings.rs
> Expose extended connect

- .github/workflows/nightly.yml
- .github/workflows/stable.yml
- h3i/Cargo.toml
- h3i/src/client/async_client.rs
Also enable building with both sync and async features in CI.
> h3i: fix clippy warnings for async feature

- tokio-quiche/src/http3/driver/mod.rs
When the H3Driver sends a `fin` on a stream, it calls `close()` on associated `Receiver<OutboundFrame>`. But tokio has an inconsistency between `mpsc::Receiver::try_recv()` and `mpsc::Receiver::poll_recv()` when called on a closed Receiver (not closed Sender).
* try_recv() will always return TryRecvError::Empty
* poll_recv() will always return Poll::Ready(None) (indicating the channel is closed)
This leads to a infite loop. In `process_writeable_stream()` we use `try_recv()`, see empty and put the stream into `waiting_streams`. There we call `poll_recv()`, see that the channel is closed, and call `process_writable_stream()` again.
The fix is easy: drop the Receiver instead of calling close on it. (It's already in an Option)
see https://github.com/tokio-rs/tokio/issues/7631
> tokio-quiche: fix possible infinite loop in H3Driver

- tokio-quiche/examples/async_http3_server/args.rs
- tokio-quiche/src/metrics/tokio_task.rs
> tq: remove unused imports
