src/tls.rs
Using uninhabited enums for opaque types is actually a bad idea, since compiler can rely on them being, well, uninhabited, and it's easy to run into UB.
There are various other approaches to represent them, and I chose to wrap newtype around `c_void`.
=> tls: fix opaque struct definitions

examples/client.c, include/quiche.h, src/ffi.rs
There were transport parameters that were not able to be set :(
This fixes that
=> ffi: export setter functions for config params

examples/client.c, examples/client.rs, examples/server.c, examples/server.rs, include/quiche.h, src/ffi.rs, src/lib.rs, src/stream.rs
The buffer is provided from 'c' as a pointer to an array of uint8_t and
a length thereof.
In addition, from 'c', a reference to a bool is provided so that the fin
status of the read can be returned to the caller.
The return value for the 'c' function is the number of bytes written
into the provided buffer.
The rust interface is similar, in that it also provides a buffer, in
the form of a mutable slice of 'u8' type.  The slice self reports its
own size.
The number of bytes written to the slice, and the fin status of the
read is returned as a tuple.
The important fix is in the RecvBuf class, where the pop method now
takes a slice as a parameter and copies queued pages of data into the
slice.
The existing RangeBuf interface is removed from RecvBuf::pop and
Stream::recv_pop and as a result, …
=> stream: stream_recv writes data to a provided buffer

src/lib.rs, src/packet.rs
As far as I can tell, these are actually the same constant and are supposed to always stay in sync.
=> Reuse constant

.travis.yml
This allows to avoid rebuilding all deps on each CI run, thus significantly speeding up compilations.
=> Add Cargo cache to Travis

.travis.yml
This seems to be breaking PR builds due to having "branch" and "pull request"
builds which reuse the same build artifacts, which in turn confuses the C
examples Makefile and cause the C examples to fail to build.
See e.g. https://github.com/cloudflare/quiche/pull/20/checks?check_run_id=59225473
This is really the Makefile's fault for being too stupid, but until I can
figure out how to fix it (e.g. make cargo build C examples?), it's just
easier to disable the build cache.
This reverts commit 5ddb63a879067702c4fac749adc96674cb61dc39.
=> Revert "add Cargo cache to Travis"

examples/http3-client.rs, examples/http3-server.rs, include/quiche.h, src/ffi.rs, src/h3/frame.rs, src/h3/mod.rs, src/h3/stream.rs, src/lib.rs
This fixes the bug that we were rejecting unknown frame types.
In order to make this more testable in the future, I added a new utility function in the library to send two stream types (the first two in the reserved range); one has a 0-length payload, the second has some 'random' bytes. These frames are sent at the start of request or response streams conditionally, that boolean is passed new parameter to `send_request` or `send_response`. This kind sucks and it means the ffi has to change. A different approach would be to set a HTTP/3 config option and then check that within the functions. I've left it as is for now to discuss.
I added the `--grease` command line argument to rust examples. We should discuss if this should be more fine grain i.e. controlling grease of transport and …
=> h3: Add support for GREASE frames

src/h3/mod.rs, src/h3/stream.rs
The main thrust of this change is to add more checks to frame parsing. This includes detecting if it is sent to an invalid peer, on an invalid stream, at the wrong time on a stream and so on.
Most of this happens in `poll()` when it parses each frame. When first writing this block, I created some helper functions but when adding more checks in this change I found that those functions reduced the readability of the code. So now we just have a simple pattern of
* For a given frame type
* Test a validity condition
* If fail
* send a CONNECTION_CLOSE with the most suitable error code
* Return error
* otherwise do whatever needs doing with the frame (either generate an event, set some internal state, or nothing)
=> Strict frame checking

src/h3/mod.rs
This can be useful e.g. to add HTTP/3 benchmarks.
=> h3: move Session into dedicated module and make public

src/h3/mod.rs, src/h3/stream.rs
Make sure we are robust when a client sends PRIORITY frames on request or control streams, even though we don't handle them for now.
=> h3: add PRIORITY frame tests

benches/benches.rs, examples/http3-client.c, examples/http3-client.rs, examples/http3-server.rs, include/quiche.h, src/h3/ffi.rs, src/h3/mod.rs, src/h3/stream.rs
This adds a new recv_body() method to the HTTP/3 connection, that can
be used by the application to retrieve request/response data from the
transport stream. The application can thus decide when and how much
data to read.
The Data event is changed to only be a signal that some data is
available, instead of returning the data itself. The Data event is now
level-triggered, meaning it will keep firing until the application has
read all of the data. This means that the application has no way of
discarding stream data currently. In the future we will need to add
support for STOP_SENDING if we need this functionality.
Internally, a new stream state is added which only sets a stream flag
indicating that the specific stream can be read. This flag triggers the
Data event itself, which is only …
=> h3: body recv API

examples/client.rs, examples/http3-client.rs, examples/http3-server.rs, examples/server.rs
fixes #56
All Rust examples changed to handle the result of socket.send[_to](). Tested local and remote interop of http3-client.
=> examples: handle socket.send() result

examples/http3-client.rs
This adds support for setting a custom HTTP method in http3-client and send request body.
It's not a whole lot of additional complexity IMO so adding this here shouldn't be too bad, though lsquic-client also supports this (and maybe h2load?), so I'm fine to leave this out as well.
=> Add support for sending POST (and other methods) requests with body to http3-client

examples/Dockerfile, examples/README.md
Adds a Dockerfile that works in 2 stages:
1) creates a build image from official Rust sources, installs build prereqs and does a release build of examples with cargo
2) creates a distribution image, ensures system root store is up to date and copies just the binaries from stage 1.
Updated readme.md to show how to use this thing.
=> examples: add Dockerfile

README.md, src/build.rs
Note that this patch requires #70.
With MacOS X and xcode tools installed,
```
cargo lipo
```
or
```
cargo lipo --release
```
will build libquiche.a
=> iOS Build Support

include/quiche.h, src/ffi.rs, src/h3/mod.rs, src/lib.rs, src/stream.rs
This allows applications to discard incoming or outgoing stream data. For
example an application might want to ignore incoming HTTP request data
in case of errors. Without this, the application would have to consume
all the incoming data in the stream manually, otherwise the HTTP/3 layer
would keep reporting "Data" events forever.
Currently that's all this API does currently, but in the future it can
be used to trigger sending STOP_SENDING and RESET_STREAM frames for
specific streams.
=> add stream_shutdown() API

examples/http3-client.rs
Adding -H/--header "field: value" option to http3-client
to add request headers in the command line. Can be multiple.
Useful when you need more http-related tests.
Currently it can't override default headers (e.g. user-agent).
If you add, there will be 2 headers with same name.
e.g.
```
http3-client -H 'cache-control: no-cache' https://cloudflare-quic.com
http3-client -H 'content-type: application/x-www-form-urlencoded' --method PUT --body test.dat https://httpbin-like...
```
=> http3-client: add request headers

CODEOWNERS
This adds the whole team as default reviewers for PRs to the quiche repository. Thoughts?
=> CODEOWNERS: add whole team

README.md, tools/build_android.sh, tools/setup_android.sh
It was missing in android build.
=> Add arm-linux-androideabi target

examples/http3-client.rs
Due to fat fingers I stumbled across an unhelpful error message when I forgot to include a `:` in a header name. So this PR adds some very basic error checking and panics with the value of the bad header.
=> http3-client: panic on custom header error

examples/http3-client.rs
Adds a new CLI option `-n`,`--requests` that allows the client to send multiple identical requests at the same time. Default is 1.
```
http3-client -n3 https://cloudflare-quic.com
```
The PR is is a lowest impact way to add this feature. The downsides are: only record and report timing of all requests, request bodies printed to stdout will get horribly intermingled.
=> http3-client: send multiple identical requests

Cargo.toml, src/tls.rs
Rough first stab at this, PTAL. Fixes #61 .
Since this problem and its solution are windows specific, there is liberal peppering of `#[cfg(windows)]`.  I'm keen to see if this actually works as it appears on paper.
Happy to hear more elegant ways to do this. Tidy up code is not great, windows API example code is a bit rubbish.
=> tls: load certs from Windows system store

src/lib.rs, src/stream.rs
This also fixes setting initial flow control limits for unidirectional
streams.
=> stream: refactor stream flow control initialization

src/h3/mod.rs
Before this change, *any* data received on a QPACK encoder/decoder stream
would trigger a conn_close with encoder/decoder error type, which could
be the wrong thing to do in some cases. This change allows data on the
streams but since we don't support QPACK dynamic table yet, we simply
put the stream into a draining state and ignore instructions.
With this change in place we can properly detect stream closure, so I
took the chance to update the relevant test.
=> h3: don't error on QPACK instruction

include/quiche.h
@ghedo I missed this one too, which causes problems for C-based servers :(
=> ffi: update QUICHE_MAX_CONN_ID_LEN

examples/Makefile
Use `-lquiche` instead of `-l:libquiche.a` to build.
=> Update makefile to fix build error

examples/http3-server.rs
this seems to fix the problem, alignment/formatting sucks.
=> examples: shutdown client request streams after reading headers

examples/client.c, examples/http3-client.c
The type of `stats.sent` etc is `size_t` not `uint64_t`. We should use `%zu` to print them.
=> Fix size_t printf type error.

examples/client.c, examples/http3-client.c, examples/http3-server.c, examples/server.c
For `ssize_t` type, use `%zd` in C example. It will remove compile warning/error.
Test in the following platforms:
- cc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516 (x86-64)
- cc (Debian 8.3.0-6) 8.3.0 (x86)
- Apple LLVM version 10.0.1 (clang-1001.0.46.4) Target: x86_64-apple-darwin18.6.0
=> Fix ssize_t fmt in C examples

src/frame.rs, src/lib.rs, src/packet.rs, src/stream.rs
Current quiche master is not working at 32bit OS.
Here is a simple test result in x86 Debian:
```
% uname
Linux buster32 4.19.0-5-686-pae #1 SMP Debian 4.19.37-5+deb10u1 (2019-07-19) i686 GNU/Linux
```
`cargo build` runs successfully, however `cargo test` fails:
```
test result: FAILED. 129 passed; 46 failed; 0 ignored; 0 measured; 0 filtered out
```
Also `http3-client` fails at runtime
```
$ target/debug/examples/http3-client https://cloudflare-quic.com
thread 'main' panicked at 'attempt to multiply with overflow', /usr/src/rustc-1.34.2/src/libcore/num/mod.rs:3516:24
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```
In above case, main issue is in `src/frame.rs:863`, where `2usize.pow(62)` overflows in 32bit platform (`usize` is 32bit in 32bit OS). …
=> 32bit architecture support

Cargo.toml, src/crypto.rs
Both HKDF and AEAD APIs changed quite significantly, unfortunately not
always for the better (see e.g. the hack to make the HKDF expand()
function accept an arbitrary length, or the fact that we now need to
manually append the AEAD tag to a sealed message).
=> crypto: update to ring 0.16

Cargo.toml, src/build.rs
This replaces the non-default `no_bssl` feature with a default `boringssl-vendored` one (so the logic is inverted: no_bssl disables building bssl when enabled, but boringssl-vendored _enables_ building bssl when enabled). This makes more sense to me, as we build for BoringSSL even with `no_bssl`, it's just that we don't build BoringSSL itself.
This also contains a bunch of other minor build tweaks.
=> Misc. build improvements

examples/client.c, examples/client.rs, examples/server.c, examples/server.rs, include/quiche.h, src/ffi.rs, src/h3/mod.rs, src/lib.rs, src/stream.rs
All users of Readable also do a collect() (otherwise they wouldn't be
able to reference the Connection while iterating), so we might as well
do it directly in the API, so we can simplify some code.
This also restores how the Readable iterator is accessed from FFI, to
before commit 67ee5f3b5dff7745abae130e8215ec7e977a5d10. The side effect
of that commit was that a user couldn't ignore a readable stream, and
every call to quiche_readable_next() would keep returning the same
stream. The new API makes it more consistent with Rust.
=> stream: simplify the Readable iterator

Cargo.toml, src/build.rs
This is a bit of a hack, but cargo doesn't exactly make this easy.
This can be used to build exernal projects that use libquiche.{a,so}
(e.g. curl) without having to hard-code paths.
To enable it, pass "--features pkg-config-meta" to cargo build.
=> build: add feature to generate pkg-config metadata file at build time

include/quiche.h, src/ffi.rs, src/lib.rs, src/stream.rs
This implements an iterator for writable streams, that is, streams that
have enough flow control capacity to be written to.
This can be used by applications to resume sending on streams that were
previously blocked by flow control.
---
This also renames the previous uses of "writable" to "flushable" to avoid confusion.
TODO:
=> stream: implement Writable iterator

examples/client.c, examples/server.c, include/quiche.h, src/ffi.rs, src/lib.rs, src/stream.rs
As @nqv pointed out in https://github.com/cloudflare/quiche/pull/124#issuecomment-522730990
they are basically the same structure, so there's no need to duplicate
them.
=> stream: merge Readable and Writable into StreamIter

examples/http3-server.rs, examples/server.rs, include/quiche.h, src/ffi.rs, src/h3/mod.rs, src/lib.rs, src/stream.rs
In order to avoid buffering an infinite amount of data in the stream's
send buffer, we now only allow streams to buffer outgoing data up to the
amount that the peer allows us to send.
This also adds a new Connection method, stream_capacity() which can be
used by applications to know how much data they can write in advance.
This is required by the HTTP/3 code that needs to know the size of body
it can write in advance in order to set a proper size in the DATA frame
header. Without stream_capacity(), send_body() could potentially write
an incomplete DATA frame in the stream send buffer which would be
complicated to recover from.
---
TODO:
=> limit stream send buffer size

include/quiche.h, src/ffi.rs
This is just so applications don't have to do this manually.
=> ffi: add function to get timeout in milliseconds

examples/http3-server.rs, examples/server.rs
This fixes a potential crash if the client sends a DCID of different
size than what we expect.
=> examples: validate the destination CID after retry

src/lib.rs, src/stream.rs
Instead of iterating over all streams when deciding which streams are
writable, keep track of writable streams separately.
=> stream: optimize writable iterator

tools/http3_test/src/runner.rs, tools/http3_test/tests/httpbin_tests.rs
Small change to `runner.rs` to allow it agility in what server it actually targets for tests. It decouples the server SNI (used by QUIC) from the IP and port used by UDP socket. 
The httpbin_tests.rs are updated with a new environment variable `HTTPBIN_HOST` to make this easy to use from a testing environment.
=> tools: allow test runner to target different test server

src/h3/mod.rs
The H3 code naively sends 2 GREASE frames every time HEADERS are sent. This is a bit of a waste because if the peer doesn't handle GREASE, it is likely to bomb out in the first instance. The savings are marginal but there seems little benefit in sending more than one set of GREASE frames.
Maths for H3-level savings:
1 GREASE frame with no payload = 8 bytes (worst case varint)
1 GREASE frame with "GREASE is the word" payload = 8 + 18 bytes (worst case varint)
Total: 34 bytes per HEADERS.
=> h3: only send GREASE frames once per connection

examples/Makefile
The glob pattern is not cross platform. At least not working in my Macbook. See [Stackoverflow question](https://stackoverflow.com/questions/4036191/sources-from-subdirectories-in-makefile).
Change it to `find` fix the problem.
=> Use find instead of glob pattern

examples/http3-client.c
In C http3-client example, when we create a h3 request hostname
is hard coded (quich.tech). Pass hostname to h3 authority field.
=> http3-client C example: Pass hostname to h3 request

tools/http3_test/src/runner.rs
Previously, the runner would appear to complete successfully if the
idle timeout triggered without all requests completing. Test
assertions are only done once all requests are complete so, if the
idle timeout is hit before then, just panic.
The downside of this is that it may reveal problems that were previously masked, but in the long term this is a good thing.
Finally, the idle timeout is quite generous in order to support the example httpbin integration test suite. We should probably parameterize it but I figure we can do that in a separate PR.
=> tools: http3_test detect client idle timeout

tools/http3_test/src/runner.rs, tools/http3_test/tests/httpbin_tests.rs
Adds a timeout parameter to `runner.rs` and a env var to httpbin_tests that exercises it.
=> http3_tests: make idle timeout configurable in runner

src/h3/frame.rs, src/h3/mod.rs, src/h3/stream.rs
Remove PRIORITY frame and tests. 
Update error codes, which leaves some holes in our internal enum. This also lets us address some existing TODOs, and I fixed a minor case of using the incorrect error code on the control stream.
=> h3: update to draft 23

src/lib.rs
We try to ignore invalid incoming packets (e.g. ones that fail
decryption) to prevent an attacker from causing the connection to be
closed by injecting invalid packets (this is unlike TCP, where e.g. RST
packets can be injected due to lack of encryption).
However currently this is not applied consistently, and there are
several cases where invalid and unauthenticated packets would cause the
connection to fail.
In addition, one problem with this design is represented by the fact
that packets that look like Initial packets but are in fact not QUIC
packets at all, could be received and trick the server into allocating
connection state.
This is unavoidable as to process Initial packets connection state is
required. However if no other valid packet is received, the connection
will never be …
=> reject undecryptable packets

src/lib.rs, src/recovery.rs
This is somewhat of an optimization to help reject obviously invalid ACK
frames. In order to do this we track the largest packet number that has
been sent, and compare if against the largest ACK packet from ACK
frames.
The spec says:
>  An endpoint SHOULD treat receipt of an acknowledgment for a packet it
>  did not send as a connection error of type PROTOCOL_VIOLATION
So we are free to close the connection as well.
=> recovery: reject ACK frames that have a largest ACKed that is too large

README.md, src/recovery.rs, tools/quic-trace-log/src/main.rs
Instead of doing weird hacks in `recovery` we can just do operations between `Duration` and floats directly, so the code is slightly easier to understand and we can follow the recovery draft more closely.
=> duration_float is now a stable feature, so use it

src/h3/mod.rs, src/h3/qpack/mod.rs, src/lib.rs, src/octets.rs
This method is deprecated https://doc.rust-lang.org/std/error/trait.Error.html#method.description
We already implement Display for the error types, so this is not needed.
=> remove implementations of Error::description() method

benches/benches.rs, examples/http3-client.c, examples/http3-client.rs, examples/http3-server.c, examples/http3-server.rs, include/quiche.h, src/h3/ffi.rs, src/h3/frame.rs, src/h3/mod.rs, src/h3/stream.rs, tools/http3_test/src/lib.rs, tools/http3_test/src/runner.rs
HTTP/3 draft-23 removed prioritization. This change
removes the "num placeholders" settings which
means that we slightly modify the public API for HTTP/3
config: `h3::Config::new()` and `quiche_h3_config_new()`
by removing that parameter.
Placeholders were a server-advertised feature, so this
change has the nice effect of making the API more sane
for clients.
=> h3: refactor Config API and remove priority placeholder setting

include/quiche.h
Without it, I get this:
~~~
include/quiche.h:305:1: error: function declaration isn’t a prototype [-Werror=strict-prototypes]
305 | quiche_h3_config *quiche_h3_config_new();
| ^~~~~~~~~~~~~~~~
=> quiche.h: use (void) in proto to satisfy picky compilers

.travis.yml, tools/quic-trace-log/src/main.rs
Now that quic-trace-log can be built with Rust stable we should test
build in CI.
=> travis: build quic-trace-log as well

src/lib.rs, src/tls.rs
This simplifies the code a bit since the `tls::Error` type is not used much anyway.
=> tls: use crate::Error instead of custom error type

src/h3/mod.rs
This can be useful for debugging.
=>  h3: expose the underlying transport error via Error::TransportError

include/quiche.h, src/ffi.rs
Previously, multiple calls to `quiche_enable_debug_logging()` would
cause a Rust panic, requiring applications to implement their
own housekeeping to avoid the problem. With this change we
manage things more gracefully, returning 0 on success of or -1
if there was some problem.
=> ffi: avoid panic on multiple quiche_enable_debug_logging

examples/http3-server.rs, examples/server.rs, src/h3/mod.rs, src/lib.rs, src/stream.rs
This implements increasing the local max streams limits by sending
MAX_STREAMS frames, once a certain threshold is passed.
Stream credits are given back to the peer only once a non-locally
generated stream is complete, that is, once all incoming data has been
read by the application and all outgoing data has been ACKed.
---
TODO
=> increase local max streams limits with MAX_STREAMS 

examples/http3-client.rs, src/lib.rs, src/stream.rs
Before this change we would decrease the maximum stream limit every time
we attempt creating a new local stream, without tracking how many
streams we actually opened.
This would work if the remote stream limits were static, however the
peer can send a MAX_STREAMS frame (which carries absolute values, rather
than incremental updates) which would cause us to reset the limits to
the maximum value. We would then attempt to create new streams without
keeping into consideration streams that were already opened.
This change adds counters for the local streams that were actually
opened (like we already did for remote ones in df75104), so that we can
simply compare that against the max limits.
---
While working on #164 I thought I'd implement support for retrying HTTP/3 requests when stream limits …
=>  stream: fix handling of remote max streams limit updates

src/lib.rs
We already "use std::time" is lib.rs, so we can shorten a few function
and type names. No functional changes, just cosmetic.
=> use time:: instead of std::time::

src/lib.rs
Follows QUIC transport Idle Timeout section:
```
idle_timeout = max ( tp.idle_timeout, 3 * probe_timeout )
```
get_idle_timeout() function added.
=> Idle timeout calculation update

.travis.yml
This adds basic CI builds for macOS and Windows (only Rust stable, and only build+test of quiche itself), as well as removes the Rust beta builds which weren't particularly useful.
=> travis: add more operating systems and remove beta

src/h3/mod.rs, src/lib.rs
In e739f55 we started rejecting all undecryptable packets because the
logic to simply ignore invalid packets was incomplete, so that was a
simplification.
However we do actually need this, even in legitimate connections,
because Firefox sends "padded" Initial packets (i.e. UDP packet with
Initial and a bunch of zero bytes appended), and we would close the
connection.
We do still need to close the connection if the first packet is broken,
in order to avoid keeping a connection alive when some junk that looks
like Initial is received and no other data is received afterwards, so
the logic is updated to check for the number of packet already processed
before deciding whether to send Error::Done (i.e. ignore packet) or some
other error which would cause the connection to be closed.
We already …
=> drop packets that fail decryption again

.gitignore, .travis.yml, Cargo.toml
For internal testing, using `exclude` will cause a lot of
directory traversing when running `cargo test`, slow down
test run a much (adding a minutes) when there is a lot of
files to scan and where file system operation is slow, such
as MacOS + Docker environment.
Using `include` will prevent this from happening.
=> Use include instead of exclude

.travis.yml, extras/nginx/README.md, extras/nginx/nginx-1.16.patch
This adds the integration of quiche with NGINX as a stand-alone patch.
Instructions for building and configuring NGINX with quiche support are
also provided, as well as documentation for contiguration directives.
=> extras: add NGINX integration

src/h3/mod.rs, src/rand.rs
We've had many compliments during interop testing on our use of **very large values** when sending greasy things. The generation of these values is "uniform random" but the frequency of these compliments made me suspicious. I knocked together a quick dummy program to test things over 100000 iterations:
```
grease_value() on master
0.00020000020000019998'th percentile of data is 2251799813685247 with 2 samples
0.0005000005000005'th percentile of data is 4503599627370495 with 3 samples
0.001000001000001'th percentile of data is 9007199254740991 with 5 samples
0.0024000024000024'th percentile of data is 18014398509481983 with 14 samples
0.0051000051000051'th percentile of data is 36028797018963967 with 27 samples
0.011700011700011701'th percentile of data is 72057594037927935 with 66 samples …
```
=> h3: make GREASE numbers more uniform

.travis.yml, src/build.rs
Add android target, build 4 platforms. Since android
language support doesn't include rust and cmake version is too
old, install it separately.
=> Add Android build to CI

extras/nginx/README.md
auto/configure seems to be for git cloned nginx repo builds ? for source tarball ./configure would be the correct one to use
=> update nginx HTTP/3 instructions

examples/http3-server.rs, examples/server.rs, include/quiche.h, src/crypto.rs, src/ffi.rs, src/frame.rs, src/lib.rs, src/packet.rs, src/tls.rs
This adds initial support for enabling early data and processing 0-RTT
packets. In practice this only works on the server-side, as there is no
support for actually writing early data (or for the client to resume a
connection to beging with).
It *looks* like sending 0.5-RTT data from the server works as well.
=> initial support for receiving 0-RTT packets

src/lib.rs, src/stream.rs
Make sure to flush STREAM frames with fin=true even if the stream has
otherwise no data to send. This requires marking the stream as
flushable when the application calls Connection::stream_send() with an
empty buffer, but fin=true.
In addition, on reception of empty STREAM frames with fin=true, make
sure that the stream is marked as readable, so the application can
receive the end of the stream.
---
TODO:
@LPardue this is pretty hacky, but it should fix the immediate problem. Can you check if you can still reproduce the problem you are seeing with this applied on both the client and tbe server?
=> Send (and receive) zero length STREAM frames with fin=true

src/lib.rs, src/packet.rs
This removes an `unwrap()` call in `packet.rs`. In addition a slight optimization is added, to avoid trying to generate packets if it's obvious that will fail later.
In practice removing the `unwrap()` is not needed if the other check is present, but fixing it anyway doesn't hurt.
=> Remove one unwrap() call

benches/benches.rs, examples/http3-client.rs, examples/http3-server.rs, extras/nginx/nginx-1.16.patch, include/quiche.h, src/h3/ffi.rs, src/h3/mod.rs, tools/http3_test/src/lib.rs, tools/http3_test/src/runner.rs
~~Previously, when `quiche::h3::Connection::poll()`
returned a `Headers` or `Data` event, there was
no way to tell if that event simultaneously closed
the indicated stream. Instead, `poll()` would need
to be called until the `Finished` event occurred.~~
~~With this change a boolean `fin` flag is returned
with the Event, which allows for some more
optimised work flows.~~
~~This changes the poll API and so has ripple effects. I chose to refactor `http3-client.rs` to act on the fin flag in every event handler. While for http3_test/runner.rs I chose to just ignore the flag and continue with the existing `Finished` event.~~
~~Implementing the feature the way I have reveals two things: 1) it's not possible to receive a a Data event with fin=true (because the stream has data on it that the app …
=> h3: add has_body flag to HTTP/3 Header Event

src/lib.rs
This is actually a false positive, as the structs are only exposed to
FFI as pointers, so they are effectively opaque from the non-Rust
perspective
The warning showed up in nightly after the following PR was merged:
https://github.com/rust-lang/rust/pull/65134
=> silence improper_ctypes warning

include/quiche.h, src/h3/mod.rs
Make it clear that applications are responsible for validating HTTP/3 pseudo-headers and headers, to help avoid issues such as https://github.com/cloudflare/quiche/issues/248
The nginx patch included in this repo has an [example](https://github.com/cloudflare/quiche/blob/a27c2b898beae734c771bcc50803737540d288f3/extras/nginx/nginx-1.16.patch#L1728) of the sort of checks that should be done.
=> h3: document that app should validate headers

src/lib.rs
There's no point is sending ACK or PING frames as the connection is
going to be closed anyway.
=> don't try to send ACKs or PINGs when closing

README.md, examples/http3-server.rs, examples/server.rs, src/ffi.rs, src/lib.rs
Due to the fact that we store a pointer to the Connection object inside
its own Handshake context, Connection objects cannot be moved (which is
why we return a boxed object from its constructor). Using Pin on it
makes the compiler enforce this.
Fixes #45.
---
Note this requires Rust 1.39.
=> pin Connection

examples/client.c, examples/client.rs, examples/http3-server.rs, examples/server.c, examples/server.rs, include/quiche.h, src/ffi.rs, src/frame.rs, src/h3/mod.rs, src/lib.rs, src/packet.rs, src/tls.rs
This adds initial support for draft-24, while still retaining draft-23
support. In practice they are basically the same protocol, so the only
change is supporting multiple versions on the server and doing some kind
of version negotiation.
This also allows PING frames in non-1-RTT packets (technically it should
be draft-24-only, but it doesn't really matter).
=> support draft-24 alongside draft-23

src/lib.rs, src/stream.rs
Even if we only decrypt the packets but not process the frames they
carry, there is still some risk for side effects (see e.g.
a0e69eda9da97ebb03ccda38f4bb58cfea572163).
In the future we may want to buffer received packets so we can later
process them as an optimization.
---
Forgot to create this during the hackathon...
=> discard 1-RTT packets received before handshake completion

fuzz/Cargo.toml, fuzz/Dockerfile, fuzz/src/qpack_decode.rs
This pull request suggests adding two fuzz targets and improving an existing one:
- `qpack_decode`: The target now checks that `decode(encode(hdrs)) == hdrs` while not panicking instead of just checking `decode(input)` doesn't panic. 
- `qpack_huffman_rt` (NEW): Fuzzer for the QPACK huffman codec. Checks that `decode(encode(input)) == input` while not raising a panic.
- `h3_frame_rt` (NEW): Fuzzer for h3::frame (de)serialization. Checks that `deserialize(serialize(frame)) == frame` while not raising a panic.
As an aside, all of those fuzzers define a buffer to store the encoded (or serialized) data. Those buffers have to be bigger than the original `data` array given by libfuzzer. This is necessary because libfuzzer sometimes find a smaller representation than what the encoder would …
=> Additional Fuzz Targets & Fuzzing improvements

src/lib.rs, src/recovery.rs, src/stream.rs
Only use upper-case "ACK" to refer to the frames.
=> spell 'acked' consistently

src/lib.rs, src/stream.rs
Currently, when sending stream data, we don't fill the entire output packet buffer due to a couple of accounting discrepancies. While this is only by a handful of bytes, so performance is not really affected, this potentially complicates applications that can's assume a whole buffer is filled. This is particularly annoying when dealing with UDP GSO.
=> Try to fill the whole packet buffer

src/recovery.rs
This is a slight optimization to avoid BTreeMap lookups when a packet is
clearly not newly acked.
=> recovery: slightly optimize detection of duplicate acks

src/build.rs
Seems like when you build dylib in MacOS it will try to find
all symbols defined by default, resulting cdylib link failing due to
missing boringssl library. Add a linker option to allow building
dylib without finding undefined symbols.
Ref: https://glandium.org/blog/?p=2764
Fixes #238
=> MacOS: fix cdylib build with --no-default-features

include/quiche.h, src/ffi.rs, src/lib.rs, src/stream.rs
This allows applications to store stream-specific data inside quiche, so
as to avoid having to track streams by themselves.
One potential use-case was storing internal HTTP/3 stream state, so we
wouldn't need to keep separate streams maps for both transport and
HTTP/3 however the current structure of the HTTP/3 implementation does
not allow for this (due to cross-references that make borrow checker
sad). Though this can be useful for other applications.
Fixes #112.
=> stream application data API

.travis.yml, src/build.rs
Pass 32bit toolchain to cmake for cross-building x86 linux from
x86_64 linux. Also CI target is added.
Ref: https://github.com/google/boringssl/blob/master/BUILDING.md
Fixes #277
=> Fix 32bit x86 build

tools/http3_test/README.md, tools/http3_test/tests/httpbin_tests.rs
Since we'll be adding some more environment variables (cc @schien) I figured we probably want to document their intended purpose and the expected format.
=> tools: add some more documentation of http3_test env vars

tools/http3_test/README.md, tools/http3_test/tests/httpbin_tests.rs
introduce two environment variables for customizing "headers" test case
`EXTRA_HEADERS` for adding additional request headers in JSON format.
`EXPECT_REQ_HEADERS` for request header validation in JSON format.
Headers with null value represents non-existence in the forwarded request headers.
=> extend httpbin tests

.travis.yml, src/build.rs
When building on windows/x86, a custom CMAKE_TOOLCHAIN_FILE
is not needed. Also split windows CI into x86_64 and x86 to make sure it works.
Fixes #293
=> Fix windows/x86 build

tools/http3_test/src/lib.rs
This will fix today's Travis failure.
```
note: this value is dropped without further use
--> src/lib.rs:277:31
|
277 |             expect_resp_hdrs: expect_resp_hdrs.clone(),
|                               ^^^^^^^^^^^^^^^^
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#redundant_clone
```
=> Fix "error: redundant clone"

.travis.yml
Apparently we need to explicitly install the target now.
=> travis: fix Windows x86_64 build

extras/docker/qns/run_endpoint.sh
The transfer test is also used to get the goodput measurement, so the
trace logs might affect performance. Unfortunately there is no way to
only disable the logs for the measurement, and they need to be disabled
for the whole test.
=> qns: disable trace logs for transfer test

.travis.yml
Currently the "stable Linux" build is the one that takes the most time
to complete, which means that the entire build will have to wait for
that to complete.
By splitting NGINX into its own build we lower the time of the "stable
Linux" build. While this goes over the 5 concurrent builds limit, the
"stable Android" is very short, which means we might be able to complete
both that one and the NGINX one before "stable Linux" (or around the
same time).
=> travis: split NGINX into its own build

examples/client.rs, examples/http3-client.rs, examples/http3-server.c, examples/http3-server.rs, examples/server.c, examples/server.rs, include/quiche.h, src/cc/mod.rs, src/cc/reno.rs, src/ffi.rs, src/lib.rs, src/recovery.rs
Configurable Congestion Control
The purpose of this mega patch is to make congestion control
configurable. Also it's extensive so that we can add more congestion
module later and make it easier to switch between different CC
algorithms using config API.
New Modules
-----------
`cc/` directory is created.
- `cc/mod.rs` contains basic CC constants such as
INITIAL_WINDOW. Also it defines CongestonControlTrait which has
method of CC related functions and hooks.
- new_congestion_control(name) is a factory method to return
a new CC module based on its name.
- `cc/reno.rs` implements `Reno` CC algotirhm, following
QUIC recovery draft 24 based.
Currently besides of basic method, you need to implement
the following CC-specific hooks called from the stack:
- on_packet_sent_cc()
- …
=> recovery: configurable congestion control

.travis.yml
The `cargo build` for the stable build was accidentally removed in
15d04c3, however since we already do `cargo package` anyway, this is
probably superfluous, so remove it from nightly build as well.
=> travis: don't do superfluous 'cargo build'

extras/docker/qns/run_endpoint.sh
multiconnect test requires:
The client is expected to establish a separate connection for each of the files requested in the $REQUESTS parameter. The connections may be established serially or in parallel. 
This is exactly how we are doing right now, so adding test name will be good enough.
=> extra: add multiconnect test for quic-interop-runner

.travis.yml, Cargo.toml, README.md, src/build.rs, tools/build_android_ndk19.sh, tools/setup_android.sh
- Update build.rs to support recent NDK (19 or later) build instruction.
- You can still get previous NDK style support using `--features ndk-old-gcc`.
- build_android_ndk19.sh is an example script to build using NDK >= 19.
- travis: android build will try both way.
- Update README
This PR will fix #300 and #325
=> Android NDK support improvement

tools/qlog/README.md
This is breaking the rendering of the README on crates.io :)
=> fix markdown in qlog README

src/cc/mod.rs, src/cc/reno.rs, src/recovery.rs
IsAppLimited() can be defined by bytes_in_flght < cwnd.
Let's consider the following scenario.
```
(initcwnd=3000)
Send pkt #0 size  500 -> bytes_in_flight =  500 cwnd=3000
Recv ack #0           -> bytes_in_flight =    0 cwnd=3000
Send pkt #1 size 1000 -> bytes_in_flight = 1000 cwnd=3000
Send pkt #2 size 1000 -> bytes_in_flight = 2000 cwnd=3000
Send pkt #3 size 1000 -> bytes_in_flight = 3000 cwnd=3000
Recv ack #1           -> bytes_in_flight = 2000 cwnd=4000 (slow start)
Send pkt #4 size 1000 -> bytes_in_flight = 3000 cwnd=4000
Send pkt #5 size 1000 -> bytes_in_flight = 4000 cwnd=4000
```
Currently is_app_limited() returns always false,
We are actually doing like this:
```
Send pkt #0 size  500 -> bytes_in_flight =  500 cwnd=3000
Recv ack #0           -> bytes_in_flight =    0 cwnd=3500 …
```
=> recovery: implement IsAppLimited()

src/lib.rs, src/tls.rs
=> tls: expose peer certificate

src/build.rs
Fix the following recent CI warning:
```
error: unneeded return statement
--> src/build.rs:78:5
error: useless use of `format!`
--> src/build.rs:63:16
error: `if _ { .. } else { .. }` is an expression
--> src/build.rs:80:13
```
=> build: make clippy happy

src/lib.rs
When we do version negotiation, try to choose highest version
supported, not the first seen version supported from a list of
versions from the peer.
e.g. litespeed send the version list like this:
versions=[51303433, 51303436, 51303530, ff000018, ff000019]
Currently we pick up h3-24 (ff000018), but better to pick up
h3-25 (ff000019) in the last.
=> Choose highest version supported

examples/http3-server.rs, examples/server.rs
When we receive a ClientHello split across multiple Initial packets we
end up creating multiple connections in the example servers due to the
fact that we only store the server-generated destination connection ID,
and not the original client-generated destination connection ID, in the
HashMap used to associate incoming packets to connections.
This changes how we generate the server-generated destination connection
ID by making it more deterministic and based on the client-generated
connection ID, and then do a double lookup for both the raw dcid and the
deterministically-generated one.
Unfortunately due to the fact that we use the normal Rust HashMap we
can't have multiple keys pointing to the same connection, so we can't
store the client-generated connection ID directly. In practice we …
=> examples: deterministically generate source conn ID on servers

src/lib.rs, src/tls.rs
In some cases (e.g. 0-RTT) BoringSSL will report the handshake as
completed by returning "1" from SSL_do_handshake(), even if the
handshake is not in fact complete.
So use "SSL_in_init()" to check for handshake completion.
=> tls: use SSL_in_init() to check for handshake completion

src/lib.rs, src/stream.rs
Due to the fact that we have already dropped the state of the stream, we
cannot know whether the frame is valid or not. Before we would assume
that this is an error, but in some cases (e.g. spurious retransmissions
due to loss of ACK frames) it's possible to receive a valid frame on a
dropped stream.
Fixes #350.
=> ignore frames on closed and collected streams

Cargo.toml
This is a bit of a hack as it requires setting `--features bench` when
invoking `cargo bench`, but it allows us to avoid pulling in criterion
when building tests and examples, which reduces the number of
dependencies for those build in half.
=> Cargo: only depend on criterion when building benchmarks

Cargo.toml, examples/client.rs, examples/http3-client.rs, examples/http3-server.rs, examples/qpack-decode.rs, examples/qpack-encode.rs, examples/server.rs, src/cc/reno.rs
Mostly this allows us to drop some "expensive" (as in, slow to build) dependencies.
Along with https://github.com/cloudflare/quiche/pull/352 this cuts the time required to run `cargo test` on my laptop in half.
Before:
```
% time cargo test
cargo test  400.72s user 29.41s system 584% cpu 1:13.54 total
```
After:
```
% time cargo test
cargo test  177.36s user 18.62s system 516% cpu 37.933 total
```
=> Simplify examples

tools/apps/src/bin/quiche-server.rs, tools/apps/src/lib.rs
A requests ending in "/" will instead be processed as "/<index>", where
index is a file pass via the --index argument (by default "index.html").
This way we won't serve 404 for "/" requests (e.g. from browsers).
=> apps: process requests ending with '/'

src/frame.rs
Erm, somehow we missed this. The RESET_STREAM error code changed from 16 bits to varint in **draft 21**.
=> lib: RESET_STREAM frame error code is a varint

src/lib.rs
When fuzzing it's useful to coalesce mutliple QUIC packets to increase
the coverage, but there can only be only one 1-RTT packet. By stashing
multiple small STREAM frames in the same packet we can store all initial
HTTP/3 frames (various control stream opening, SETTINGS, HEADERS, ...)
from the client in a single packet.
=> coalesce small STREAM frames when fuzzing

examples/http3-server.rs, src/h3/mod.rs, src/lib.rs, tools/apps/src/lib.rs
See commit messages.
The first commit is actually a follow-up to https://github.com/cloudflare/quiche/commit/56fc60bfa2d92e3abfd6c06a47c191dcb439eac8. It fixes the fact that the flow control limit didn't actually decrease until a STREAM frame was sent on the wire, so the application could keep writing data without having the connecion flow control matter. It's not strictly necessary for the HTTP/3 fix, but it makes writing a test for that easier so I put them in the same PR.
=> Handle partial writes of HTTP/3 HEADERS

extras/nginx/nginx-1.16.patch
As #17 and #23 discussed, the patched nginx needs to be linked with Apple's Security framework when compiling on macOS. https://github.com/cloudflare/quiche/commit/e1f9d135cae6f8aedaaebb31457b1234f115bc60 should fix that.
=> nginx: MacOS build

extras/nginx/nginx-1.16.patch
Follow-up to 572cf96, needed to handle the StreamBlocked error.
=> nginx: handle blocked stream when sending HEADERS

src/lib.rs
tx_data is "The sum of the largest received offsets on all streams"
so it need to be increased when we send a new data. If we decrease
tx_data while retransmitting it will result sending more data,
so the receiver will get more data than reported in MAX_DATA frame,
causing FLOW_CONTROL_ERROR.
=> Don't decrease tx_data when retransmit

tools/qlog/src/event.rs, tools/qlog/src/lib.rs
qlog: Add remaining EventTypes and helper functions
Previously, the qlog data model was missing some
event types (e.g. HTTP/3 and QPACK) and there were
a few incorrect fields peppered throughout the code.
While fixing up the code, I also spotted some of the
burden on calling applications. I've attempted to
improve life by adding an Event module that couples
EventCategory, EventType and EventData. It provides
methods to concisely construct valid events, and if
people want to manually construct such events they
can use an is_valid() method to catch obvious errors
such as trying to log a TransportEventType with
HTTP/3 EventData.
Applications that use some or all of the helpers
should find it much more difficult to produce bogus
data.
cc: @hawkinsw @agrover @rmarx
=> qlog: Add remaining EventTypes and helper functions

src/lib.rs
Otherwise we would end-up sending draft-27 transport parameters on
earlier drafts connections.
=> re-encode transport parameters when changing versions on the server too

src/lib.rs
In one scenario, quiche will power a server
that supports a range of QUIC versions. So
test that clients can complete a handshake
for each version in that range.
=> lib: add client version test

tools/qlog/src/lib.rs
Previously we derived qlog serde deserialize code
and this was not heavily tested. In some offline
tests, I found that the deserializer often failed
to construct the correct object, especially for
EventData which contains the most useful data.
A quick analysis puts this a few factors:
* EventData is an enum that is untagged, which
means serde has to do some "duck typing".
* qlog is very flexible and allows omission of
many fields, that makes guessing harder.
* EventData variants can be quite similar in
structure and serde geusses in first-to-last
order. This causes, for example,
EventData::PacketSent to be deserialized as
EventData::PacketReceived. Probably the worst
possible aliasing.
The deserialization code ends up quite large,
I counted ~12k LOC jus for EventData. Until a
robust …
=> qlog: remove derived deserialize

src/cc/mod.rs, src/cc/reno.rs, src/recovery.rs
To reduce calling Instant::now() inside congestion control hooks,
add a timestamp (`now`) parameter to the following hooks:
- `on_packet_sent_cc()`
- `on_packet_acked_cc()`
=> cc: pass timestamp to hooks

src/lib.rs
Follow-up to e739f554 and 2e04d446.
The idea is that invalid packets that haven't been authenticated
shouldn't cause a connection to be aborted, as they may be injected by
malicious man-in-the-middle or man-on-the-side attackers.
We were already doing this for undecryptable packets, but there were a
number of cases not covered.
=> ignore invalid unauthenticated packets

include/quiche.h, src/ffi.rs, src/lib.rs, src/recovery.rs
My original objective was to expose the delivery rate via `Stats`, though while at it I made some clean-up to the recovery and rate estimation code.
=> expose delivery rate in Stats + clean-up

src/tls.rs
The newer version of BoringSSL has an incompatible API change: the read
and write secrets are now set from separate callbacks, instead of the
same one.
In pratice this is not much of a problem, as the code is already capable
of setting read and write secrets independently.
=> deps: update BoringSSL

tools/apps/src/bin/quiche-client.rs, tools/apps/src/bin/quiche-server.rs, tools/apps/src/lib.rs
Follow-up to 8a1aff78fe0b484ff14ad2cb67627b7696c77eaf.
The idea is to basically downgrade logs that were previously DEBUG, to
TRACE, so we can actually see the logs that were originally INFO but are
now DEBUG.
=> apps: downgrade more logs

extras/docker/Dockerfile
* Make a debug build for docker images
(non-docker build is already debug build).
qns test doesn't need a high performance so it should be ok
* No need to run `update-ca-certificates` (it will run at installation time)
* Add `git log..` for logging quiche commit is built. Only for
travis log.
Also, current total build time is half dominated by docker build (taking >10 min) at the end of master build. Probably better to make it parallel task?
=> docker: small build time improvement

src/lib.rs
Instead of unconditionally cloning optional QUIC header values, check
that the output packet type requires them
=> avoid some needless small allocations when creating packets

extras/docker/qns/run_endpoint.sh
Follow-up to 77f9f8bf16461db361d0052d7c7cae4d8dae2b1c.
Forgot about this in the previous PR :man_facepalming:
=> qns: actually enable 0-RTT in resumption/zerortt tests

src/lib.rs, src/stream.rs
When we add frames in Connection.send(), some frames are missing
checking if there is enough space left in the packet (`left`),
may cause underflow of `left` in release build (debug build
it will crash runtime)
=> Make sure there is enough space left in the packet before adding frames

src/lib.rs
Make sure the packet is marked as ack-eliciting and in-flight when
HANDSHAKE_DONE is sent. In practice the packet is marked properly in
most cases due to other frames (e.g. CRYPTO), but this ensures that it
is.
---
This is based on https://github.com/cloudflare/quiche/pull/407.
=> HANDSHAKE_DONE is also ack-eliciting and in-flight

src/lib.rs
When it tries to corrupt buf[], there is a 1/256 chance of test
failure when buf[written - 1] = 0. Try to have always different value
by inverting bits.
=> Fix invalid_initial() and invalid_packet() tests

src/lib.rs, src/minmax.rs, src/recovery.rs
Port google opensourced min-max filter code based on
Kathleen Nichols' algorithm for tracking the minimum
(or maximum) value of a data stream over some fixed
time interval.
=> recovery: windowed min and max filter implementation

src/ffi.rs, src/lib.rs, src/recovery.rs
delivery_rate is defined as bytes/sec, so no need to be f64.
=> recovery: change delivery_rate to u64

src/h3/mod.rs, src/h3/stream.rs
We already have a few measures in place to prevent DATA before HEADERS, mainly on the client side. This change just enhances that by adding some tracking into the `h3::Stream` object for local initialization (this is special because `Stream` is generally geared around tracking state of the stream as data is read).
=> h3: prevent DATA before headers

tools/apps/src/bin/quiche-server.rs, tools/apps/src/lib.rs
When a stream doesn't have enough capacity, we might receive a partial
HTTP/0.9 request. Before handling it we need to wait until the full
request is received.
=> apps: handle partial HTTP/0.9 requests on the server

Cargo.toml, clippy.toml, include/quiche.h, src/ffi.rs, src/frame.rs, src/lib.rs, src/packet.rs, src/ranges.rs, src/recovery.rs, tools/apps/Cargo.toml, tools/apps/src/bin/quiche-client.rs, tools/apps/src/bin/quiche-server.rs, tools/apps/src/lib.rs, tools/qlog/Cargo.toml, tools/qlog/README.md, tools/qlog/src/event.rs, tools/qlog/src/lib.rs
This is still WIP but ready for review. I need to add tests for the new capability but will await design feedback.
The PR contains 2 commits, the older one uses a buffered serialization approach, the newer one replaces this with a streaming serialized approach. I left these so that we could compare the two, but we'd definitely squash this down before any merge.
To test this out, you can run quiche-client or quiche-server with the `QLOGDIR` environment pointing at a folder. The resulting trace will be written to a file such as `client-{scid}.qlog` which can then be imported to the visualization tool https://qvis.edm.uhasselt.be.
=> add optional qlogging to quiche

src/lib.rs, src/recovery.rs, tools/apps/Cargo.toml
Both the apps crate and quiche itself optionally depend on the qlog
crate, however the apps crate enables quiche's qlog feature
unconditionally. This means that even if the qlog feature of the apps
crate is disabled, the qlog crate will still be built.
However the apps crate doesn't need to depend on the qlog crate at all,
as it doesn't use it directly. This change removes the dependency, and
turns the qlog feature into an explicit feature that only enables
quiche's qlog feature when enabled.
---
Also, we might want to enable the `qlog` feature in the apps crate by default.
=> apps: make 'qlog' feature really optional

src/lib.rs
We currently only check for the connection's flow control limit when
passing writable streams to the application, but we should also check
for cwnd.
This prevents the application from trying to send data that might end up
being blocked later anyway.
=> check connection's send capacity when returning writable streams

src/lib.rs
Previously we would attempt to write a qlog metrics_updated
event while processing frames in a received packet. This would
silently fail because qlog was in the middle of writing a
packet_received event.
This change moves metrics_updated writing to the point after
the packet_received event is complete. This might cause a slight
inaccuracy in the event's reported time but it is better than no
event at all.
Anecdotal test against cloudlare-quic.com:
before = 15 metrics_updated events
after = 27 metics_updated events
=> qlog: fix qlog metrics_updated on recv

extras/nginx/nginx-1.16.patch
Due to the fact that the underlying QUIC connection is already closed
(e.g. due to idle timeout), the open HTTP/3 streams need to be forcibly
terminated (e.g. if a stream was blocked, it would end up never being
unblocked because the client can't provide additional stream credit, so
the stream would never be closed).
=> nginx: forcibly close HTTP/3 stream when finalizing QUIC connection

tools/apps/Cargo.toml
The quic-interop-runner sets the `QLOGDIR` env var (https://github.com/marten-seemann/quic-interop-runner/blob/master/docker-compose.yml), so all we need to do is enable the feature in our quiche apps. Tested the interop runner locally and it seems to work fine, dumping the qlog output to `logs/qlog/{role}-{CID}.qlog`
~Note that I think this also enables the feature for both the `cloudflare/quiche` and `cloudflare/quiche-qns` images but I think that is an acceptable tradeoff. The alternative is probably a complicated branching dockerfile :nauseated_face:~
=> apps: make qlog feature default

src/ffi.rs, src/lib.rs, src/stream.rs, src/tls.rs
This PR addresses comments in #32 which taken together imply that Connection could be Send (but not Sync). Doing so would greatly ease integration in a project I'm working on, so I thought I'd see what the maintainers think.
=> Make Connection Send

src/lib.rs, tools/qlog/src/lib.rs
Follow-up to 2f49a25. If the qlog feature is enabled in quiche,
Connection stops being Send (and the tests fail).
=> qlog: make QlogStreamer Send-able

Cargo.toml
Follow-up to 6a9fddd4e67165a6ba63eeb95ee6d90b28f503fa.
=> Cargo: remove other mentions of benches

extras/docker/qns/run_endpoint.sh
The server doesn't need to wait for the simulator to be up since it
doesn't send anything on its own.
=> qns: don't wait for it when starting the server

Cargo.toml, src/frame.rs, tools/qlog/src/lib.rs
This adds the HANDSHAKE_DONE frame to qlog, and makes quiche log it.
This also removes the "unknown frame" case in the Frame::to_qlog()
method, as there can't be unknown frames, and it hides missing frame
types conversions.
=> qlog: add HANDSHAKE_DONE frame

extras/nginx/nginx-1.16.patch
Somewhat interestingly, GCC only reports a warning for this when all
optimizations are disabled (-O0), while Clang always reports it.
Reported by @morf (https://github.com/cloudflare/quiche/commit/349a63f672d80320b1f6989d16d8bdae5d1fba8e#commitcomment-38326179).
=> nginx: initialize 'fc' earlier when closing stream

src/lib.rs
When an invalid first packet is received the connection is correctly
marked as closing, however due to the anti-amplification mechanism it is
prevented from actually sending anything.
Since the draining timeout is armed only when `CONNECTION_CLOSE` is
actually sent, and the idle timeout is armed when a packet is processed
successfully, the connection ends up never being closed.
=> immediately mark connection as closed when receiving an invalid first packet

src/recovery.rs, src/recovery/delivery_rate.rs
The delivery rate estimation code is fairly self-contained, so it can be
moved into its own submodule pretty easily.
=> recovery: refactor delivery rate estimation

README.md, examples/client.c, examples/client.rs, examples/http3-client.c, examples/http3-client.rs, examples/http3-server.c, examples/http3-server.rs, examples/server.c, examples/server.rs, src/lib.rs, tools/apps/src/bin/quiche-client.rs, tools/apps/src/bin/quiche-server.rs
This changes the `recv()` public method to never return `Error::Done` to
applications, due to confusion of its meaning and misuse.
Many applications (including the quiche-apps and quiche examples) have
been interpreting the Done error as a signal to stop reading incoming
packets from a socket. However this is wrong, as applications shouldn't
stop reading incoming packets, as that might cause a deadlock where the
socket is not re-armed by the event loop and even if a connection is
closing, new packets should still be processed as the socket might be
shared among multiple connections.
Instead of `Error::Done`, `recv()` will now return an `OK(...)` value
with the full size of the incoming buffer, to mean that the entire
buffer has been processed (or ignored), which was the intended meaning …
=> don't return Error::Done from recv()

src/lib.rs, src/stream.rs, tools/qlog/src/event.rs, tools/qlog/src/lib.rs
Opening mainly to get some eyes on.
Qlog draft 02 has a data_moved event that allows logging when stream data is moved into or out of the transport. Logging this information allows us in the qvis multiplexing tool to see how the quiche-client reads data from the transport layer.
Our definition of data_moved is bit old, so this change tweaks it to contain the length. In testing I found that `SendBuf.off()` always returned `0` while the qvis expects the offset to move along at the stream offset grows. That is why I added the `cumulative_offset()` function as a hack. Happy to hear a better solution to this.
Right now data_moved is in the category HTTP/3 but that will change to be transport soon. So we can rename things in a separate followup PR.
=> Qlog data moved

examples/http3-server.c, examples/server.c
Fixed the path for the certificate and key files in server.c file in examples.
With the existing path, it leads to -
**`quiche::tls: error:100000ae:SSL routines:OPENSSL_internal:NO_CERTIFICATE_SET`**
=> fixed certificate and key path in .c examples

examples/http3-server.c
Fix http3-server.c example early connection 'fin', subsequent call to quiche_h3_send_body seems useless.
=> Fix http3-server.c example early connection 'fin'

src/lib.rs
Follow-up to db5e6acd59a4d15eb6f79a68d315a60bd729570e.
Nothing is preventing an application from calling e.g. send() after a
connection is already closed, so it might end up accidentally sending a
packet after closure.
=> do nothing if connection is already closed

src/lib.rs
The 0x100 error space is reserved for TLS alerts, so if we encode
generic CryptoFail and TlsFail as 0x100 the peer might interpret it as a
close_notify alert,  but that is not the intention.
TLS alerts are handled separately so this change doesn't affect that.
=> encode generic CryptoFail and TlsFail errors as PROTOCOL_VIOLATION

extras/nginx/nginx-1.16.patch
When nginx is built with --with-debug, `quiche_log()` is called
for debug log. In this functino `line` is used for format
string of sprintf().  When it contains a format string such as '%d',
it expects additional parameter but we only provide one, it can crash
nginx at logging.
=> Fix nginx crash at debug logging

Cargo.toml, include/quiche.h, src/lib.rs, src/recovery.rs, src/recovery/cubic.rs, src/recovery/reno.rs
- Implemented based on RFC8312 "CUBIC for Fast Long-Distance Networks"
- CUBIC is the default CC algorithm.
- CUBIC specific variables is stored to cubic::State. I added
this to Recovery structure itself. If you use Reno only
this will be a waste of memory if you use Reno, but the overhead
is small (4 fields) for now. It can be dynamically allocated later.
- `f64` is used for various calculations. Optimization using integer ops is a future task.
- Use libm::cbrt to avoid linking with -lm for C applications. Note that libm:cbrt
is slower than C cbrt() which is asm-optimized (roughtly 2x when I
test in MacOS) but the difference is small.
- For config API, to use Cubic explicitly for the connection, call the following:
Rust: config.set_cc_algorithm(recovery::CongestionControlAlgorithm::Cubic) …
=> CUBIC congestion control

extras/nginx/README.md
The HTTP/3 code does not support request buffering right now, so
enabling proxy_request_buffering will break POST requests.
=> nginx: disable request buffering in config example

extras/nginx/nginx-1.16.patch
Debug lines for new QUIC connections print the server's
SCID. Previously, we mistakenly used the length the client SCID
which could cause some incorrectness. For example, Chrome sends
a 0-length SCID.
This change ensures we use the actual server SCID length.
=> fix debugging when SCID length is mismatched

src/h3/mod.rs
AFAIK, There is no pseudo-header like `:user-agent` in [draft-ietf-quic-http.html#section-4.1.1.1](https://quicwg.org/base-drafts/draft-ietf-quic-http.html#section-4.1.1.1)
=> chore:h3:correct doc typo

tools/qlog/src/lib.rs
This is only derived for a single type, and it doesn't look like we
actually need it since we don't support deserialization.
=> qlog: don't import Deserialize trait

examples/qpack-decode.rs, fuzz/src/qpack_decode.rs, src/frame.rs, src/h3/frame.rs, src/h3/mod.rs, src/h3/qpack/decoder.rs, src/h3/qpack/encoder.rs, src/h3/qpack/huffman/mod.rs, src/h3/stream.rs, src/lib.rs, src/octets.rs, src/packet.rs, src/tls.rs
This changes the `octets` API into immutable and mutable variants of the same API. The main motivation for this is to avoid having to take mutable references to buffers when decoding read-only buffers (in most cases there's no reason to use mutable references other than the fact that the octets API forces it).
For example, when parsing transport parameters we get an immutable buffer from the BoringSSL API, so in order to use it with the octets API we currently need to clone it so that we can get a mutable reference. Though in general it's a good idea to use immutable references when the data doesn't actually need to be modified, which happens a lot.
The duplication in `octets.rs` is somewhat unfortunate, though I couldn't figure out a nice way to avoid it for now, but it can be improved …
=> Mutable and immutable variants of Octets

examples/client.c, examples/client.rs, examples/server.c, examples/server.rs, include/quiche.h, src/h3/mod.rs, src/lib.rs, src/packet.rs, src/tls.rs, tools/apps/src/lib.rs
This mostly just simplifies how transport parameters are encoded and
decoded, by removing the intermediate buffer required for older draft
versions.
---
I just realized that the C hq client and server have been using a truncated ALPN value....
=> drop support for old draft versions

tools/qlog/src/lib.rs
The CI builds sometimes fail due to timing issues in the qlog tests.
The qlog serializer generates a relative event time when `add_event()` succeeds. I guess it takes the CI slightly longer to run through the test steps, which causes the event time to be greater than the expected value in the `log_string` variable.
The simplest solution is to sample the time just before the successful `add_event` call and hope it doesn't take 1 millisecond to run 2 lines of code. Then substitute the sample time back into the expect log string before the comarison with the generated log.
=> qlog: fix flappy test

extras/nginx/nginx-1.16.patch, src/h3/mod.rs, tools/http3_test/src/runner.rs, tools/http3_test/tests/httpbin_tests.rs
This fixes handling of blocked 0-length HTTP/3 data writes in both quiche and NGINX.
Also adds some machinery to be able to test for this in http3_test.
=> Correctly handle blocked 0-length HTTP/3 writes 

src/lib.rs, src/packet.rs, src/recovery.rs
There is a problem when sender has some leftover data cannot be
sent as a QUIC packet, app_limited is true so cwnd doesn't
grow well, especially during congestion avoidance.
Let's think the following scenario:
- max_packet_size=1200
- at send(): cwnd=1220, flight_size=0, send a full packet, 1200 bytes
- at send(): cwnd=1220, flight_size=1200
we are only able to send 20 bytes, but it does't fit even for
QUIC headers (usually larger than 20 bytes) and
send() returns Error::Done.
In this case, flight_size < cwnd so app_limited is still true.
However the app already send as much as possible to cwnd and
can't send more. This case should be considered
as app_limited=false.
The fix is to check and update app_limited when we return Error::Done
from send(). If still considered limited by cwnd, …
=> lib: fix app_limited to allow cwnd growth

src/lib.rs
Let's think the following scenario:
0. Client sends Initial pn=0
1. Server sends Initial pn=0 -> Lost
2. Server sends Handshake pn=0
Currently when Initial#0 is lost, Client received Handshake#0 and
close the connection immediately because now it gets `Error::CryptoFail`
because Handshake#0 cannot be decrypted.
This can happen when 1 is lost, or reordered so 2 is delivered before 1.
Server doesn't know the connection is closed in the Client,
so keep trying to retransmit and timed out eventually.
The fix is not to immediately close the connection for invalid
incoming packets when Client has no valid received packets. To allow
loss recovery from Server or reordered delivery, now it has a threshold
to allow -- `recovery::PACKET_THRESHOLD` constant is used here because
it's already used for …
=> lib: allow incoming Initial packets lost/reordered

src/lib.rs, src/packet.rs, src/ranges.rs, src/recovery.rs
This removes a potential DoS vector and it ensures that the size of
outgoing ACK frames does not get out of hand, which could cause a
deadlock in case ACK frames cannot fit in generated packets anymore.
Older packet number ranges are simply removed from the start of the
list, to keep the total list length under the limit. This will cause the
peer to spuriously retransmit the data within those packets, though that
seems better than the alternative.
Fixes #489.
=> limit number of tracked packet number ranges that need to be acked

include/quiche.h, src/ffi.rs
Adds a ffi function `quiche_conn_set_qlog` to call `Connection::set_qlog` from C.
Work heavily based on the implementation of `quiche_conn_set_qlog_fd`, but taking a file path as an input instead of a file descriptor, and being, in this way, compatible with non posix OSs (i.e. Windows).
Tested on Windows, Linux and MacOS.
=> Added C ffi function to make set_qlog compatible with Windows

include/quiche.h
Ensure that check_symbol_exists calls in CMake do not fail due to
missing headers. The minimal reproducer can be stripped down to:
echo '#include <quiche.h>' | gcc -Iinclude -fsyntax-only -xc -
A similar (untested) fix for Windows was taken from
https://github.com/cloudflare/quiche/issues/450
=> quiche.h: ensure size_t and ssize_t are defined

src/recovery.rs, src/recovery/cubic.rs, src/recovery/hystart.rs, src/recovery/reno.rs
During LSS, cwnd didn't grow because we reset congestion
recovery start time and `on_packet_acked()` exit early because
it thinks it's in a recovery mode. But there was no congestion
event happened, so LSS should not be considered as a recovery
and cwnd will increase in LSS.
- LSS doesn't initialize congestion recovery start time
and use `lss_start_time` instead. `lss_start_time` is initialized
when LSS started.
- hystart.in_lss() is replaced by lss_start_time().
- `now` is added to recovery.hystart_on_packet_acked().
Note that Reno is not impacted.
=> cubic: fix HyStart++ cwnd growth during LSS

src/build.rs
32bit iOS target is demoted.
https://blog.rust-lang.org/2020/01/03/reducing-support-for-32-bit-apple-targets.html
=> build: remove 32bit iOS support

src/build.rs
When we do `cargo lipo` on Xcode 10.1 (11.2 works fine),
it fails with the following error during BoringSSL build:
```
ld: in libcrypto.a(rdrand-x86_64.S.o), building for iOS Simulator,
but linking in object file built for iOS, for architecture x86_64
```
It looks like we need to have `-target x86_64-apple-ios-simulator`
compiler flag for both C/C++ and asm object not to confuse the linker.
This is not added by cmake so manually added in build.rs.
This hack works both Xcode 10.1 and 11.2 (confirmed by CI).
Fixes #515.
=> build: fix x86_64 iOS build on Xcode 10.1

src/lib.rs
Currently we are not retransmitting MAX_STREAM_DATA frame so
when the client lost the packet containing MAX_STREAM_DATA,
the server doesn't know it can read more when it hits the
flow limit. In this case we can't transfer more on this
stream.
[quic-transport draft 13.3](https://www.ietf.org/id/draft-ietf-quic-transport-27.html#name-retransmission-of-informati) says that MAX_STREAM_DATA need to be
sent with updated value when the frame is lost.
In this PR we only cares about MAX_STREAM_DATA frame but
it seems like many frame types are not retransmitted properly.
Losing MAX_STREAM_DATA frame is more problematic than other
frames such as MAX_DATA because it's stream specific so when
we lost it there is no chance for the server to know unless
retransmitted.
For example MAX_DATA is frequently …
=> retransmit MAX_STREAM_DATA frame if lost

src/tls.rs
* Write the key log line and LF in one go to avoid problems with
multiple interleaving applications.
* Drop the "QUIC_" prefix, since draft-ietf-quic-tls-17 the same HKDF
label from TLS 1.3 is in use. Wireshark v3.1.0rc0-836-gcc50ec3634
supports both, but the "QUIC_" variant is deprecated.
=> tls: write SSLKEYLOGFILE line in one syscall

tools/apps/src/lib.rs
When running quiche-server I got the following message pretty often
when the session hit the bandwidth limit.
```
[2020-05-19T06:34:28.655009788Z ERROR quiche_apps] 8e01440c13c8788bacc6b0c12265cc4210bafc05 stream send failed Done
```
However, all transfer was normal and this seems not an actual error,
so I think it's safe to ignore this error(`quiche::h3::Error::Done`).
=> apps: handling h3::Error::Done

src/lib.rs, src/recovery.rs, src/recovery/cubic.rs, src/recovery/delivery_rate.rs, src/recovery/hystart.rs, src/recovery/reno.rs
Instead of using a BTreeMap, use a VecDeque to track sent packets, which
makes it easier to keep track of acked and lost packets for a short time
after they have been acked or declared lost instead of immediately
removing them from the list, which in turn will allow detecting things
like DSACKs and spurious losses.
Similarly to how the BTreeMap was used, sent packets are appended to the
back of the queue (so they end up being sorted by packet number / sent
time). Access now happen by iterating over the queue from the start
rather than looking up specific packets by packet number. When acked or
declared lost, the packets are simply marked accordingly _without_ being
removed from the queue.
At predefined times, the semt packets marked as acked or lost are then
removed from the start of the …
=> recovery: refactor sent packets tracking

src/minmax.rs, src/recovery.rs
Making this minmax filter implementation generic so that it can be used to get filtered minmax bandwidth for BBR implementation.
=> Make minmax filter implementation generic

include/quiche.h, src/ffi.rs, src/lib.rs, src/tls.rs, tools/apps/src/bin/quiche-client.rs, tools/apps/src/bin/quiche-server.rs
When an application enables key logging in the Config object, quiche
will automatically read the SSLKEYLOGFILE variable and create the
corresponding file to log to.
However this is slightly dangerous as the application is not necessarily
in control of the environment variable, so keys might accidentally end
up being logged without the application saying so. And it generally
doesn't seem to be good form for a library to depend on environment
variables.
The current API is also not very flexible, as it only allows
applications to log to files, and doesn't allow enabling/disabling
logging on a per-connection basis.
So, in addition to calling `log_keys()` on the Config object,
applications now also need to call the `set_keylog()` method on each
connection they wish to log keys for, passing the …
=> improve keylog API

.travis.yml
rustfmt is yet again broken in the latest nightly, so pin the rust
version to the last known good one.
Can revert once https://github.com/rust-lang/rust/issues/73200 is fixed.
=> travis: pin Rust nightly version

tools/apps/src/bin/quiche-client.rs, tools/apps/src/bin/quiche-server.rs
Other implementations running in the interop runner have higher timeouts
which kind of puts us at a disadvantage.
In the future we might want to make this configurable, but for now there
is not much point.
=> apps: increase max idle timeout

include/quiche.h, src/h3/ffi.rs, src/h3/mod.rs, tools/apps/src/lib.rs
This replaces #465.
It builds on top of #513, adding APIs to the H3 layer and setting the priority of the stream prior to sending any data on it. I've included the quiche commit from #465 so that the CI can run properly and allow anyone interested to test it out.
The quiche-client and quiche-server applications have been updated
to test this out. quiche-client can be run with e.g.
`-H "Priority:u=4,i"` to send a priority signal. quiche-server
process the Priority header (or assumes the default if none is
provided). It also supports a special query string syntax that
takes precedence over the header. For example, a client can send
`https://example.com?u=4&i=1` to indicate the priority as `u=1,i`. In this way,
multiple requests can be issued with different priorities, which makes for more …
=> H3 stream priority

src/lib.rs, src/recovery.rs
Currently when sending a PTO probe we either include new data frames or
a PING frame in the packet to make sure that the probe is ack-eliciting.
However if no new data is availabe, we should try to include old data
that has not been marked as lost yet if there is any, instead of just
sending a PING.
This changes that by iterating over old sent packets (that have not been
acked or lost yet) and copying CRYPTO and STREAM frames into the outgoing
packet when creating PTO probes.
This requires cloning the frames, which is somewhat unfortunate, but it
should only happen when PTO expires, which has exponential backoff so it
shouldn't be possible to use this as a DoS vector.
=> try to retransmit old frames on PTO

Dockerfile
Some indirect dependency requires a newer Rust version to build:
https://github.com/BurntSushi/aho-corasick/issues/62
=> docker: bump rust image to latest stable

src/lib.rs
There might be occasions when the frame parsing fails and then we end up leaving the qlog streamer in a state that causes the next packet's frames to be recorded in the wrong event.
=> lib: finish qlog events even on frame error

src/lib.rs, src/recovery/cubic.rs, src/recovery/delivery_rate.rs, src/recovery/mod.rs, src/recovery/reno.rs
In 39905083 we implemented support for retransmitting unacked data in
PTO probes if no new data is available.
However after discussion it seems that prioritizing new data is not
actually necessary, and simply retransmitting old data first might be
the better strategy (if anything it's easier to implement).
This reverts the changes from the previous commit, and simply implements
logic to reschedule the frames from the 2 oldest sent packets when the
PTO expires.
Besides having a much simpler implementation, this also has the
advantage of allowing other frames to be sent in the probe packet (e.g.
ACKs), without risking that the original data frame wouldn't fit in the
output packet, since we won't retransmit CRYPTO and STREAM frames as-is
but will go through the normal packetization procedure …
=> recovery: retransmit frames from 2 oldest unacked packets on PTO

src/lib.rs, src/recovery/mod.rs
Instead of always sending 2 PTO probes, we should start by sending one
probe, and increase to 2 if the previous probe was lost.
This is done by using the current PTO count to determine how many probes
should be sent (up to 2).
---
This depends on https://github.com/cloudflare/quiche/pull/571.
=> recovery: send PTO probes based on PTO count

src/build.rs
This PR fixes an issue with `--release` Windows builds of rust packages using quiche as a dependency (and quiche stand-alone, if built with custom configurations).
What happens (at least in my case) is that cargo builds the dependencies without debug symbols for release builds of a Rust package (i.e. builds with symbols only the root package).
If `quiche` is one of those deps, it gets built `--release` but without the debug symbols, and cmake-rs consistently puts boringssl in a `<somepath>/Release` directory, instead of the `<somepath>/RelWithDebInfo` directory expected by `build.rs` which then fails with the dreaded `could not find native static library 'crypto', perhaps an -L flag is missing?`.
This code synchronizes the behaviour of `build.rs` with [the one included in …
=> Fixed Windows build when used as cargo dependency or building for release without debug symbols

examples/http3-server.c, examples/server.c
fixes #566. Replaces #582
Previously, when doing stateless retry the C example server would
reuse the dcid for new_scid. Once a client sent back the token
and we validated it, a new connection ID would be generated and
sent back to the client as part of the handshake. The client would
detect an error when validating retry_source_connection_id and
close the connection.
This change aligns the C examples to the Rust examples. A new
connection ID is generated and sent in the retry. Once a client
sends back the toked and we validate it, we use the information
at hand instead of generating anything again.
=> examples: align retry mechanism with Rust examples

.travis.yml
We only need Android NDK to build quiche for Android platform.
Simply use rust image from Travis and install NDK.
=> build: simplify Android build

src/lib.rs
This is a regression introduced by 74458c6db64aa50b01314ac8a2fa3e2394c7965c.
We need to check that there are outstanding packets that need to be
acked before trying to create an ACK frame, otherwise a panic is
triggered when the frame is serialized.
=> don't try to create ACK frames if there is nothing to ack

src/stream.rs
When a STREAM frame is received and `get_or_create()` is called, we
assume that the stream was not created locally.
However it can happen that a locally-created stream was already
collected and then duplicated data for it is received.
This means that we should check whether the stream was destroyed, before
validating the stream ID.
=> stream: only validate stream id of new streams if they never existed

src/lib.rs, src/packet.rs, src/recovery/mod.rs
This updates how PTO and loss timeout are calculated based on the latest
recovery draft. It also fills in some gaps we had, notably arming PTO
when the peer has not completed address validation to prevent deadlocks
during handshake.
=> recovery: update calculation of PTO and loss timeout

src/recovery/cubic.rs
Implements quicwg/base-drafts#3917 for CUBIC.
=> cubic: use appropriate byte counting

src/stream.rs
When "popping" a RangeBuf that exceeded the maximum capacity of the
output buffer, we would simply split-off the internal buffer up to the
maximum cap, and then push a new RangeBuf back into the send or recv
buffer.
This is inefficient for two reasons:
1. Splitting off a Vec means duplicating the remainder of the buffer
into a new Vec. Depending on the size of the original buffer this
could be very expensive, which is why we had a hack to split-off
buffers received by the application before creating the original
RangeBuf.
2. Pushing back the new RangeBuf into the send or recv buffer is
potentially expensive as a binary heap is used.
The new popping implementations allow for a RangeBuf to be partially
consumed at its start, without the need for splitting it off.
The downside is that the …
=> stream: allow RangeBuf to be partially consumed without splitting

extras/nginx/nginx-1.16.patch
`ngx_msec_t` is `uint_t` and it's 32bit in 32bit platform. However
`quiche_conn_timeout_as_millis()` returns `uint64_t` and comparing
`ngx_msec_t` with `UINT64_MAX` is not meaningful. (compiler
gives a warning)
Fix here is we check the return value of `quiche_conn_timeout_as_millis()`
first and cast to `ngx_msec_t`. In 64bit platform `ngx_msec_t` is
`uint64_t`, so no casting there.
Fix #648
=> nginx: ngx_msec_t is 32bit in 32bit platform

tools/qns/run_endpoint.sh
This is required since https://github.com/marten-seemann/quic-interop-runner/pull/221.
=> qns: explicitly enable ChaCha20 test on the server

fuzz/src/qpack_decode.rs, src/h3/qpack/decoder.rs, src/h3/qpack/huffman/mod.rs
This is a violation of the HTTP/3 spec, as upper-case header names MUST
be treated as invalid. However we delegate this check to the aplication.
This partially reverts 0812aa2aa8083b7fe14178c11e9fa185eb6ba9b7.
=> qpack: don't lower-case incoming header names

Dockerfile
We don't need Go during build anymore.
=> Dockerfile: no need to install Go

tools/apps/src/bin/quiche-client.rs, tools/apps/src/lib.rs
This change introduces the `--dump-json` option for quiche-client.
When enabled HTTP/3 request headers, response headers and
response body (up to a hard-coded 10KB limit) is written to stdout
once all requests complete or the client times out.
Timed-out requests contain empty values.
The format is HAR-like but simplified.
=> apps: add quiche-client JSON dump option

examples/http3-client.c, examples/http3-client.rs, examples/http3-server.c, examples/http3-server.rs, extras/nginx/nginx-1.16.patch, include/quiche.h, src/h3/ffi.rs, src/h3/frame.rs, src/h3/mod.rs, src/h3/stream.rs, tools/apps/src/lib.rs, tools/http3_test/src/runner.rs
**_NB this is mostly done, I just need to have another sanity check of the API and error conditions that we CAN detect._**
Previously, quiche did some basic GOAWAY frame reception validation
internally but did not expose a method to send GOAWAY, nor an event
to inform apps that a GOAWAY had been received.
On the sending side, this change adds the `send_goaway()` method
that an application can use to send a GOAWAY frame that informs the
peer of the intention to close the connection.
On the receiving side, this change adds the `h3::Event::GoAway`
event which is returned by `poll()`.
The GOAWAY frame contains an identifier field, which affects how an
application should continue using the HTTP/3 connection. This change
is based on the draft-28 version of GOAWAY, which permits
both endpoints …
=> h3: add GOAWAY API

tools/apps/src/bin/quiche-client.rs, tools/apps/src/lib.rs
This should make it easier to use quiche-client in scripts.
=> apps: return non-zero status code for incomplete requests

src/lib.rs, src/stream.rs
The documentation of this method doesn't match what it actually does.
Also rename it to be consistent with SendBuf.
=> stream: fix name and documentation of method returning lowest recv offset

src/lib.rs, src/stream.rs
Currently we use the "raw" received STREAM frame length to check that
received data doesn't exceed the connection-level flow control limit.
However it can happen that the same data is received in two different
overlapping STREAM frames. In the current implementation this data ends
up being counted twice towards the flow control limit.
Instead use the difference between the frame's maximum offset and the
stream's maximum received offset.
This is consistent with §19.9 of the -transport draft:
The sum of the final sizes on all streams - including streams in
terminal states - MUST NOT exceed the value advertised by a receiver.
=> don't count dup data towards flow control limit

extras/nginx/nginx-1.16.patch
This simply refreshes the metadata in the patch by re-exporting it.
No functional changes.
=> nginx: refresh patch

.travis.yml
https://rust-lang.github.io/rustup-components-history/
pin to 2020-10-25.
=> build: rustfmt missing since 2020-10-26

src/h3/mod.rs
This wouldn't cause any problem if the client consistently sent, or consistently did not send, prioritiy parameters. However, if a client mixed things up and omitted sometimes (which the spec recommends it does for defaults) then scheduling results might not meet expectations.
=> h3: ensure urgency is always shifted

examples/http3-server.rs, examples/server.rs, src/lib.rs, src/packet.rs, tools/apps/src/bin/quiche-server.rs
This introduces a new "ConnectionId" type that represents a QUIC
connection ID as either a Vec<u8> (as we do right now) or a &[u8].
The latter form allows us to avoid cloning the connection IDs when
generating outgoing packets. When parsing incming packets we still
need to use a Vec though.
Note that this is a backwards-incompatible API change as it modifies
the public Header type.
=> avoid cloning connection IDs when sending packets

.github/workflows/deploy.yml, .github/workflows/nightly.yml, .github/workflows/stable.yml
This adds some GitHub Actions workflows. It's not quite as complete as the Travis CI configuration yet (e.g. missing Windows, macOS, Android builds), and I couldn't test the deploy workflow yet (only one way to find out if it works...). Also, we first need to create the secret for the Docker Hub credentials (though we could also just publish the image on the GitHub registry instead which might be easier).
One advantage of Actions vs Travis CI is that we seem to have a bigger number of concurrent jobs available, so the build overall should take less time than on Travis. Not quite sure yet whether we'll end up hitting the monthly limits yet though.
=> initial GitHub Actions workflows

src/lib.rs, src/octets.rs
Instead of waiting to write frames into the packet to after all frames
are generated, write frames immediately after creation.
For now this doesn't really make much of a difference, but in the future
this will allow writing stream data directly into the packet without
having to copy it into an intermediate buffer first, which should also
decrease the number of allocations.
This requires changing how the payload length is encoded into the packet
as well. Since we don't know the length in advance, we simply reserve a
fixed number of bytes, and later fill this space once all frames have
been encoded.
For the time being we still maintain a vector of all frames. This is
mostly only for logging purposes to avoid logging frames before packet
headers, as the latter are logged alongside the …
=> write frames into output packet upon creation

src/lib.rs, src/stream.rs, src/tls.rs
This changes the internal storage of SendBuf to a VecDeque, but it
doesn't change the underlying logic. In the future this will allow us to
change how SendBuf data is emitted to avoid the allocation and
additional copy we currently perform.
In most cases insertions to the SendBuf happen at the end of the buffer,
however, due to the fact that buffers need to be stored in order, in
case of retransmissions they might happen at any index in the vector.
While at it, the SendBuf::push_slice() method is also renamed to
SendBuf::write() to be consistent with RecvBuf.
=> stream: use VecDeque to store SendBuf data

examples/client.c, examples/client.rs, examples/http3-client.c, examples/http3-client.rs, examples/http3-server.c, examples/http3-server.rs, examples/server.c, examples/server.rs, include/quiche.h, src/ffi.rs, src/lib.rs, src/recovery/cubic.rs, src/recovery/hystart.rs, src/recovery/mod.rs, src/recovery/reno.rs, tools/apps/src/bin/quiche-client.rs, tools/apps/src/bin/quiche-server.rs, tools/http3_test/src/runner.rs
In the recovery module we use MAX_DATAGRAM_SIZE constants (1452)
and when the actual payload size (max_udp_payload_size) parameter
and the actual max size of the packet doesn't match, the congestion
control might work inefficiently. For example quiche-server
sets max_udp_payload_size and max udp packet size to 1350, but
since MAX_DATAGRAM_SIZE is 1452, the congestion window grows
too fast then expected, resulting unnecessary packet loss due to
overtransfer.
This PR changes MAX_DATAGRAM_SIZE as a configurable parameter
and adds set_max_datagram_size() API for the application.
When tested, this can reduce errors such as timeout a lot when
running in very high bandwidth/rtt environment.
=> recovery: configurable max_datagram_size

src/octets.rs
get_u64() will get in a network order and it passes all tests. Let me know if there is any concerns.
=> octets: simplify get_varint()

src/frame.rs, src/stream.rs
This changes how RangeBuf objects are allocated when sending data.
Currently a new RangeBuf is allocated for each application write (of the
size of the write itself).
This change makes it possible to allocate RangeBufs of a pre-defined
capacity, whether the application data can fill it or not:
* If the application data is bigger than the RangeBuf capacity, new
RangeBuf objects are allocated (with the same fixed capacity) until
all the application data has been stored.
* If the application data is smaller than the RangeBuf capacity, the
RangeBuf is stored with the unused capacity at the back of the
SendBuf. Following writes will then try to fill the trailing RangeBuf
if it has any spare capacity.
The use of Arc<RwLock<>> for the RangeBuf's internal buffer makes
accessing the data somewhat …
=> stream: allocate send RangeBuf with consistent sizes

src/lib.rs
This test is sometimes flappy and it's because when ack delay
encoded in the ACK frame is higher than 63 it uses 2 bytes,
instead of 1 bytes the test is expecting.
Tests are running locally so ack delay expected to be very small,
but this is microseconds granularity. For example ack_delay=82
means 656 microseconds (82 << 3, 3 is default ack_delay_exponent)
and it's still small (under 1milliseconds) but can happen when
the test server is slow (e.g. docker container, emulator, etc)
Workaround is to increase ack_delay_exponent parameter. It will
encode ack delay to lower number and makes the possibility to
become higher than 63 very small. I choose 5 here. For example
656 microseconds in the above example now encoded to 20, using
only one 1 varint byte.
Note that there is a still possibility …
=> test: fix a flappy tests::empty_stream_frame

src/lib.rs
If no other frame other than APPLICATION_CLOSE needs to be sent,
Connection::send() would return early and not send the frame.
This ensures that a packet is properly sent if APPLICATION_CLOSE needs
to be sent.
=> ensure APPLICATION_CLOSE frame is sent

include/quiche.h, src/ffi.rs
Added `quiche_conn_trace_id` to FFI. Covers #713.
=> Expose Connection:trace_id in C API

include/quiche.h, src/ffi.rs
Added `quiche_conn_stream_priority` to FFI. Covers #721.
=> Expose Connection::stream_priority in C API

src/ffi.rs, src/lib.rs, src/stream.rs
This makes both Config and Connection Sync-able (in addition to
Send-able which they were already).
The biggest hurdle is the fact that the BoringSSL SSL_CTX and SSL
structures are not thread-safe, so they need to be wrapped in Mutex.
In the case of Config this probably has no real downside, since an
application is not supposed to keep changing it once the initial
configuration is applied.
For Connection, this might affect performance slightly, but mostly just
during the handshake. However some of Connection's methods (like
`is_established()`) could be called repeatedly by the application even
after the handshake, so we "cache" the return value (since they won't
change after the handshake is complete) so we won't need to go through
the mutex anymore.
=> make Config and Connection Send + Sync

src/lib.rs, src/tls.rs
Currently we depend on the fact that a 1-RTT packet needs sending for
other reasons, in order to send that frame. Usually that happens because
we need to send TLS session tickets, or initialize an HTTP/3 connection,
but that's not guaranteed.
=> ensure HANDSHAKE_DONE frame is sent

src/lib.rs
Follow-up to b1316fcf53f5065477d2c86e8707a82928260217. When logging the
"connection established" trace log, the handshake lock is already held
when `self.is_resumed()` is called, which also attempts to access the
handshake object through the mutex.
This only happens if the logging is enabled at the trace level.
=> fix deadlock in handshake completion trace log

.github/workflows/nightly.yml
There isn't much point to build this on both stable and nightly.
=> ci: remove quiche_x86 build from nightly

src/lib.rs
When processing ACK frames, quiche collects streams if the conditions
are suitable. Previously, endpoints exchanging 0-length STREAM frames
could confuse things, causing the stream to be collected while still
readable(). Applications that attempted to call stream_recv() would
encounter a InvalidStreamState error.
This change adds a check for is_readable() to the ACK processing, and
a test case to demonstrate the sequence of events that previously
triggered the error.
=> lib: defer collecting streams when ack'ing empty frames

src/h3/mod.rs
See also #740
If the server is finishing the stream with sending an empty frame with
the FIN bit set after the client has recv'd the body of the response,
the subsequent poll is returning Error::Done instead of raising
Event::Finished. If there is no more data to be received, the client
might not call poll again. Thus, make sure to raise the event properly
in such cases.
=> h3: Ensure Event::Finished is raised in poll

src/lib.rs
Let's think the following scenario:
- starting default of stream and connection flow limit
stream#1 limit=100, want to write 150 bytes in total
stream#2 limit=100, want to write 150 bytes in total
stream#3 limit=100, want to write 150 bytes in total
connection limit=300
And let's say server want to write 150 bytes each in the stream.
And all stream has a same priority: each stream data need to be delivered FIFO, which means
we should deliver 150 bytes in stream#1 full and 150 bytes in stream#2, and so on.
- Current behavior
server stream_send() stream#1 100 bytes (stream#1 reach limit = 100)
server stream_send() stream#2 100 bytes (stream#2 reach limit = 100)
server stream_send() stream#3 100 bytes (stream#1 reach limit = 100) (connection reached limit = 300)
server send() stream#1 100 …
=> lib: send MAX_DATA when MAX_STREAM_DATA is sent

.github/workflows/stable.yml
Basically porting what we have in Travis CI to Github Action.
In case of NDK LTS build, I split into each target platform for
parallel build.
- android_ndk_old (r13b)
- android_ndk_lts (21) - 4 targets
=> CI: Add Android build to Github Action

examples/http3-server.rs, examples/server.rs, src/lib.rs, src/packet.rs, tools/apps/src/bin/quiche-server.rs, tools/apps/src/client.rs, tools/apps/src/common.rs
Basically this replaces instances of Vec<u8> used to represent
connection IDs, with ConnectionId.
This also implements a few additional traits for ConnectionId to make
its use a bit easier.
---
This doesn't yet change the public API (well, no more than e0394a87cd75f30caa4ce1863bed3017ef0f7e94 does), but I think we should update `accept()`, `connect()`, `retry()`, etc... at some point to use `ConnectionId` instead of `&[u8]`.
Also, in the server examples/app,  there are a couple more clones of IDs than there were before, because of some lifetime issues I ran into. Will probably need more sleep to figure out a better way around that though :)
=> use ConnectionId more widely

include/quiche.h, src/ffi.rs
`Connection::is_draining` was introduced [here](https://github.com/cloudflare/quiche/commit/a533bcf622ebe25256c5a3c9704ce95bc9eff469) but was not exposed for FFI
=> Add Connection::is_draining FFI

src/lib.rs, src/packet.rs, src/stream.rs
This is not done automatically by the Rust compiler during cross-crate
compilation.
=> mark small public APIs as inlineable

include/quiche.h, src/h3/ffi.rs, src/h3/mod.rs
When DATAGRAM support was added, poll() was updated to return
Event::Datagram. We made the decision to prefer returning such
events ahead of stream events (Event::Headers, Event::Data).
There can be cases when an application wants to handle streams
ahead of DATAGRAMS. However, just reordering things inside poll()
wouldn't work for applications that prefer to read DATAGRAMs.
This change introduces a basic yield mechanism into poll().
Poll() starts by processing DATAGRAMs. Once a threshold
count is hit, it moves to processing request
streams. Once that threshold is hit, it moves back to DATAGRAMs.
The thresholds are configured using quiche::h3::Config. By
default there are no thresholds applied, this maintains prior
behavior.
Since this changes poll(), I've added several unit tests for both …
=> h3: add event yielding to poll()

.github/workflows/nightly.yml, .github/workflows/stable.yml
The idea is to run builds on the "pull_request" event only for external
PRs (i.e. PRs created from forks of the repository), so that PRs created
from internal branches won't run all builds twice.
This should reduce the number of concurrent builds run for internal PRs
by half, which should reduce the time required to show the green check.
Unfortunately there doesn't seem to be a way to configure the condition
globally, so each build need to duplicate it.
=> ci: avoid running duplicate 'push' and 'pull_request' events

Cargo.toml, src/build.rs
This adds an optional dependency on boring-sys, to allow building quiche
as part of projects that use that crate.
=> build: support building quiche against boring-sys

examples/client.rs, examples/http3-client.rs, tools/apps/src/client.rs
Due to the fact that ConnectionId wasn't used for the initial SCID
generated by the client, it would get formatted as a vector, rather
than being pretty printed in hex form.
e.g. see qlog files generated in interop runner in the last few days:
https://interop.seemann.io/logs/2020-11-28T08:09/xquic_quiche/handshake/client/qlog/
=> examples/apps: fix client SCID formatting

src/lib.rs, src/recovery/mod.rs
When peer's max_udp_payload_size is smaller than the sender's
max_datagram_size, update max_datagram_size to match to the
peer's max_udp_payload_size for accurate congestion control.
=> lib: update max_datagram_size if smaller than peer's max_udp_payload_size

src/lib.rs
This will make it possible to augment transport errors with additional
information, and it's the same thing we already do for HTTP/3 errors.
=> turn Error into a Rust enum

examples/http3-server.rs, examples/server.rs, include/quiche.h, src/h3/mod.rs, src/lib.rs, src/stream.rs, tools/apps/src/common.rs
This implements resetting a stream's send-side, as well as sending a
RESET_STREAM frame, upon receipt of STOP_SENDING from the peer.
By resetting a stream, all of its already buffered data is dropped, and
no more writes are permitted.
In order to signal to the application that a stream was "stopped" and
reset, the stream is marked as writable upon receipt of the STOP_SENDING
frame, but when calling `stream_send()` as well as `stream_capacity()` a
new error, `StreamStopped` will be returned.
Returning the error from the `stream_capacity()` is required to make
sure the application is notified in cases where the method is called to
check whether any capacity is available before calling `stream_send()`
(like we do in the HTTP/3 code), and the target stream is blocked (so
`stream_send()` isn't …
=> properly handle incoming STOP_SENDING frames

src/h3/mod.rs
There's no need to keep this open forever, so close it once we sent all
the GREASE data.
=> h3: close GREASE stream

Cargo.toml
When quiche is used a dependency on Windows from crates.io it fails to build because the .asm files for boringssl are missing.
This adds the a new filter to the include part in Cargo.toml so those files are actually there when building.
Fixes #606
=> Add missing .asm files for BoringSLL, required for Windows

src/frame.rs, tools/qlog/src/lib.rs
Previously, we logged DATAGRAM frames as a generic "unknown" frame
event with a hard-coded frame type of 0x30. This change adds a
proper frame definition that results in such frames getting logged
as "datagram" along with the length of the frame payload.
=> qlog: add basic DATAGRAM frame logging

src/lib.rs
It seems we forgot to account for the 1-byte of frame type in dgram_max_writable_len(). Since this went undetected, I've added an explicit assertion of the return value in an existing test. The actual packet overhead varies due to variable DCID length, but the maximum overhead is 44 bytes with this change.
=> lib: fix DATAGRAM fram size calculation in  dgram_max_writable_len()

include/quiche.h, src/h3/ffi.rs, src/h3/mod.rs
We previously landed support for the H3_DATAGRAM setting. This
change adds a method that applications can use to determine if
the peer has sent the SETTING and corresponding Transport Parameter.
Since SETTINGS are processed with poll(), this method will always
return false until a peer has sent a SETTINGS frame with
H3_DATAGRAM=1, and the application has called poll() after the
frame has arrived.
=> h3: add method to expose if H3 DATAGRAMS were enabled

tools/qlog/Cargo.toml, tools/qlog/src/lib.rs
In order to preserve the behavior where multiple frames can be appended on a stream event, the frames field must serialized last. If that is not the case, it is not possible to keep the frames array "open" for appending.
This commit fixes Issue #785, specifically. It uses the preserve_order feature of the serde json library. This feature tells the library to serialize all structure fields in the order that they are inserted.
=> qlog: Always serialize frames field last

src/recovery/cubic.rs, src/recovery/mod.rs, src/recovery/reno.rs
Implements https://tools.ietf.org/html/rfc3465#section-2.2
During slow start, when there is an ACK frame ack'ing
too many packet at once, cwnd will go too high. For example
there is an single ACK ack'ing 5 packets, cwnd will be increased
by 5 x MSS. This can lead to unexpected burst of cwnd, such as
ACK for multiple received STREAM frames, or recovering from a loss.
To prevent from such burst, during slow start an single ACK
will not increase cwnd more than MSS x ABC_L constant. ABC_L is
defined as 2 in RFC3465, and QUIC transport draft also recommends
ACK'ing every two packets (transport-32 section 13.2.2), so this looks
a good number to start.
=> cc: RFC3465 ABC Slow Start

include/quiche.h
When compiling a C program which includes `quiche.h`, the compiler noticed that `quiche_h3_config_set_dgram_poll_threshold` is defined twice.
It seems like changing `dgram` to `stream` was overlooked when this declaration was copied.
=> Fix duplicate declaration in quiche.h

.github/workflows/nightly.yml
Run `cargo fmt` right after toolchain installation.
It should help to catch fmt errors early before trying the actual build.
=> ci: run fmt early

include/quiche.h, src/ffi.rs
Motivation:
It is useful to know the len of the datagram in the recv queue so we can allocate a buffer with the correct size. This is already possible in rust but wasn't exposed in the c layer.
Modifications:
Add quiche_conn_dgram_recv_front_len which expose this functionality in the c layer.
Result:
Be able to obtain the len of the first datagram in the recv queue.
=> Add quiche_conn_dgram_recv_front_len

examples/client.rs, examples/http3-client.rs, examples/http3-server.rs, examples/server.rs, fuzz/src/packet_recv_client.rs, fuzz/src/packet_recv_server.rs, src/ffi.rs, src/h3/mod.rs, src/lib.rs, src/packet.rs, tools/apps/src/bin/quiche-server.rs, tools/apps/src/client.rs, tools/http3_test/src/runner.rs
This changes the remaining public APIs to use the ConnectionId type for
connection ID values, instead of slices.
The FFI API is left as-is, as there isn't much point to introduce a new
type there.
=> use ConnectionId in public functions

Cargo.toml, examples/Makefile, extras/nginx/nginx-1.16.patch, src/h3/mod.rs, src/lib.rs, src/tls.rs
Currently the FFI API is always built, whether quiche is used as part of
a Rust project or not. This can be problematic when multiple versions of
quiche are built as part of the same project, as the FFI API would then
conflict. It also doesn't make sense to expose FFI functions if they are
not going to be used.
This adds a new feature (disabled by default) to enable the FFI API.
=> make FFI API optional

include/quiche.h, src/ffi.rs, src/lib.rs, src/stream.rs
Motivation:
Sometimes its useful to know if a stream creation would be allowed before actual trying to create the stream.
Modifications:
Add peer_max_streams_bidi() and peer_max_streams_uni() that can be used to check for the maximum allowed stream id by the remote peer.
Result:
Fixes https://github.com/cloudflare/quiche/issues/734
=> Add peer_max_streams_bidi() and peer_max_streams_uni()

tools/http3_test/src/lib.rs, tools/http3_test/src/runner.rs, tools/http3_test/tests/httpbin_tests.rs
Previously, http3_test was focused on successful tests where the server
under test was expected to handle requests and provide complete
responses. If an error occurred the test runner would panic and throw
up to the invoker to deal with.
With this change, instead of panicking, the Result is returned directly
to the invoker. This allows for checking success or failure
explicitly.
Several new test cases have been added that ensure the server can handle
clients that violate rules set out in the HTTP/3 spec.
=> http3_test: add some negative test cases

src/lib.rs
Delivery rate is instanteous and is calculated at the end of every ack received. Logging it with entire connection level stats is misleading.
=> Remove delivery rate in the connection level stats logs

.github/workflows/stable.yml
- `cargo ndk` command line option are changed in v2.
- Since triple target doesn't work, a list of (triple, target) is added in the build matrix.
- arm-linux-androideabi is replaced with x86_64-linux-android
=> ci: use cargo ndk 2

.github/workflows/stable.yml
Android builds keep failing randomly when downloading the Android NDK
from Google's servers with error "Error in the HTTP2 framing layer", so
disable HTTP/2 when downloading.
=> ci: use HTTP/1.1 to download Android NDK

.github/workflows/nightly.yml, .github/workflows/stable.yml, examples/Makefile
It looks like we are not building rust (not C) examples in examples/ directory in CI.
=> ci: build rust examples

include/quiche.h
Motivation:
quiche_rangebuf is not used anymore, we should remove it from the header file.
Modifications:
Remove unused typedef
Result:
Code cleanup
=> Remove quiche_rangebuf as it is not used anymore

src/tls.rs
Motivation:
BoringSSL uses CRYPTO_BUFFER to store the raw DER certificate already so we can make use of this and so allow to retrieve the DER certificate without the need to decode the X509 representation on each call.
Motiviation:
Use the CRYPTO_BUFFER via SSL_get0_peer_certificates
Result:
Less overhead when calling Connection::peer_cert()
=> Use CRYPTO_BUFFER to retrieve the peer certificate

extras/nginx/nginx-1.16.patch
ENOBUFS shouldn't be a fatal error, so avoid closing connection when we
get it, but end send loop early.
=> nginx: handle ENOBUFS and incomplete writes

README.md, tools/android/build_android_ndk19.sh
cargo-ndk v2 changed command line options. CI already runs with
updated version, so the documentation only need to be updated.
=> doc: update android cargo-ndk instructions

src/lib.rs, src/tls.rs
Fixes #837.
---
This extracts the BoringSSL update from https://github.com/cloudflare/quiche/pull/826.
=> tls: update BoringSSL version

src/recovery/cubic.rs, src/recovery/delivery_rate.rs, src/recovery/hystart.rs
For nightly build (cargo doc).
=> ci: Fix "this URL is not a hyperlink" warning

Dockerfile, README.md, src/lib.rs
Instead of writing one QUIC packet at a time, `send()` will now try to
coalesce multiple packets onto the same UDP datagram.
In order to support that, padding of Initial packets needs to be moved
outside the QUIC packet itself, so instead of using PADDING frames, we
simply leave some free space at the end of the datagram.
One notable change, is that Initial packets from the server are now also
padded as needed to reach the minimum 1200 length. This is to ensure
that the network path actually supports the minimum size in both
directions.
Though in practice this doesn't change much, since in most cases the
packet is pretty full already so the padding done from the server is
minimal
---
This fixes a `MUST` violation (padding of server Initial packets) in the later draft versions, which …
=> coalesce outgoing packets

src/h3/mod.rs
Spotted while reviewing #765. 
Fixing this doesn't seem to cause any difference in test outcomes but may as well get it right.
=> h3: ensure dgram test helper uses role consistently

src/lib.rs, src/stream.rs
When a STOP_SENDING frame is received, if the corresponding stream is
already flushable we end up sending a 0-length STREAM frame with
fin=true immediately after the RESET_STREAM frame.
This is because while the buffered data is dropped when receiving the
STOP_SENDING, the stream is still in the flushable queue, and since no
data is buffered anymore, and the final size is known, the 0-length
STREAM frame is generated.
It's not currently easy to remove a specific stream from the flushable
queue due to the priority mechanism, so instead check if the stream is
stopped before trying to generate a STREAM frame.
=> avoid sending STREAM frames for stopped streams

src/h3/mod.rs
`0` is not a valid HTTP/3 error code, as No_ERROR corresponds to 0x100.
=> h3: use H3_NO_ERROR when shutting down unknown stream

src/lib.rs, src/stream.rs
A couple of fixes related to `stream_shutdown(Read)`.
=> Read stream shutdown fixes

src/h3/mod.rs, src/h3/stream.rs
After 5d39b5b1, we started collecting GREASE and other unknown type
streams correctly. However the way these were handled meant that we were
issuing Finished events regardless of the stream's type.
This makes FInished events be emitted only for request and push streams.
=> h3: only emit Finished events for request/push streams

examples/http3-client.c, examples/http3-client.rs, extras/nginx/README.md, extras/nginx/nginx-1.16.patch, include/quiche.h, src/ffi.rs, src/h3/ffi.rs, src/h3/mod.rs, src/h3/stream.rs, src/lib.rs, tools/apps/src/common.rs
Currently all HTTP/3 events are edge-triggered with the exception of
`Data` and `Datagram`, which get reported until the underlying data is
read by the application.
Besides being inconsistent, this is problematic because an application
can't decide to ignore those events in particular circumstances. For
example an application might want to apply backpressure to a particular
stream on which the Data event has been reported, but still process
other streams normally.
In the current implementation, a Data event for the "blocked" stream
would keep being fired until the application decides to actually read
the body data from that stream, which means that, if the application is
not ready to do that yet, no other events are reported, thus blocking
all other streams as well.
This changes those …
=> h3: make all events edge-triggered

include/quiche.h, src/ffi.rs, src/lib.rs
This can help for example when implementing segmentation offloading, to
know what the negotiated MTU is.
=> expose the max UDP payload size to applications

src/lib.rs, src/stream.rs
When a stream enters the draining state, besides not storing the
received data, it also stops updating its internal state, like the
stream's maximum offset, which affects the flow control calculation.
For example, if the stream is reset by the peer, this could trigger a
spurious flow control violation error, causing the connection to be
terminated.
=> stream: process incoming data when draining

src/recovery/cubic.rs, src/recovery/mod.rs, src/recovery/reno.rs
Implementing detecting spurious congestion events and restore to the previous CC state in CUBIC.
Current algorithm is as follows:
- When the congestion event happen, save the current CUBIC state before cwnd reduction.
- When the current recovery episode ends and the new lost count is smaller than RESTORE_COUNT_THREHOLD (unit of a packet), restore from the saved prior state. It means that this can be a random loss, not a congestion loss which usually come with many multiple losses.
=> cc: CUBIC - detecting spurious congestion events

src/lib.rs
Follow-up to 8736dbec. There's not much point to this structure if the
fields cannot be accessed.
=> make ConnectionError fields public

src/h3/mod.rs, src/h3/stream.rs
If an application keeps calling `recv_body()` on a stream that is
already finished, we end up adding it to the finished streams queue
multiple times.
The application shouldn't really do this, but do the sane thing if it
does happen.
=> h3: avoid marking a stream as finished multiple times

src/h3/mod.rs
Previously, if `send_goaway()` was called on a client connection, it
would return without emitting a frame. This was justified by the lack
of server push support in quiche. However, it also prevented client
GOAWAY when the endpoints didn't use push, which is unfortunate.
This change simply always populates the emitted GOAWAY frame with an
ID of 0, which is valid and consistent with our server push support
status.
=> h3: emit GOAWAY from client

src/lib.rs
When a pre-v1 client connects to a v1-enabled server, we need to
re-enable the legacy TLS extension codepoint on the server-side due to
the downgrade.
=> disable the TLS extension for QUIC v1 on the server when downgrading

src/lib.rs, src/tls.rs, tools/apps/src/args.rs, tools/apps/src/client.rs, tools/qns/run_endpoint.sh
This makes it possible to support session resumption on a client and is
a pre-requisite for supporting sending 0-RTT data.
=> support exporting and importing TLS sessions

tools/qns/run_endpoint.sh
In 60f66cac, run_quiche_client_tests was changed to do "case $1", like
check_testcase, but the testcase was not passed to the function.
Also remove unused variable.
=> qns: fix client test run

src/lib.rs, src/tls.rs, tools/apps/src/args.rs, tools/apps/src/bin/quiche-server.rs, tools/apps/src/client.rs, tools/qns/run_endpoint.sh
This adds support for clients to generate 0-RTT packets. Currently only
STREAM and DATAGRAM frames are allowed, though this is somewhat stricter
than what is allowed in theory.
This requies exporting the peer's transport parameters as part of the
TLS session, so that they can be restored on resumption.
This also changes how epoch/packet type is picked when creating a new
packet. Packet types offer more granularity (e.g. Short vs. ZeroRTT), so
it's better to pick the type first and then derive the epoch, rather
than the other way around.
Closes #683.
---
It seems to work reasonably fine so far, but probably needs more interop testing.
=> support for sending 0-RTT packets on the client

tools/http3_test/README.md, tools/http3_test/src/runner.rs, tools/http3_test/tests/httpbin_tests.rs
Add EARLY_DATA and SESSION_FILE for testing 0-rtt connection
resumption on http3_test.
Based on #914
=> http3_test: add 0-rtt connection resumption

src/recovery/cubic.rs
Update based on https://github.com/NTAP/rfc8312bis/pull/35
- remove w_last_max
- update the logic of fast convergence
- fix the bug where fast convergence is not applied
=> cc: CUBIC - rfc8312bis fast convergence

src/lib.rs
This check is currently done in `Connection::send()` as well, but when
coalescing multiple packets, if one causes the connection to move to
draining (e.g. because a CONNECTION_CLOSE was sent), we should stop
trying to write additional coalesced packets.
=> stop sending packets if draining

include/quiche.h, src/ffi.rs
Motivation:
We should expose functions to access the source and destination ids via the c API as well
Modifications:
Expose functions in the C API
Result:
Be able to access the ids of a connection
=> Expose connection source / destination id via c API

src/frame.rs, src/stream.rs
Currently, when writing stream data, `RangeBuf` objects are allocated
with a fixed capacity, and if the buffer is not immediately filled, the
next stream write will re-use it.
This was originally implemented to try to reduce memory fragmentation of
stream data, and, in order to be able to maintain the `Send` and `Sync`
traits implementation, the `RangeBuf` data buffer was wrapped in an
`RWlock`, in order to implement thread-safe interior mutability.
However due to the fact that the locking falls within 2 hot code paths
(stream data writing, and STREAM frame creation) it heavuily affects
throughput.
In retrospect, the benefit of reduced memory fragmentation does not seem
to justify the performance penalty, so this undoes the consistent
allocation change to remove the need for the lock. …
=> stream: undo consistent RabgeBuf allocation on send

examples/client.c, examples/client.rs, examples/http3-client.c, examples/http3-client.rs, examples/http3-server.c, examples/http3-server.rs, examples/server.c, examples/server.rs, extras/nginx/nginx-1.16.patch, fuzz/src/packet_recv_client.rs, fuzz/src/packet_recv_server.rs, include/quiche.h, src/ffi.rs, src/h3/mod.rs, src/lib.rs, tools/apps/src/bin/quiche-server.rs, tools/apps/src/client.rs, tools/apps/src/common.rs, tools/http3_test/src/runner.rs
Currently quiche does not hold any information about the network path of
a QUIC connection (such as the address of the peer), and the application
is responsible for maintaining such information.
This means that in case of a network migration, the application is
responsible for detecting the change and switching over to new path,
however there is currently no way for an application to actually
validate a new path, as required by the QUIC spec.
Adding an ad-hoc API to only expose path validation to applications
would likely be very cumbersome, due to the synchronization needed
between an application and quiche on the state of the current path, and
any other path being probed.
Instead, this change makes quiche be aware of the network path being
used.
The application needs to communicate the …
=> network path awareness

include/quiche.h, src/ffi.rs, src/lib.rs, src/recovery/cubic.rs, src/recovery/mod.rs, src/recovery/reno.rs
Currently pacing is enabled for Cubic and Reno, since BBR is under development.
=> Pacing: Pacing of egress QUIC packets

src/recovery/cubic.rs, src/recovery/hystart.rs, src/recovery/mod.rs, src/recovery/reno.rs
RFC3465 ABC_L constant (2) is to prevent an ACK from
growing cwnd too fast for TCP ACK. However in QUIC
recovery we process each ack'ed packet one by one in
on_packet_acked(), there is no case where 2 or more
packets are acked in on_packet_acked() hook.
Also current logic limits growing cwnd more than 2 MSS
for ACK packet containing more than 2 ACK packets,
cwnd can grow too conservative in case that an ACK range
contains many packets. For example the receiver may
ack multiple packets in a single ACK frame when it processed
multiple packets at once.
This PR partially reverts #737.
=> recovery: remove ABC_L constant and its logic

examples/client.c, examples/client.rs, examples/http3-client.c, examples/http3-client.rs, tools/apps/src/client.rs, tools/http3_test/src/runner.rs
Since #898 the client uses sendto() and recvfrom(), the socket need to be
connectionless.
Before:
```
[2021-05-26T21:58:46.109658000Z INFO  quiche_apps::client] connecting to 172.16.127.145:8443 from 172.16.127.1:52740 with scid 5e6d2dac34510af3a071466617d450357c844777
thread 'main' panicked at 'send() failed: Os { code: 56, kind: Other, message: "Socket is already connected" }', src/bin/quiche-client.rs:48:39
```
After:
```
[2021-05-26T22:04:21.549094000Z INFO  quiche_apps::client] connecting to 172.16.127.145:8443 from 0.0.0.0:64418 with scid a3ff695193c37da3945c83c8645e585edf7eca89
[2021-05-26T22:04:24.537648000Z INFO  quiche_apps::common] 1/1 response(s) received in 2.986774919s, closing...
[2021-05-26T22:04:24.576217000Z INFO  quiche_apps::client] connection closed, recv=80512 …
```
=> quiche-client: connectionless udp socket

src/recovery/cubic.rs
cwnd_inc is used for storing cwnd increments during congestion
avoidance. When cwnd_inc >= MSS we increase cwnd by 1 MSS.
Currently we clear cwnd_inc when cwnd is updated but this will
lead to slightly slower growth because the residual part is gone.
=> cubic: fix cwnd growth during congestion avoidance

src/lib.rs
Previously, quiche would always prefer sending pending DATAGRAM frames
over STREAM frames. Depending on the size of DATAGRAMs in relation to
QUIC packet sizes the available space in packets for STREAM frames
can end up being small. Similarly, sometimes STREAM frames may only get
sent when the congestion window was smaller than the next DATAGRAM.
This commit introduces a preference toggle into the quiche sending
logic. This gives equal opportunity to send full-sized DATAGRAM or
STREAM frames between calls to `send()`. In cases where there is no
pending data of one type, quiche will just fallback to the other.
=> lib: alternate DATAGRAM and STREAM frame packing

examples/http3-client.c, examples/http3-client.rs, examples/http3-server.c, examples/http3-server.rs, extras/nginx/nginx-1.16.patch, include/quiche.h, src/h3/ffi.rs, src/h3/mod.rs, src/lib.rs, src/stream.rs, tools/apps/src/common.rs, tools/http3_test/src/runner.rs
When a RESET_STREAM frame is received, unless the stream was already
readable for other reason, the application wouldn't know about it.
For example, if one peer sent STREAM frames without setting the fin
flag, then sent a RESET_STREAM frame completing the stream (even without
an error), the other peer would correctly close the receive-side of the
stream, but not notify the application.
This would prevent, for example, issuing HTTP/3 events to the application.
This change causes the stream to be marked as readable when a
RESET_STREAM frame is received, as if a STREAM frame with fin=true was
received. In addition, a `StreamReset` error will be returned by the
`stream_recv()` method when called by the application.
This also changes the behaviour in case a RESET_STREAM frame is
received, but …
=> properly handle incoming RESET_STREAM frames

src/lib.rs
Continuing from #716, increase ack_delay_exponent not to
change the packet size depending on ack delay, when
the test runs on slower environment - such as quiche_multiarch
(running on docker + emulator).
=> test: fix flappy tests on slow machine

include/quiche.h, src/ffi.rs, src/lib.rs, src/recovery/mod.rs
1. Sent bytes.
2. Received bytes.
3. Lost bytes.
4. Retransmitted bytes.
5. Retransmitted packets -> packets with transmitted frames.
6. MTU -> currently using max datagram size configured
=> Add transport byte counters.

src/recovery/cubic.rs, src/recovery/mod.rs, src/recovery/prr.rs
Implmenting RFC6937 (Proportional Rate Reduction for TCP).
Currently when we go into the recovery, retransmiting
lost packet will wait until bytes_in_flight < cwnd. This
is described as "half window of silence" in RFC6937 because
it took a half rtt to get ACK to open a space for transmission.
PRR tries to send such retransmissions (not limited to new or
retransmitted packet though) more evenly at the beginning of
the recovery, does 'soft pacing' for retransmissions for stable
and fast recovery.
Here is some differences from TCP algorithm described in the RFC.
- pipe: RFC6675 pipe definition is more close to QUIC's
bytes-in-flight since it includes retransmit already.
So here bytes_in_flight is used instead of pipe.
- RecoverFS: use bytes_in_flight value in the beginning of
the recovery.
- …
=> recovery: RFC6937 Proportional Rate Reduction

tools/apps/src/bin/quiche-server.rs, tools/apps/src/common.rs
Similar to #684, but this is only for quiche-server in apps.
Should be able to help stable rtt and cwnd for high speed transfer.
=> apps: implementing limiting send burst

src/lib.rs, tools/qlog/src/lib.rs
Previously, the `add_event()` method populated the qlog event_time
field by calling `std::time::Instant::elapsed()`, which causes an in
direct call for `std::time::Instand::now()`. This incurs additional
system calls that are wasteful, especially if events are logged in
rapid succession or the time is available elsewhere.
This change introduces the `add_event_with_instant()` method that
allows callers to provide their own Instant that they wish to use
when logging an event.
=> qlog: add means to provide external event time

src/lib.rs
Motivation:
The documention of stream_send(...) states that Err(Error::Done) is returned if no bytes were send. This is not always the case and Ok(0) might be returned.
Modifications:
Return Err(Error::Done) if tx_cap is 0.
Result:
Return value matches the documentation.
=> stream_send(...) should return Err(Error::Done) if no bytes are send

src/lib.rs
This ends up being rendered as "[Ok(0)]".
=> remove spurious link mark-up in docs

examples/Makefile, src/recovery/prr.rs
In addition to #976, fix additional divide by zero case.
Also test cases for all overflow added, including #973.
=> recovery: fix more PRR calculation issues

extras/nginx/nginx-1.16.patch
This exports a couple of fixes from the internal repo:
* Make write event ready before sending packets.
* Silence "zero size buf in chain writer" warning log.
=> nginx: sync patch

src/lib.rs, tools/qlog/src/lib.rs
The qlog crate is primarily based on the qlog draft 01 specification.
This allowed configuration of time units used for logging, either in
milliseconds or microseconds. The qlog crate only supports relative time
logging and defaults to millisecond units in integer form.
The unfortunate side effect of millisecond units is that events occurring
close together get aliased into the same millisecond. Tools like qvis
can then misrepresent things.
In qlog draft 02, the time unit handling changed. It is no longer
configurable, instead it is always milliseconds, represented as floating
point. Previously, an event at relative time 100085 microseconds, would
be logged as "100". With this change it is logged as "100.085".
This change updates the time unit handling to align with draft 02. It
removes …
=> qlog: align time units to qlog draft 02 style

src/lib.rs
In case multiple packets are sent with the HANDSHAKE_DONE frame (e.g.
due to probe timeouts), but only one gets acked, we would keep resending
the frame until all of the them would get acked.
The server needs only one ack, so avoid retransmitting the frame if it
got acked at least once.
=> avoid sending HANDSHAKE_DONE if already acked

src/lib.rs, src/tls.rs
The requirements for the Sync trait are somewhat confusing [0], but it
appears that the reason why it is not automatically implemented for
pointers is aliasing (that is, the data referenced by the pointer may be
aliased). In addition, non-thread-safe "interior mutable" types
(including pointers) also shouldn't be Sync (see e.g. Rc vs. Arc).
[0] https://doc.rust-lang.org/std/marker/trait.Sync.html
In the case of tls::Context and tls::Handshake, there is no aliasing,
but they do have "accidental interior mutability", where a non-mutable
reference is used to get a mutable pointer in a number of methods.
This means that explicitly implementing both Send and Sync for
tls::Context and tls::Handshake _should_ be safe, after the "accidental
interior mutability" problem mentioned above is fixed. …
=> tls: try to sanitize use of raw pointers for Context and Handshake

src/lib.rs
Since servers cannot send 0-RTT packets, `is_in_early_data()` will be
called unnecessarily. While it's not a huge cost, avoiding it is pretty
simple and as a side-effect, it also reduces noise in flamegraphs.
=> avoid calling is_in_early_data() unnecessarily

src/recovery/mod.rs
This implements adaptive reordering threshold as suggested in:
https://quicwg.org/base-drafts/draft-ietf-quic-recovery.html#section-5.1.1.
The algorithm is similar to what Chrome uses as well.
I did a quick test on my laptop with `netem delay 10ms 1ms 10%` and this seems to improve things a fair amount:
Before:
```
finished in 31.92s, 0.03 req/s, 321.44KB/s
requests: 1 total, 1 started, 1 done, 1 succeeded, 0 failed, 0 errored, 0 timeout
status codes: 1 2xx, 0 3xx, 0 4xx, 0 5xx
traffic: 10.02MB (10506459) total, 97B (97) headers (space savings 47.57%), 10.00MB (10485760) data
```
After:
```
finished in 1.85s, 0.54 req/s, 5.40MB/s
requests: 1 total, 1 started, 1 done, 1 succeeded, 0 failed, 0 errored, 0 timeout
status codes: 1 2xx, 0 3xx, 0 4xx, 0 5xx
traffic: 10.00MB (10488607) total, 97B …
```
=> Adaptive reordering thresholds

src/stream.rs
Only call buf.consume() once and don't check for empty buffers as it is
already done before reaching this point.
=> stream: slightly simplify SendBuf::emit() logic

src/frame.rs, src/lib.rs, src/recovery/mod.rs, tools/qlog/src/event.rs, tools/qlog/src/lib.rs
In qlog-01, many of the fields that carry numbers were basically defined
as string in order to accommodate perceived problems with JSON and 64-bit
numbers. QUIC is rife with potentially 64-bit numbers but in practice,
many of these fields will contain values that are perfectly legal for
the duration of a connection. In later versions of qlog, many of the
fields have been changed to actual number types.
This change updates many qlog fields and API parameters to be closer the
qlog specifications today by using numbers e.g. stream IDs are now u64
rather than String . There general several benefits to this, we no
longer need to create owned Strings to pass around, we don't waste
effort creating strings that are immediately serialized again by the
streaming serializer, we save space in the …
=> qlog: convert numbers to actual numbers

src/lib.rs, src/recovery/mod.rs
Previously, when the qlog feature was enabled, quiche would log all
recovery metrics (that it cares to log) any time there was a recovery
event. This is legal but increases duplication in the logs.
With this change, we make the event emission smarter by only generating
them if at least one of the event data fields has changed. In testing,
the file size is reduced by up to 25%, the qvis congestion view
continues to work just fine, and the sequence diagram has improved
readability,
builds on https://github.com/cloudflare/quiche/pull/999 so needs to come after it
=> recovery: only log qlog metrics when fields change

extras/nginx/nginx-1.16.patch
When finalizing an HTTP/3 connection, we iterate over all open streams
so they can be closed properly.
For each iteration, the stream at the root of the streams tree is picked
and woken up. This assumes that the stream actually gets closed, so that
in the next iteration a different stream is picked, but this is not
necessarily true, as a stream could be blocked and be unable to actually
write, say, an HTTP error response.
This means that we might end up in a n infinite loop, where a stream is
blocked, so it can't be closed, but it keeps getting picked for each
loop iteration.
Instead, properly walk the tree, so that each stream is picked only once
during the loop.
=> nginx: properly iterate over open HTTP/3 streams

src/dgram.rs, src/h3/mod.rs, src/lib.rs
These can be used by applications to avoid copying DATAGRAM data, and
instead provide or receive an owned Vec<u8> directly.
This also prevents an intermediate copy when writing HTTP/3 DATAGRAMs,
as well as when receiving DATAGRAM frames.
=> add DATAGRAM APIs to work with Vec<u8> directly

src/crypto.rs, src/lib.rs, src/packet.rs
This replaces the use of ring::aead with the BoringCrypto AEAD API.
While the ring AEAD API is nicer and less verbose, BoringCrypto's
`EVP_AEAD_CTX_seal_scatter()` allows passing plaintext data in two
separate buffers ("in" and "extra_in"), which will enable later
optimizations to avoid copying plaintext stream data in the output
packet buffer before encryption.
Other crypto operations like HKDF and QUIC header protection are still
implemented using ring, though this might change in the future (if
anything, because building and using 2 different crypto libraries at the
same time is kind of stupid).
=> crypto: use BoringCrypto for AEAD operations

src/lib.rs
IIRC this method was changed before merging, so this sentence doesn't
make sense anymore, as a single value is returned rather than a tuple.
=> remove outdated sentence in peer_error() docs

src/frame.rs, src/lib.rs
Similarly to how STREAM and CRYPTO frames are written to the output
packet buffer, write the DATAGRAM frame header and data into the output
packet buffer directly.
This doesn't really make much of a difference in terms of performance,
but it enables a later change to use the crypto scatter seal API to
avoid unnecessary copies of data.
=> write DATAGRAM frame data directly into the output packet

examples/client.rs, examples/http3-server.rs, examples/server.rs, src/crypto.rs, src/frame.rs, src/h3/mod.rs, src/lib.rs, src/packet.rs, src/recovery/mod.rs, src/tls.rs, tools/apps/src/bin/quiche-server.rs, tools/apps/src/client.rs, tools/apps/src/common.rs
There's a new Rust stable release, so it's time again to fix all the new clippy warnings.
=> fix needless_borrow clippy warnings

src/lib.rs, src/tls.rs
We currently support specifying a server name (via SNI) on the client
side, but there is no API for the server to read it, so add one.
=> add method to return the server name requested by the client

extras/nginx/nginx-1.16.patch, include/quiche.h, src/h3/ffi.rs, src/h3/frame.rs, src/h3/mod.rs, src/h3/stream.rs
The name of this setting was changed in draft -28 but we never went and
updated it. Since the setting is exposed externally in the API, it could
confuse people that come to implement the more recent drafts. This
change fixes things.
Note that this does not update the qlog crate, since that spec is
lagging behind too; see: https://github.com/quicwg/qlog/issues/175
=> h3: rename max_header_list to max_field_section

src/lib.rs, src/stream.rs
Instead of copying application data (stream / DATAGRAM) into the output
packet buffer, and then encrypting that in-place, we can use the seal
scatter API exposed by BoringCrypto to avoid the additional data copy,
by passing the data buffer directly to the crypto API.
The limitation is that the "scattered" payload buffer must be at the end
of the packet, so no additional frames can be queued after that. In the
STREAM case this is not a problem as only a single STREAM frame is
queued anyway, but in the DATAGRAM case we need to avoid pushing more
than one. In addition, PADDING frames can't be added either.
=> zero-copy emit scatter API

Dockerfile, README.md, src/recovery/cubic.rs, src/recovery/hystart.rs, src/recovery/reno.rs
- Implement hystart++ draft 03 for cubic and reno
- A new mode Conservative Slow Start (CSS) introduced instead of
Limited Slow Start (LSS). The difference is CSS is still under
slow start (cwnd < ssthresh)
- Add hystart.reset() hook to be called in collapse_cwnd() CC
hook to start in a clean state.
- Update hystart test in cubic and test 2 mode transitions:
SS -> CSS -> SS and SS -> CSS -> CA.
- For various rtt, simply use Duration.
- Bump minimum rust version to 1.53 due to the use of Duration::MAX.
=> recovery: hystart++ draft 03

extras/nginx/nginx-1.16.patch
To fix the following nginx build error:
```
/usr/bin/ld: ../target/debug/libquiche.a(std-008055cc7d873802.std.cf1c8f7e-cgu.0.rcgu.o): in function `std::f32::<impl f32>::lerp':
/rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b//library/std/src/f32.rs:914: undefined reference to `fmaf'
/usr/bin/ld: ../target/debug/libquiche.a(std-008055cc7d873802.std.cf1c8f7e-cgu.0.rcgu.o): in function `std::f64::<impl f64>::lerp':
/rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b//library/std/src/f64.rs:916: undefined reference to `fma'
collect2: error: ld returned 1 exit status
```
It seems like related with recent rust (1.55) release.
=> ci: fix nginx build failure

tools/http3_test/tests/httpbin_tests.rs
They make builds with latest Rust nightly sad.
=> http3_test: remove unused fields

src/lib.rs, src/stream.rs
Currently the send-side flow control allowance is enforced and reduced
whenever stream data is buffered in the corresponding stream's send
buffer (i.e. when the application calls `stream_send()`). This is to
limit the amount of buffered data to what the connection can actually
take and avoid over-buffering.
However whenever a stream is reset (e.g. `STOP_SENDING` is received, or
`stream_shutdown()` is called), the stream's final size will include all
data that was previously buffered, even if not all of it was actually
sent on the wire yet.
To aovid that, we can make the final size be the offset of the first
unsent byte, and then "claw back" the remaining data from the flow
control allowance when a stream is reset.
=> avoid counting reset streams' unsent data towards flow control limit

src/frame.rs, src/lib.rs
This change adds support for parsing received ACK frames of type 0x03 that
include ECN Counts. These are not used by quiche for anything, so are effectively
discarded. No support for sending ECN Counts is added to quiche with this commit.
Fixes #1051
=> lib: add parsing support for ACKs with ECN counts

src/recovery/mod.rs
From RFC9002, section 7.7:
Using a value for N that is small, but at least 1 (for example,
1.25) ensures that variations in RTT do not result in
underutilization of the congestion window.
The 1.25 value is taken directly from that, but we might want to do some tweaking.
Also includes a small clean-up.
=> Pacing tweaks

Cargo.toml, tools/qlog/Cargo.toml, tools/qlog/README.md, tools/qlog/src/lib.rs
The qlog README.md was stale, so I pulled over the equivalent docs from lib.rs. I also updated them both to use QUIC v1 now that it's an RFC.
=> qlog: update docs and bump to 0.5.0

src/h3/mod.rs, src/h3/stream.rs
quiche applies a limit to the size of some HTTP/3 frames. Previously, if the
limit was exceeded we emitted a CONNECTION_CLOSE with H3_INTERNAL_ERROR code.
Instead use H3_EXCESSIVE_LOAD code.
=> h3: when frames are too large, generate H3_EXCESSIVE_LOAD

include/quiche.h
The quiche.h header files use struct sockaddr extensively, meaning that
they rely on having sys/socket.h types defined. This include is missing
in the quiche.h header file, sadly.
This patch adds that include, so that the quiche.h header file stands
alone.
=> Add sys/socket.h to include list

include/quiche.h, src/ffi.rs, src/flowcontrol.rs, src/lib.rs, src/packet.rs, src/stream.rs, tools/apps/src/args.rs, tools/apps/src/bin/quiche-server.rs, tools/apps/src/client.rs
This PR reimplments #529 which tried to implement a QUIC flow
control specified in https://docs.google.com/document/d/1F2YfdDXKpy20WVKJueEf4abn_LVZHhMUMS5gX6Pgjl4/edit?usp=sharing
It's basically window-based approach where window size is determined
by current receiving speed.
Since lot of things changed from #529, I tried to minimize the
changes in the existing code. Most of the logic is in src/flowcontrol.rs
and it will replace max_data and max_data_next logic.
=> lib: window-based flow control

examples/http3-client.c, include/quiche.h, src/h3/ffi.rs, src/h3/frame.rs, src/h3/mod.rs, src/h3/stream.rs
SETTINGS frames can contain parameters with unknown or reserved identifiers.
quiche has no direct usage for these parameters and previously discarded them.
With this change we store all received parameters in the order that they were
sent, and add a new `peer_settings_raw()` to access them,
=> h3: store all received SETTINGS parameters and expose them

src/frame.rs, tools/qlog/src/events/mod.rs, tools/qlog/src/events/quic.rs, tools/qlog/src/events/security.rs, tools/qlog/src/lib.rs, tools/qlog/src/streamer.rs
Noticed during some interop testing, some of our event definition fields were a bit wrong compared to the spec. I've fixed them up here as individual commits but we can squash before merging as there's nothing really complicated going on.
=> qlog event nits

src/lib.rs, src/recovery/cubic.rs, src/recovery/mod.rs, src/recovery/reno.rs
on_init() congestion control hook can be used for a custom
initialization of the congestion control states.
=> cc: add on_init() hook

.github/workflows/stable.yml, examples/http3-client.c
Fix a build error (not caught in linux) and add C example build
to macOS X CI.
=> examples: fix MacOS X C examples and add to CI

src/recovery/cubic.rs, src/recovery/hystart.rs, src/recovery/mod.rs, src/recovery/reno.rs
For congestion control specific debug log, add debug_string()
hook to the congestion control operations.
=> cc: debug info

src/lib.rs
I guess 'unirectional' is just a typo for 'unidirectional,' but let me know if it's not.  (Honestly, I'm a beginner of Rust/QUIC and have little understanding of the code itself.)
=> Fix typo *unidirectional

src/frame.rs, src/lib.rs
Path Challenge/Response data is exactly 8 bytes. Stateless Reset Token is exactly 16 bytes. If we know the sizes in advance, there's no reason for the dynamic allocation.
=> prefer arrays for small fixed-size fields

.github/workflows/stable.yml, quiche/src/frame.rs, quiche/src/h3/ffi.rs, quiche/src/h3/mod.rs, quiche/src/h3/qpack/huffman/table.rs, quiche/src/lib.rs, quiche/src/octets.rs, quiche/src/ranges.rs, quiche/src/recovery/mod.rs
Many of the warnings that we explicitly allow have been disabled by
default. In addition, we weren't running clippy with the "ffi" and
"qlog" features enabled.
=> clean-up clippy warnings

quiche/src/build.rs
Follow-up to bbe6e2ab, which changed the target dir.
=> build: fix pkg-config target dir

quiche/src/h3/mod.rs, quiche/src/lib.rs
Fixes the problem discussed in issue #1095. 
Now, `stream_send` returns `Ok(0)` only when an empty fin was submitted to the method, accordingly to the spec.
I had to update the test suite a bit as well as the `send_request()` function of h3.
=> ensure stream_send returns Ok(0) only when an empty FIN was submitted

quiche/src/recovery/cubic.rs
The original change seems to be causing some connection timeouts. Don't
have time to debug it right now, so just revert for now.
This reverts commit f6b3d0f55967300845b7bcfcdd150743aed3f7fb.
=> Revert "cubic: limit cwnd growth based on max bytes-in-flight"

README.md
Link was off by one folder. Current link was dead. This one works I believe.
=> Fix thin C API Link

quiche/include/quiche.h, quiche/src/ffi.rs
While we figure out a better way to implement these, we should remove
them so people don't accidentally use them. See  issue #1127 for more
details.
Fixes #1127.
=> ffi: remove quiche_conn_session() and quiche_conn_peer_cert() for now

apps/src/common.rs, qlog/src/lib.rs, qlog/src/streamer.rs, quiche/src/lib.rs
Introduces the `QlogFileSeq` and `TraceSeq` types defined in draft-ietf-quic-qlog-main-schema-01, and changes the qlog version to `0.3`. Default the streaming serializer to JSON-SEQ format.
=> Add support for QLOG JSON-SEQ

README.md
Hello, 👋🏽 
I think the certificate paths in README haven't caught up with some refactors.
Best,
=> Modify the certificate path in README.md

.github/workflows/stable.yml
Since multi-arch build are done in `cross` docker container,
no need to install rust.
It will reduce `tool rustfmt is already installed...` warning and
save a little build time.
=> ci: reduce CI warning on quiche_multiarch

.github/workflows/stable.yml, quiche/src/build.rs
- Use an actual `target_os` for build script to handle macOS build option correctly
- Reduce iOS build warning.
=> ci: macOS and iOS fix

quiche/include/quiche.h, quiche/src/ffi.rs, quiche/src/lib.rs, quiche/src/tls.rs
There's a slight change to the Rust API as well, but I think this is better anyway (see commit message).
=> Restore FFI functions to return TLS session and peer cert

quiche/src/h3/stream.rs
When quiche processes HTTP/3 streams, in a particular state we reject
non-DATA frames that are larger than an internal limit and return an
error.
This change moves the limit check earlier, in order to avoid stream
information getting updated with inaccurate information being stored
within the library.
=> h3: exit stream state transition earlier on error

quiche/src/h3/mod.rs, quiche/src/stream.rs
This is a follow up to https://github.com/cloudflare/quiche/pull/996, which implements the alternative suggestion of using a locally-defined "no-op" hasher.
=> Use a simpler hasher for stream collections

quiche/src/crypto.rs, quiche/src/packet.rs
In `packet::decrypt_pkt()`, when `payload` is to small and
no space in `ciphertext`, it may cause overflow in
`max_out_len` in `crypto::open_with_u64_counter()`, can lead
a crash.
This can happen when the received packet payload is corrupted.
To fix it, an overflow check for `max_out_len` is added.
=> Check payload size before decryption

quiche/include/quiche.h, quiche/src/h3/mod.rs
An HTTP/3 operation might fail due to a transport-related reason. This
usually happens if a stream write can't occur because the peer stopped
it. This should be expected behaviour and not a critical error for
applications. In Rust, the quiche::h3::Error::TransportError
encapsulates the underlying QUIC error, so applications can match only
quiche::Error and swallow certain types. In contrast, the FFI interface
collapses all HTTP/3 transport-related errors into a single value,
preventing FFI-based applications from being able to also swallow.
This change exposes the encapsulated QUIC transport errors to the FFI by
applying a simple numerical shift to the QUIC error codes.
=> ffi: expose transport-related HTTP/3 errors

.github/workflows/stable.yml
Today I see `windows-latest` is updated to `windows-2022` and the
build start to fail on 32bit build. Until we figure it out, pin the version
to 2019.
=> ci: use windows-2019 for windows build

quiche/src/recovery/reno.rs
During congestion avoidance, when `bytes_acked_ca` is more
than cwnd, we increase cwnd by 1 mss. However currently
we increase cwnd first before updating `bytes_acked_ca`,
can cause overflow (`bytes_acked_ca` can be < 0).
Fixes #1168
=> reno: fix overflow

apps/src/bin/quiche-server.rs, quiche/include/quiche.h, quiche/src/ffi.rs, quiche/src/lib.rs, quiche/src/recovery/mod.rs
For higher performance sending multiple packets is a common
practice, such as sendmmsg() or linux sendmsg() GSO. To
help with that, send_quantum is added and it can be modified
in the congestion controller. It's a hint for the application,
it may or may not use the value for controlling the batch
size of packets.
For default value, initcwnd is used(RFC9002 section 7.7).
Also, conn.send_quantum() and C API (quiche_conn_send_quantum())
is provided for the application.
=> cc: add send_quantum API

quiche/src/lib.rs
Fix where `retrans_count` is not updated when there is a
retransmit of a stream data. Also add `stats.retrans` to
debug formatter for logging.
=> lib: fix retrans_count is not updated

quiche/src/lib.rs, quiche/src/stream.rs
NB: this reduces the frequency of blocked frames at the same offset from "every send()" to once. If we want a middle ground, like every N packets, that is feasible too.
When applications try to send stream data with `stream_send()`, the
number of bytes actually written might be less than supplied due to
insufficient stream or connection capacity. In these cases, quiche
internally marks the stream as blocked and, when `conn.send()` is next
called the mark causes a STREAM_DATA_BLOCKED frame to be emitted in a
new packet.
Previously, every call to `stream_send()` would cause the stream to be
marked and therefore generate a STREAM_DATA_BLOCKED frame. In cases,
where `conn.send()` is called frequently, the blocked frame might be the
only frame in the packet, which is wasteful.
This change …
=> lib: send STREAM_DATA_BLOCKED frames less often

quiche/src/recovery/mod.rs
Especially for ACK packet (or other packet with no pacing
condition) which has no payload size, it need to be
sent immediately. However if next scheduled time is already
in the future, sending ACK immediately can cause out-or-order
delivery and result in lost packet and retransmit.
To prevent such case, if `last_packet_scheduled_time` is
already in the future when no pacing used, don't update
the timestamp. Otherwise the current time(now) will be used.
=> pacing: no pacing can cause out-of-order

quiche/src/lib.rs, quiche/src/recovery/mod.rs
Since `recovery.last_packet_scheduled_time` always have a
default value (current timestamp), Having it `Option<Instant>`
type doesn't make sense much. No changes on public API.
=> pacing: get_packet_send_time() is no longer Option<>

quiche/src/recovery/cubic.rs, quiche/src/recovery/mod.rs, quiche/src/recovery/reno.rs
`lost_bytes` is the total payload size of lost packets
detected by an ACK. This can be used as a hint for the congestion
controller when needed.
=> cc: pass lost_bytes to congestion_event() hook

quiche/src/recovery/cubic.rs, quiche/src/recovery/mod.rs, quiche/src/recovery/reno.rs
Currently we have on_packet_acked() called by each ACK'ed data
packet and it will be called multiple times if an ACK range
contains many data packets. Sometimes there is a need to process
an ACK itself, not the all data packet ACK'ed this time.
To support it, on_packets_acked() hook is introduced in place
of on_packet_acked(). Only difference is passing a list of Acked
instead of each Acked and the hook need to process all packets
in the Acked list if needed, for example to get the total size
of ACK'ed payload.
reno and cubic is updated to use a new hook.
=> cc: on_packets_acked() hook

quiche/src/lib.rs
Previously `Stats.lost` is much higher than `Stats.retrans`.
It is because `retrans_count` increases when there is
some retransmitted bytes in the lost packet list, not counting per
retransmitted range.
Now it counts for each lost data frame. `lost` and `retrans`
may not match but in a simple case (e.g. lost 1 packet,
retransmit the same range) it will be same.
Before: `lost=2814 retrans=10`
```
[2022-03-04T09:55:16.694598762Z INFO  quiche_server] 6d66c30c86018d28a71aea8d1e6d4a9ae2d2d6d6 connection collected recv=446 sent=10845 lost=2814 retrans=10 rtt=52.978034ms cwnd=782252 peer_tps={ max_idle_timeout=30000, max_udp_payload_size=65527, initial_max_data=1073741823, initial_max_stream_data_bidi_local=67108863, initial_max_stream_data_bidi_remote=0, initial_max_stream_data_uni=67108863, …
```
=> lib: fix retrans_count again

quiche/src/lib.rs, quiche/src/recovery/cubic.rs, quiche/src/recovery/delivery_rate.rs, quiche/src/recovery/mod.rs, quiche/src/recovery/reno.rs
- Update delivery rate implementation to draft 01.
- Major rework on delivery rate estimation.
- `estimate()` is removed - it will be done in `generate_rate_sample()` after calling `update_rate_sample()` in each ack, as specified in the draft.
- Rate estimation is only checked in Application packet number space.
- Expose some functions for later use, such as
`recovery.delivery_rate.app_limited()` returns `C.app_limited != 0`,
`recovery.delivery_rate._delivered()` returns `rs.delivered`,
`recovery.delivery_rate.sample_is_app_limited()` returns `rs.is_app_limited`.
- `C.app_limited`: now we use the packet number instead of the byte
range. `largest_acked` and `last_sent_packet` is added for
tracking packet number. This is used for rate sample and
separately from `recovery.app_limited`.
- …
=> delivery rate estimation: draft 01

quiche/src/tls.rs
I ran into the following error while updating quiche a while back:
```
= note: /usr/bin/ld: target/debug/deps/libquiche-aebddac5b5b78042.rlib(quiche-aebddac5b5b78042.quiche.2dd0d882-cgu.7.rcgu.o): in function `new_session':
/home/builder/.cargo/git/checkouts/quiche-3a3206f14f25c564/a0088a9/quiche/src/tls.rs:1010: multiple definition of `new_session'; target/debug/deps/libquiche-7702398d4219d80f.rlib(quiche-7702398d4219d80f.quiche.1f33b6b3-cgu.5.rcgu.o):/home/builder/.cargo/git/checkouts/quiche-3a3206f14f25c564/df3fac0/src/tls.rs:1010: first defined here
```
That's not a particularly helpful error - the issue was that that we had two versions of quiche in
the dependency tree. This removes the unnecessary `no_mangle` attribute from `new_session` -
it's only ever used as a function pointer, …
=> Remove `no_mangle` from `new_session`

tools/http3_test/Cargo.toml, tools/http3_test/src/lib.rs, tools/http3_test/src/runner.rs, tools/http3_test/tests/httpbin_tests.rs
Previously, http3_test just ignored any Event::ResetStream occurrences
that might happen at the client.
With this change we mark reset streams as complete and store the
received error code in the request object, which tests can access for
post exchange asserts.
We use this new capability to add an optional `drip_delay_reset` test to
httpbin_tests, which can be enabled with the `test_resets` feature flag.
=> http3_test: add RESET_STREAM testing capability

quiche/src/recovery/cubic.rs, quiche/src/recovery/mod.rs
Due to pacing calcuation pkt.time_sent can be a future
time. For such case the time difference need to be zero.
=> recovery: time_sent can be in the future

quiche/src/recovery/cubic.rs, quiche/src/recovery/hystart.rs, quiche/src/recovery/reno.rs
Update based on [draft-ietf-tcpm-hystartplusplus-04](https://datatracker.ietf.org/doc/html/draft-ietf-tcpm-hystartplusplus-04).
Major change is removing `LOW_CWND`.
=> cc: hystart++ draft 04

quiche/Cargo.toml, quiche/examples/client.rs, quiche/examples/http3-client.rs, quiche/examples/http3-server.rs, quiche/examples/server.rs
This PR updates the version of `mio` used in the examples from v0.6 to v0.8 (latest minor version).
After this change, I've confirmed that the `http3-server` and` http3-client` examples work as before:
```console
$ cd quiche/
$ mkdir examples/root/
$ echo 'Hello World!' > examples/root/hello
// Server
$ cargo run --example http3-server
// Client (another shell)
$ cargo run --example http3-client https://127.0.0.1:4433/hello
Hello World!
```
Closes https://github.com/cloudflare/quiche/issues/1196
=> Use mio v0.8 in examples

.github/workflows/stable.yml, apps/src/common.rs
This also adds a commit to fix clippy in CI, as it was run only on the quiche package in the workspace (not apps, qlog, ...) because of the `--examples` option.
=> apps: fix single_char_pattern clippy warning

quiche/src/recovery/delivery_rate.rs
The RTT value in the test is 50ms.
=> style: fix typo of rtt value

qlog/src/lib.rs, qlog/src/streamer.rs, quiche/src/lib.rs
When we switched from JSON to JSON-SEQ, we modified the qlog serializer but didn't change it's behaviour wrt QUIC Packet events (rx/tx). The old behaviour TL;DR was:
1. qlog streamer user passes streamer a packet event
2. Streamer writes out packet header information. Then it locks itself into frame writing mode.
2. While locked, no other events cand be written.
3. qlog streamer user passes 0 or more frames.
4. qlog streamer user finalizes frames write. Streamer unlocks itself.
There are a few downsides to that approach:
* Locking prevents other events being written. For example, while processing frames, any additional events would be ignored by the serializer. While callers could buffer events themselves and log them later, it adds complication and we decided never to do that inside …
=> Make qlog packet event logging atomic

Dockerfile, README.md, apps/Cargo.toml, apps/src/common.rs, quiche/Cargo.toml, quiche/include/quiche.h, quiche/src/h3/ffi.rs, quiche/src/h3/mod.rs
h3: change priority type and add optional parser
The `quiche::h3::send_response_with_priority()` method allows
applications to specify a stream priority that is used by quiche's
stream prioritization.
Previously, the priority was passed as a String value that was expected
to contain Extensible Priority parameters in a serialized Structured
Fields Dictionary format; see
https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-priority-12#section-4.
Internally, the String was manually parsed to extract the "u" and "i"
parameters.
With this change, we convert the priority parameter from a String to a
new `quiche::h3::Priority` type that holds only the parameters we use
inside quiche. Applications are now required to handle Extensible
Priorities field values themselves. A `TryFrom<&[u8]>` …
=> h3: change priority type to byte array and use sfv

quiche/src/recovery/mod.rs
Currently `delivery_rate.on_packet_sent()` is called
only packets with in-flight data, which makes non
in-flight packets not updated with some metadata such
as `delivered`, etc. They have zero payload, but
need to be included in the rate estimation and
app_limited updates. Otherwise there can be unsync
between `Rate.last_sent_packet` and `Rate.latest_acked`
(`last_sent_packet` doesn't include non-ack-eliciting
packets but `latest_acked` does), which can mess up
`Rate.end_of_app_limited` tracking.
=> recovery: update delivery_rate on all packets

quiche/Cargo.toml
Not sure how it ever worked, but apparently we need to enable this.
=> enable 'ws2def' and 'ws2ipdef' features for winapi 

apps/src/common.rs, nginx/nginx-1.16.patch, quiche/examples/http3-client.c, quiche/examples/http3-client.rs, quiche/examples/http3-server.c, quiche/examples/http3-server.rs, quiche/include/quiche.h, quiche/src/h3/ffi.rs, quiche/src/h3/frame.rs, quiche/src/h3/mod.rs, quiche/src/h3/stream.rs, quiche/src/stream.rs, tools/http3_test/src/runner.rs
In one commit, introduce support for the two PRIORITY_UPDATE frames defined in
https://datatracker.ietf.org/doc/draft-ietf-httpbis-priority/12/.
In an additional commit, add a new Event::PriorityUpdate that is returned by the
`poll()` method. It only occurs on servers because only clients can send
PRIORITY_UPDATE frames.
Event:PriorityUpdate behaves like other edge-triggered events. The first
time a server receives a PRIORITY_UPDATE frame, the event is fired and
subsequent `poll()` will not generate more events. Application are
required to use the new `take_last_priority_update()` method to read all
received PRIORITY_UPDATE frames before the trigger is rearmed.
PRIORITY_UPDATE frames are sent on the control stream and include a
reference to request stream IDs. Due to reordering, it is …
=> h3: initial support for PRIORITY_UPDATE event

apps/src/common.rs
When we externalized the Priority field value parsing out of quiche,
we provided an optional utility function behind the the `sfv` feature.
In the apps, only the quiche-server requires the `sfv` feature. And we
started by assuming this is a default features. Unfortunately, if trying
to build the quiche-apps crate with `--no-default-features`,
quiche-server will then fail. This is especially annoying because people
have a good reason to build a slimmed-down quiche-client without all the
extra feautres.
This change modifies the quiche-server related code so that is can build
without the `sfv` feature. In this case, any Priority headers or
PRIORITY_UPDATE fields cannot be parsed. Instead, the default priority
is assumed.
=> apps: allow apps to be compiled without sfv feature

apps/src/common.rs, quiche/examples/http3-server.rs, quiche/examples/server.rs, quiche/src/ffi.rs, quiche/src/lib.rs, quiche/src/tls.rs
We currently need to access the quiche connection state during the TLS
handshake inside BoringSSL's various callbacks, and to do this, when a
Connection structure in created, we store a pointer to it in the SSL
state using the "ex data" API.
This however has the disadvantage that the pointer to the Connection
structure needs to be stable for the whole duration of the connection,
which means that Connection is wrapped in `Pin<Box<...>>` to avoid
applications accidentally moving the structure (thus invalidating the
pointer stored in ex_data).
But we don't actually need the ex data pointer during the whole
connection, in fact, we only need it when calling specific BoringSSL
APIs (e.g. `SSL_do_handshake()`) that in turn call the callbacks
registered by quiche, which means that we can actually …
=> only store &mut Connection in SSL ex_data when necessary

quiche/src/lib.rs, quiche/src/tls.rs
Follow-up to 3c7a597a3765995a5434eb08f838caba65112a6f.
Instead of storing a pointer to the whole `Connection` structure in the
TLS ex data, this change introduces a new `ExData` structure that
provides references to specific `Connection` fields needed in the TLS
callbacks.
This way we avoid having aliased mutable references to a `Connection`
when the BoringSSL callbacks are being executed (which is undefined
behaviour).
This needs to make `QUICHE_EX_DATA_INDEX` private again, since the
`ExData` structure is not public and can't be used by applications
(though nothing should be using this right now).
Fixes #1217.
=> avoid storing Connection pointer in TLS ex data

qlog/Cargo.toml, quiche/Cargo.toml
Changes include:
* Align qlog data model with draft-ietf-quic-qlog-quic-events-01 and
draft-ietf-quic-qlog-h3-events-01
* Make all qlog streamer serializer event writes atomic. QUIC packet
events no longer lock the serializer.
* New method `add_event_data_now()` added to the streaming serializer.
=> qlog: release 0.7

quiche/src/dgram.rs
Instead of allocating the max queue size upfront, allocate a smaller
size and allow the queue to grow to the maximum limit.
=> dgram: don't allocate full queue upfront

Dockerfile, README.md, quiche/Cargo.toml
rust_decimal need `edition2021` or 1.56. Bump the minimum version to 1.56.
=> Bump minimum rust version to 1.56

quiche/src/lib.rs, quiche/src/recovery/mod.rs, quiche/src/recovery/pacer.rs
Currently we update the timestamp for next packet
(`last_packet_scheduled_time`) for each packet based on
the current pacing rate, which can confuse the
rtt measurement because the recorded timestamp
and actual time sent can be different, especially when
the application sends in burst using send_quantum
and batches a group packets using GSO. In such case
rtt measured can be smaller than expected, or even 0
when the packet is not sent in a specified time.
Pacer provides the timestamp for next packet to be sent
based on the current send_quantum, pacing rate
and last updated time. It is reset when a valid packet is
received (including ACK and non-ACK packets) to
start a new burst.
Pacer is GSO-friendly, which means it will provides a same
timestamp for same sized (except last one) packets in …
=> recovery: add GSO-friendly pacer

.github/workflows/stable.yml, quiche/src/build.rs
- Read target_env from CARGO_TARGET_ vars.
- Override _WIN32_WINNT for building in MinGW.
- Fix linking order (-lssl -lcrypto) for MinGW linker.
- Add Windows + MinGW (x86_64-pc-windows-gnu)
to github workflow (MinGW + 32bit is still broken).
=> ci: fixing MinGW cross build, adding to CI

README.md, apps/src/args.rs, apps/src/bin/quiche-server.rs, apps/src/client.rs, apps/src/common.rs, fuzz/src/packet_recv_client.rs, fuzz/src/packet_recv_server.rs, nginx/nginx-1.16.patch, quiche/Cargo.toml, quiche/examples/client.c, quiche/examples/client.rs, quiche/examples/http3-client.c, quiche/examples/http3-client.rs, quiche/examples/http3-server.c, quiche/examples/http3-server.rs, quiche/examples/server.c, quiche/examples/server.rs, quiche/include/quiche.h, quiche/src/cid.rs, quiche/src/ffi.rs, quiche/src/frame.rs, quiche/src/h3/mod.rs, quiche/src/lib.rs, quiche/src/packet.rs, quiche/src/path.rs, quiche/src/recovery/cubic.rs, quiche/src/recovery/delivery_rate.rs, quiche/src/recovery/mod.rs, quiche/src/recovery/reno.rs, tools/http3_test/src/runner.rs
This PR provides provides connection migration support to quiche. It is composed of 3 incremental parts (the current 3 commits), starting from CID handling support, then path validation and finally connection migration. See the commit messages for further details about the changes introduced by each of them.
Note that while most of the changes are additive, there are a few breaking API changes introduced by the path validation support. Namely,
- `RecvInfo` now contains the `to` field, indicating the local host address on which the packet was received.
- `SendInfo` now contains the `from` field, indicating from which local host address the packet should be sent.
- Both `connect` and `accept` now takes an owned `ConnectionId` for the source CID and an additional `SocketAddr` parameter …
=> Connection migration support

Dockerfile, README.md, apps/src/args.rs, apps/src/bin/quiche-server.rs, apps/src/client.rs, apps/src/common.rs, fuzz/src/packet_recv_client.rs, fuzz/src/packet_recv_server.rs, quiche/Cargo.toml, quiche/examples/client.rs, quiche/examples/server.rs, quiche/src/ffi.rs, quiche/src/h3/mod.rs, quiche/src/lib.rs, quiche/src/tls.rs
This avoids requiring clients to do tedious and error-prone length calculations manually.
As a bonus, it avoids some unnecessary copies in quiche itself.
- Relax the lifetime constraints on `Octets`
- Rename `set_application_protos` to `set_application_protos_wire_format`
- Add a new `set_application_protos` function that takes a slice of byte strings
- Change `set_alpn` to take a slice of slices instead of a slice of `Vec`
- Changes apps to use the new API
=> Add a new API for setting application protocols from a slice of byte strings

quiche/src/path.rs
in a download test this reduces CPU time spent in `path_id_from_addrs` from 2.4% to 0.66%.
=> switch addrs_to_paths to BTreeMap

quiche/src/tls.rs
in a download test I noticed 3.29% of CPU time spent in do_handshake. After this change it is no longer showing up in perf output. I'm not familiar enough with BoringSSL QUIC APIs to say for certain this is correct usage.
=> process_post_handshake short-circuit

.github/workflows/stable.yml
Looks like mingw32 test executable crashes outside the
tests occasionally. Since windows tests are covered by
msvc builds, mingw32 is switched to build only, not
running test to prevent CI flakiness.
=> ci: disable mingw32 test

quiche/include/quiche.h
Otherwise, this clashes with projects that define their own `struct
Connection` or `struct Config`.
=> Change generic struct names to use quiche prefix in FFI

apps/src/common.rs, quiche/examples/http3-client.rs, quiche/examples/http3-server.rs, quiche/src/h3/mod.rs, tools/http3_test/src/runner.rs
Tweaks the debug format slightly so that they can be human-readable and a bit more grepable when values contain comma or quote.
Restores quiche-apps to something closer to the previous format, for legacy consumers
Previous:
```
got response headers [:status: 200, date: Mon, 11 Jul 2022 17:41:05 GMT, content-type: text/html, cf-cache-status: MISS, cf-apo-via: origin,miss, expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct", priority: u=3,i=?0, strict-transport-security: max-age=15552000; preload, lucas: pardue, server: cloudflare, cf-ray: 729353f2dab47545-LHR, alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400] on stream id 0
```
Now:
```
got response headers [(":status", "200"), ("date", "Tue, 12 Jul 2022 14:23:36 GMT"), ("content-type", …
```
=> h3: tweak impl Debug for headers to quote fields and escape embedded quotes

octets/src/lib.rs, qlog/src/events/connectivity.rs, qlog/src/events/h3.rs, qlog/src/events/mod.rs, qlog/src/events/qpack.rs, qlog/src/events/quic.rs, qlog/src/events/security.rs, qlog/src/lib.rs, qlog/src/streamer.rs, quiche/src/crypto.rs, quiche/src/frame.rs, quiche/src/h3/frame.rs, quiche/src/h3/mod.rs, quiche/src/h3/qpack/mod.rs, quiche/src/h3/stream.rs, quiche/src/lib.rs, quiche/src/packet.rs, quiche/src/path.rs, quiche/src/ranges.rs, quiche/src/recovery/mod.rs, tools/http3_test/src/lib.rs
Done using `cargo clippy --fix` against Rust 1.63.0
=> fix clippy lints

apps/src/client.rs
It expects an IP address and port, so let's just say that.
Fixes #1081
=> apps: display a friendlier message for bad --connect-to

quiche/Cargo.toml, quiche/src/ffi.rs
Due to https://github.com/rust-lang/rust/pull/78802 we can't simply copy
the binary representation of `SocketAddr` into `struct sockaddr*` and
vice versa, so implement proper conversions.
=> ffi: fix conversions between SocketAddr and strust sockaddr

quiche/src/dgram.rs
Many connections never use datagrams. It should be possible to advertise
datagram support, have a maximum queue length, but not pay the memory
penalty of never using it.
=> quic: dont preallocate dgram queue

quiche/src/path.rs
Many connections only have a single path, stop preallocating the
paths slab beyond that.
=> quic: lazy alloc paths slab

apps/src/bin/quiche-server.rs, apps/src/client.rs, quiche/examples/client.c, quiche/examples/http3-client.c, quiche/examples/http3-server.c, quiche/examples/server.c, quiche/include/quiche.h, quiche/src/ffi.rs, quiche/src/lib.rs
Instead of returning stats for all paths from the `stats()` method, add
a new method specific to path stats. This also allows us to return an
iterator for the path stats list, rather than have to collect the
iterator into a `Vec` (thus avoiding an allocation and also having to
iterate over all paths).
=> refactor per-path stats

quiche/include/quiche.h, quiche/src/minmax.rs, quiche/src/recovery/bbr/init.rs, quiche/src/recovery/bbr/mod.rs, quiche/src/recovery/bbr/pacing.rs, quiche/src/recovery/bbr/per_ack.rs, quiche/src/recovery/bbr/per_transmit.rs, quiche/src/recovery/delivery_rate.rs, quiche/src/recovery/mod.rs
Implementing `bbr` congestion control algorithm module. 
To try this module, you'll need `quiche-server` supports packet pacing only with `SO_TXTIME` feature in recent linux kernel (#1138). Also you'll need to configure `fq` in `tc qdisc` on the server for pacing to work properly.
Currently this PR is rebased on #1238 implementing GSO-friendly pacer. You can test with quiche-server using GSO in #1138 
TODOs
=> cc: BBR congestion control module

apps/src/bin/quiche-server.rs, apps/src/common.rs, apps/src/lib.rs, apps/src/sendto.rs
When GSO can be enabled (on a supported linux platform),
now quiche-server sends multiple packets using sendmsg()
with GSO.
For non-supported platforms, it should work same as before.
This PR is based on #1075 , so it will provide GSO + pacing(SO_TXTIME) combined.
If one of those feature is not detected, quiche-server won't use sendmsg().
=> apps: Linux GSO + pacing support for quiche-server

quiche/include/quiche.h
Motivation:
We should clarify that the token must be 16 bytes long as otherwise we might risk a crash
Modifications:
Add some more docs
Result:
Make it clear that the token must be 16 bytes
=> Clarify that token must be 16 bytes long

apps/src/bin/quiche-server.rs, apps/src/common.rs, quiche/examples/http3-client.rs, quiche/src/h3/mod.rs
When creating a new h3:Connection, quiche attempts to open
unidirectional streams. We care about the control stream
being opened and will return an Error if that can't happen.
In the case where the control stream failure occurred due to
stream ID limits, quiche returns a StreamLimit error to
indicate that.
In the case where the control stream failure occured due to
flow control being too small to send SETTINGS, we would
return a generic Error:Done, which is potentially confusing.
With this change, failures due to flow control are
more clearly marked as InternalError, since this is an implementation
choice. Trace logging has also been added to help better
communicate the control flow through quiche.
To mirror these changes, applications have been updated
with clearer error handling.
Fixes …
=> h3: return InternalError when flow control blocks control stream

quiche/src/lib.rs, quiche/src/stream.rs
When a stream is in draining state and stream data is received, the data will be dropped and the stream's state updated. However, because the application can't read the dropped data, it can never "consume" it freeing connection-level flow control credits for that data.
This change marks the received data as consumed automatically when a stream is in draining state, so that the flow control limits can be updated.
Fixes #1320.
=> consume incoming stream data when stream is draining

quiche/src/lib.rs
Useful for knowing when to "wake up" dgram writers. If it goes from full -> !full, we can re-attempt dgram sends.
=> expose whether or not the dgram send queue is full

quiche/src/h3/mod.rs, quiche/src/h3/stream.rs
In HTTP/3 some frames can legitimately have 0-length payloads, such as SETTINGS.
Previously, the HTTP/3 frame streaming parsing could get confused by these
frames, whereby it would try to read 0 bytes from the transport layer via
stream_recv(). In some cases, quiche could determine the stream is not
readable, because there are no more bytes to read - imagine a an empty
SETTINGS frame that arrived as the last frame on the control stream. In such a
case, quiche would return Error:Done, which would cascade up to the
HTTP/3 layer's frame parsing and cause it to quit early before parsing
the frame. The insidious thing here is that the HTTP/3 layer would
continue trying to read this stream on every call to `poll()`, but it
would always fail as long as the stream was determined to be not …
=> h3: better support 0-length payload frame parsing

apps/run_endpoint.sh, apps/src/args.rs, apps/src/bin/quiche-server.rs
Linux GSO will be detected automatically but some cases (quic-interop-runner) we need a way to explicitly disable it.
=> apps: add --disable-gso option

quiche/src/h3/stream.rs
HTTP/3 frames have a type, payload length, and frame-specific data.
There are some HTTP/3 fields that always contain fields, and as such,
they will always have a non-zero length payload length.
With this change, we add more robust checks for HTTP/3 frames that
contain fields but have a zero-length payload length. If this is
detected, its a critical error and the connection will be aborted with
the error H3_FRAME_ERROR.
=> h3: check and fail 0-length payload frames

quiche/include/quiche.h, quiche/src/ffi.rs
The state-related C API functions do not modify the connection object, and thus can use a constant pointer.
=> Added const quilifiers to some C API functions.

quiche/src/frame.rs, quiche/src/tls.rs
If quiche receives non-utf8 reason bytes for conn/app close and attempts to write to qlog, it will panic.
=> quic: avoid panics for non-utf8 reasons/errors

qlog/src/events/quic.rs, qlog/src/lib.rs, qlog/src/streamer.rs, quiche/src/lib.rs
This allows us to record the time that the packet pacer would
send this packet at. Since the qlog crate only uses relative
time since log start, the packet send Instant is converted
into a qlog time base and we log the duration since log start.
=> qlog: add send_at_time to PacketSent event

quiche/include/quiche.h, quiche/src/ffi.rs
A config option to completely disable pacing was introduced in #1348.
This PR adds the corresponding C API function:
```c++
// Configures whether to enable pacing (enabled by default).
void quiche_config_enable_pacing(quiche_config *config, bool v);
```
=> C API: added quiche_config_enable_pacing(..)

quiche/src/lib.rs
qlog packet have a mandatory PacketHeader type that contains several
optional fields. When creating packets to send, some of the fields
needed for qlog would upset the borrow checker later on, so previously
we constructed a PacketHeader early to avoid problems. This was
optionaly compiled via the qlog feature flag but there were no runtime
checks to see if the active connection had a qlog streamer configured.
That lead to unilateral construction of the object in quiche builds
that had the feature but didn't use it, leading to wasted effort.
With this change, the PacketHeader is only constructed if a connection
has actually been configured to output qlogs.
I also did a sweep for any other instances of similar unilateral
construction but this seems to be the only one.
=> lib: don't init qlog pkt hdr unilaterally

quiche/src/crypto.rs, quiche/src/lib.rs, quiche/src/packet.rs, quiche/src/recovery/bbr/mod.rs, quiche/src/recovery/cubic.rs, quiche/src/recovery/delivery_rate.rs, quiche/src/recovery/hystart.rs, quiche/src/recovery/mod.rs, quiche/src/recovery/reno.rs, quiche/src/tls.rs
Currently, epoch values are just `usize` constants over the code. The handling of the different epochs is done through arrays and the epoch-specific structure is accessed using the raw value behind the constant. While this should not happen, it might be possible to index a value out-of-bound (for instance, when doing some arithmetics on epoch values).
This commit replaces the plain `usize` typedef of `Epoch` by a dedicated `enum`, and implements the `Index(Mut)` traits to minimize the impact on the existing code (i.e., `Epoch` enum can be used to index the array).
Note that this change is also present in the refactoring commit in PR #1310, but proposing this specific refactoring in single-path sounds relevant and can then decrease the diff of the previous PR.
=> refactor Epoch to be an enum instead of usize consts

quiche/src/lib.rs
Previously, when a quiche connection was closed using `close()` with
`app` true, the connection might not already have been in a state
where it was safe to emit the application CONNECTION_CLOSE frame. Because
calling `close()` puts the connection into a terminal state where
newly received packets are discarded rather than processed, it is
possible that a connection in this state cannot emit a suitable
CONNECTION_CLOSE. In some circumstances, this could have led to a
connection becoming idle and then silently closed.
Applications could have worked around this by carefully managing the
use of `close()` based on connection states. For example, by
manually converting to a connection level close (`app` false)
or by deferring the close until a later moment.
This change modifies the `close()` …
=> Better support for Immediate Close during Handshake

quiche/include/quiche.h, quiche/src/ffi.rs, quiche/src/lib.rs, quiche/src/path.rs
- useful for keepalives
- ack-elicit is per-path to increase compatibility with multi-path work in #1310 
- not exactly a PING API since it doesn't send a PING if you would already send an ACK-eliciting packet. May or may not address #635 
- if this is interesting, we can update the C API too
=> quic: API for app to elicit ACK from peer

README.md
Apparently the URL changed a few weeks ago https://github.com/badges/shields/issues/8671
=> README: update URL of build badge

quiche/src/lib.rs
Addresses issue #1277.
Without this PR, having no space available in the congestion window prevents to send acknowledgements for the newly received packets. This can lead to situations with poor performance where no ACK is sent during a noticeable amount of time.
To implement this behaviour, we now only consider the available buffer size (`buf_cap`) when packing ACK frames.
When ACK frames are packed, reduce `left_for_congestion_controlled_packets` (new name for the `left` variable) to take the ACK frame size into account when packing the next non-ACK frames.
I added a new unit test verifying the inteded behaviour (`sends_ack_only_pkt_when_full_cwnd_and_ack_elicited`). This new test fails without the changes of this PR.
Do not hesitate to test, review and modify anything you want. …
=> Allow sending ACK only packets when the cwnd is full

qlog/src/lib.rs
Separated reference_time alignment as suggested in pull request [#1390](https://github.com/cloudflare/quiche/pull/1390)
=> qlog: align reference_time field with qlog spec

quiche/src/lib.rs, quiche/src/path.rs
During send_single, the current path is retrieved many times over which is both not free from a performance PoV and also not very readable. This change makes sure paths.get_mut is only called once per packet, which requires some workaround for the borrow rules. Overall the result is a cleaner code with slightly improved perforamnce.
In addition this change also keeps a single reference to the current PktNumSpace, which is purely a readabity improvement.
=> Take paths.get_mut out of the hot path

quiche/src/lib.rs, quiche/src/recovery/mod.rs
Because the ACK does not count towards the congestion window and the PING does, there can be a pathological case when the window is full then ACKs are emmited but PINGs are not, and quiche gets into an inifinite loop of sending ACKs, since the ack_elicit_required remains true, as no ack eliciting frame goes out.
=> only send opportunistic ACK if there is enough cwnd for PING

quiche/src/h3/qpack/encoder.rs, quiche/src/h3/qpack/huffman/mod.rs, quiche/src/h3/qpack/mod.rs
Huffman encoding is optimised for the regular ASCII range that HTTP
field values use. Characters in the lower or extended ASCII ranges can
use more bits via huffman than they might normally do otherwise.
The HTTP/3 layer estimates a generous buffer size for qpack encoding
based on name and value lengths. However, prior to this change,
certain combinations of characters could result in length inflation
beyond that which could bit in the reserved buffer. In turn, that would
cause the QPACK encode to fail and bubble up an h3::InternalError
to an application attempting to send requests or responses.
With this change, we add an early check the of huffman encoding
length prediction. If that huffman would produce a string larger
than the the literal unencoded string, we simply just use the raw …
=> qpack: when huffman inflates use raw literals

nginx/nginx-1.16.patch, quiche/include/quiche.h, quiche/src/ffi.rs, quiche/src/h3/mod.rs, quiche/src/lib.rs, quiche/src/stream.rs
Instead of cloning and returning a list of readable/writable streams, the new `stream_readable_next()` and `stream_writable_next()` return the first stream in the corresponding readable or writable queue, and remove it from said queue.
The end result is that each stream is only reported once, rather than being continuously reported until it becomes unreadable or unwritable, and as a consequence, applications will need to track partial read or written streams on their own.
In addition, a "low send watermark" is implemented through the existing `stream_writable()` method. When calling `stream_writable()`, if the stream doesn't at that time have enough capacity for the specified amount of bytes (i.e. `Ok(false)` is returned), then that stream will only be marked as writable again once its …
=> implement edge-triggered stream pseudo-iterators

quiche/src/stream.rs
if buf.fin() && buf.is_empty() && self.fin_off.is_some() true, then self.fin_off.is_some() && buf.is_empty() MUST be true, which means that we should return Ok(()) before this command.
=> stream: delete unreachable logic

quiche/src/ranges.rs
This API used to require an unstable feature, but it's now been stabilized.
=> ranges: simplify removing first element of list

quiche/src/lib.rs
Currently the handshake is confirmed, on both client and server, when an ACK for a 1-RTT packet is received, per RFC 9002, section 4.1.2 (2nd paragraph).
However we currently have no way to distinguish ACKs for 1-RTT packets and 0-RTT ones, which means that a client might end up thinking that the handshake is confirmed too early, and drop the Handshake epoch preventing the server from completing the handshake, and because this is just an optional optimization, it _should_ be safe to remove for the client.
For the server, we need to implement proper handshake confirmation per RFC 9002, section 4.1.2 (1st paragraph), which just states that handshake is confirmed once it is complete.
This also fixes a small bug that caused the "connection established" trace log to be spuriously emitted when …
=> fix handshake confirmation logic

fuzz/src/qpack_decode.rs, octets/src/lib.rs, quiche/examples/qpack-decode.rs, quiche/src/ffi.rs, quiche/src/h3/mod.rs, quiche/src/h3/qpack/mod.rs, quiche/src/packet.rs, quiche/src/ranges.rs, quiche/src/recovery/mod.rs, quiche/src/stream.rs
[std::u8](https://doc.rust-lang.org/stable/std/u8/index.html) has been deprecated in the standard library, as have [std::u16](https://doc.rust-lang.org/stable/std/u16/index.html), [std::u32](https://doc.rust-lang.org/stable/std/u32/index.html), [std::u64](https://doc.rust-lang.org/stable/std/u64/index.html), [std::usize](https://doc.rust-lang.org/stable/std/usize/index.html), etc. So I replaced these deprecated constants by built-in primitive type constants. Then these are all I can find, please add if there is something missing.
=> replace deprecated number constants by built-in primitive type constants

apps/run_endpoint.sh, apps/src/args.rs, apps/src/bin/quiche-server.rs
Pacing is enabled by default if SO_TXTIME is available, but it can be useful to disable it completely (e.g. for testing purposes).
=> apps: add option to disable pacing on the server

quiche/src/h3/mod.rs
Most cases of blocked body sends were already covered, except the specific edge-case where only enough capacity for a non-fin DATA frame header is available, in which case we would return `Error::Done` without calling `stream_writable()`.
=> h3: set send lowat when sending body is blocked

quiche/src/crypto.rs, quiche/src/lib.rs, quiche/src/packet.rs
This adds support for handling key update initiated by a peer. Based on the changes from #1121 with some additional modifications.
In addition to the included test case, this was also tested using the QUIC interop runner.
Fixes #1115, #1273, #1121.
=> handle peer-initiated key update

apps/src/bin/quiche-server.rs
When small packets are generated, the server only sends a single packet per RTT, which is not verry efficient.
=> apps: keep sending packets when a small packet is generated

qlog/src/events/h3.rs, qlog/src/events/qpack.rs, qlog/src/events/quic.rs, qlog/src/lib.rs, quiche/src/frame.rs, quiche/src/h3/frame.rs, quiche/src/lib.rs
The specs updated to use the common RawInfo type in several places,
these changes just synchronise that.
=> qlog: switch to RawInfo where needed

apps/src/args.rs, apps/src/bin/quiche-server.rs, apps/src/client.rs, apps/src/common.rs
SiDuck was an early attempt to promote interop of QUIC datagrams.
In the meantime, both QUIC datagrams and HTTP datagrams have been
published as RFCs. Furthermore, UDP and IP proxying use cases have
acheived good interop in the wider community.
This change removes SiDuck from the apps.
=> apps: remove siduck

quiche/src/h3/mod.rs, quiche/src/h3/qpack/decoder.rs, quiche/src/h3/qpack/encoder.rs, quiche/src/h3/qpack/static_table.rs
This change improves the QPACK static table lookup by avoiding iterating over all of the 99 entries for each header. Instead each lookup now consists of finding the table for the proper name length, then iterating over the possible names and if found iterating over the list of values for that name.
In the best case this will result in 0 iterations, in the worst case for an unmatched header it will result in 6 iterations for a name of length 7, and in 18 iteration for the worst succesful match for ":status: 500".
=> Improved static qpack lookup

qlog/Cargo.toml
We also bump serde to 1.0.139 to address a semver bug in serde_with.
https://github.com/jonasbb/serde_with/pull/588
=> Bump serde_with to 2.3.1

quiche/src/lib.rs, quiche/src/recovery/bbr/mod.rs, quiche/src/recovery/cubic.rs, quiche/src/recovery/delivery_rate.rs, quiche/src/recovery/mod.rs, quiche/src/recovery/reno.rs
Currently every time an ack arrives quiche allocates a new Vec to hold the newly acked packet descriptors. This is rather expensive, and can be avoided by reusing the same Vec. Sadly due to the way Recovery interface is implemented it can't be integrated in Recovery without significant rewrite, and has to be provided externally. Still the performance benefits are pretty significant.
=> Reuse the same Vec for newly_acked

.github/workflows/stable.yml, quiche/examples/Makefile
- ci: uthash is now available from homebrew
- Apple Silicon macOS: homebrew will install header and libraries in /opt/homebrew, not /usr/local.
CI doesn't have Apple Silicon yet, but it would be helpful for Apple Silicon macOS users.
=> ci: uthash from homebrew, fix Apple Silicon macOS example build

quiche/src/tls.rs
When debugging a QUIC packet exchange, enabling keylog allows to retrieve the encryption keys and set them up in, for example, Wireshark.
Realised today that keylog file was not being written until the connection was closed, which can be an inconvenience when debugging. Looking at the code, it seems that the keys are being written but not flushed out. A connection close/dealloc must be causing the flush currently, hence why the file is only written on connection close.
This PR adds a flush right after the write to make sure that the keylog file is made available as soon as possible.
=> Flush keylog write straight away

.github/workflows/stable.yml
It seems something got broken in a recent update in mingw land. So pin the workflow to an older release in order to let builds proceed.
See: https://github.com/brechtsanders/winlibs_mingw/issues/147
=> pin woodsend/setup-winlibs-action

quiche/src/lib.rs
Currently Instant::now is called twice, and is
surprisingly visible on flamegraphs.
=> Only call Instant:now once in send_on_path

quiche/src/lib.rs, quiche/src/path.rs, quiche/src/recovery/mod.rs
There is a bug where Quiche does not appropriately trigger loss recovery on connection migration. The main change introduced in this PR is to perform loss detection when connection migration is complete to allow for faster loss detection and retransmission on the current active path instead of the old, inactive path.
=> Trigger loss recovery as soon as connection migration is complete

quiche/src/build.rs
If a custom BoringSSLl is used then this may be outside the system library search path which would make the libquiche to use the system one which may not be what the user wants.
This is needed so the build [adds](https://doc.rust-lang.org/cargo/reference/build-scripts.html#rustc-link-arg) a directory to the runtime library search path which is needed for the generated quiche shared object, otherwise this is unknown by the lib and forces users to have the `LD_LIBRARY_PATH` set with a custom bssl path.
=> Include the BoringSSL lib path to the rpath when linking with a specified path.

quiche/src/recovery/mod.rs
The unacked array can contain thousands of packets and it can be very expensive to traverse linearly when acks are not delivered in order.
=> Use binary search to find beginning of unacked block

apps/src/bin/quiche-server.rs, quiche/src/cid.rs, quiche/src/lib.rs
An application can track these on its own, but quiche already has this information, so it can easily be exposed.
=> add method to expose all source CIDs

quiche/src/h3/mod.rs
The original idea was to set these streams as incremental so that
each one in the same urgency bucket had a fair share of bandwidth.
However, in reality there is little-to-no data being sent on these
streams. All the current behaviour does is create needless work in
the stream prioritizer for the entire length of a connection.
.
Changing to non-incremental reduces work and there should be no
noticable impact.
=> h3: convert control streams to non-incremental

quiche/include/quiche.h, quiche/src/ffi.rs, quiche/src/lib.rs, quiche/src/stream.rs
This was originally added for curl, but it was never used. The Rust API is also hard to use, because the app data reference borrows the whole connection object.
=> remove per-stream application data

quiche/src/lib.rs, quiche/src/stream.rs
Previously, StreamIter next() would pop() the last stream ID and return
it, leading to a back-to-front progression.
Since we're stuck with SmallVec for internal data for performance reasons
we can't pop_front(). So instead, this change skips mutating the
StreamIter's internal data and instead uses a simple tracking index that
lets us move front-to-back.
This change helps to avoid cases where we had a correctly ordered
SmallVec of streams, and would need to reverse it before constructing a
StreamIter, just so that the iteration would make logical progressions.
It also addresses cases where we missed doing any reversal preparation.
=> lib: progress through StreamIter from front to back

quiche/src/ffi.rs, quiche/src/h3/ffi.rs
nightly builds are failing without such a change.
=> ffi: explicitly drop Box in _free methods

quiche/src/lib.rs, quiche/src/path.rs
Also use smallvec. Similar to 0f22ab5f.
=> path: progress through SocketAddrIter from front to back

quiche/Cargo.toml, quiche/src/ranges.rs
Currently the RangeSet is always backed by a BTreeMap, and the map is allocated every Ack packet. This change is not unlike SmallVec for Vec, where instead of allocating, a limited number of ranges can be stored inline. Because in practice Ack packets will rarely ack more than one or two ranges, this avoids a significant number of allocations.
RangeSet is also used by the SendBuf to track the numbers of acked packets. Although in this use case allocations are already rare, with inline RangeSet the insertion operation is now also significantly faster.
=> Add an inline version of RangeSet

apps/src/common.rs
Previously, as soon as a server received a request, it would try to emit
headers and body during the same cycle. When then body was too large to
send (e.g., due to congestion window) the response would be queued up
for later rounds of writing. This initial send always happened
regardless of a stream's selected priority.
The later rounds of writing explicitly use a writable iterator to step
through the streams. When switching to an iterator that better supports
priority scheduling, streams that are queued are more likely to respect
the selected priority.
With this change, we no longer attempt to write body immediately.
Instead, it is added to the dispatch queue that will be drained in
accordance with the writable iterator.
.
=> apps: queue response body writes for better scheduling

quiche/src/lib.rs, quiche/src/stream.rs
Its clearer to have two functions do insert or remove than overload a
single one with a bool.
=> lib: split stream mark_* methods

quiche/src/tls.rs
See issue #1559. This does not fix the crate's unsafe bindings strategy, but corrects some of the mistakes that snuck in as a result of this unsafe strategy.
One thing to call out is that sk_num and sk_value's index types were wrong. This would have caused a problem were the crate not saved by most 64-bit calling conventions defining the upper half of the register when a 64-bit register is used to pass a 32-bit value. (But I have not carefully checked all calling conventions for this. The real fix is to stop writing bindings this way. This bindings strategy is even less safe than calling the library from C, which is quite a low bar to fail!)
Beyond that, the issues are mostly const-ness, though one notable issue is that function pointers need to be imported as Option. Also the return …
=> Fix a pile of incorrect bindings in tls.rs

quiche/Cargo.toml, quiche/src/tls.rs
It's already in our dependency tree, and will be easier to replace with std API once it's stabilized.
=> tls: use once_cell instead of lazy_static

quiche/Cargo.toml, quiche/src/h3/mod.rs, quiche/src/lib.rs, quiche/src/packet.rs, quiche/src/stream.rs
This change modifies the internal implementaion of
readable and writable stream collections so that they
better respect the ordering expected from RFC 9218.
=> prioritized readable and writable iterators

quiche/src/h3/mod.rs, quiche/src/lib.rs
slices already encode their length, no need for extra len argument
=> remove unnecessary argument to decode_pkt

quiche/src/lib.rs
The function declaration of `sort()` is `fn sort(&mut self) -> ()` and so these tests were simply asserting `() == ()`. After correcting them they failed and so a change to `paths_iter()` is needed.
=> Fix broken send_on_path_test

quiche/include/quiche.h, quiche/src/ffi.rs, quiche/src/lib.rs
Connection::new() takes several parameters and does a lot of heavy
lifting for callers. In particular it creates a TLS Handshake from the
Config's tls_ctx object, which requires mutability.
In contrast, Connection::with_tls() doesn't require any Config
mutability. So let's remove that.
Fixes #1593
=> lib: with_tls doesn't require a mutable Config

quiche/src/recovery/mod.rs
Usually an Ack will acknowledge packets that are no longer in the queue so the first packet may be larger than the smalles acked packet.
=> Correct logic to avoid binary search on ack

apps/Cargo.toml, apps/src/common.rs, nginx/nginx-1.16.patch, quiche/examples/http3-client.c, quiche/examples/http3-client.rs, quiche/examples/http3-server.c, quiche/examples/http3-server.rs, quiche/include/quiche.h, quiche/src/ffi.rs, quiche/src/h3/ffi.rs, quiche/src/h3/frame.rs, quiche/src/h3/mod.rs, tools/http3_test/src/runner.rs
h3: add HTTP/3 datagram RFC version
With this change, we add support for advertising the HTTP/3 datagram SETTING
value (0x33) defined in draft 11 and RFC-to-be when an h3 Connection is
configured to have datagrams enabled.
The format of the the HTTP/3 datagrams are pretty much structurally identical,
so there is not much meaningful difference between versions. Applications that
rely on HTTP/3 datagrams, such as to use CONNECT-UDP, would apply their own
semantics to these datagrams and can manage that themselves. Therefore, this
change doesn't provide fine grain control over versions.
h3: remove HTTP/3 datagram API
An HTTP/3 datagram is a series of fields carried in a QUIC DATAGRAM frame
payload. In draft 00, draft 11 and what will be the RFC there is a single field,
which is a …
=> h3: remove dgram API in order to add support for RFC version

README.md, quiche/src/lib.rs, quiche/src/tls.rs
quiche currently unwraps the SslContextBuilder and modifies it with the boring FFI functions directly. This assumes the SSL context is exclusively owned by quiche, but that may not be the case as SslContext values are clonable. The function should take a SslContextBuilder instead, which guarantees that the inner SSL context is not shared with anything else prior to calling SslContextBuilder::build.
=> Pass a SslContextBuilder to quiche

quiche/src/lib.rs
This patch fixes the calculation and avoids app_limited to be incorrectly set true.
=> Correctly account for datagram queue in delivery_rate_check_if_app_limited

quiche/src/recovery/bbr/mod.rs
For Web traffic which is sending packets for short duration and then idle for some duration, we should not enter probe RTT phase when idle. This leads to unnecessary reduction in cwnd and sometimes stalls.
When probe RTT timer has expired, idle_restart flag decides whether to enter probe RTT or not. In quiche we reduce the inflight after updating the BBR model and state, this leads to inflight not being zero. Since inflight is not zero we do not set idle_restart flag and we always enter probe RTT phase for web kind of traffic.
Here we check if inflight is less than 4 packets and if app_limited flag is also set, we set idle_restart flag. The idea being since inflight is low we would have already captured min_rtt and dont need probe RTT phase.
=> Fix BBRv1 idle_restart flag

quiche/src/h3/mod.rs, quiche/src/lib.rs, quiche/src/ranges.rs
Fixes the following lints that were enabled in 1.72.0:
https://rust-lang.github.io/rust-clippy/master/index.html#useless_conversion
https://rust-lang.github.io/rust-clippy/master/index.html#redundant_pattern_matching
https://rust-lang.github.io/rust-clippy/master/index.html#useless_vec
https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow
=> Clippy Fixes

apps/Cargo.toml, apps/src/bin/quiche-server.rs, apps/src/sendto.rs
One notable change is that functions like `setsockopt()` now require `AsFd` instead of the raw fd, but mio doesn't implement that, so we need to convert fds explicitly.
=> apps: update to nix 0.27

quiche/include/quiche.h, quiche/src/lib.rs, quiche/src/recovery/bbr/mod.rs, quiche/src/recovery/bbr2/init.rs, quiche/src/recovery/bbr2/mod.rs, quiche/src/recovery/bbr2/pacing.rs, quiche/src/recovery/bbr2/per_ack.rs, quiche/src/recovery/bbr2/per_loss.rs, quiche/src/recovery/bbr2/per_transmit.rs, quiche/src/recovery/cubic.rs, quiche/src/recovery/delivery_rate.rs, quiche/src/recovery/mod.rs, quiche/src/recovery/reno.rs
This PR is implementing BBR v2 congestion control algorithm specified in [draft-cardwell-iccrg-bbr-congestion-control-02](https://datatracker.ietf.org/doc/html/draft-cardwell-iccrg-bbr-congestion-control-02), based on #1180.
Mostly as-is translation of the draft, might be buggy and not well tested. Also it need some additional change on the recovery and rate estimatino module included in this PR.
If you look for more stable bbr, see #1180 first.
=> cc: BBRv2 congestion control module

quiche/include/quiche.h, quiche/src/ffi.rs, quiche/src/lib.rs
Currently, transport parameters are available through `stats()`. APIs that used to offer access to certain transport parameters have been removed in favor of using `stats()`. While this does work, it's wasteful to return such a large structure when you may only care about a single TP. This change makes `TransportParameters` public, adds a method `peer_transport_params()` that returns a reference, and removes transport parameter fields from `Stats`.
=> quic: add peer_transport_params()

quiche/src/dgram.rs, quiche/src/lib.rs
Previously, we calculated the value of the largest DATAGRAM frame that
could be sent every time we wanted to send a packet. The calculation is
controlled by peer TPs, which can be sent even if the peer doesn't
really want us to use the DATAGRAM on the connection (e.g. conventional
HTTP/3 serving).
We only need the DATAGRAM size when we have datagrams to actually send.
This change implements a check of the internal DATAGRAM send queue to
avoid the calculation.
=> lib: skip dgram frame size calc when none to send

quiche/include/quiche.h
The last argument of `quiche_get_varint` in [ffi.rs (line 1365)](https://github.com/cloudflare/quiche/blob/83d9168ab6f76302ae846cb068cc8991f2b06479/quiche/src/ffi.rs#L1365C15-L1365C32) writes the read value to the last argument. However, the argument in the respective C function in [quiche.h (line 679)](https://github.com/cloudflare/quiche/blob/83d9168ab6f76302ae846cb068cc8991f2b06479/quiche/include/quiche.h#L679) accepts the last argument as a value and not as a pointer.
=> quiche.h: add missing pointer

quiche/src/ffi.rs
This should have been removed in 21af572b4ae1ce906fbac7b3048409c935e59662.
=> ffi: remove spurious `paths` field from Stats

.github/workflows/stable.yml
For now only the "main" quiche CI job tests both features to avoid adding too many new jobs, in the future we might decide to change this.
Ref #1614.
=> ci: test both vendored boringssl and boring crate

quiche/src/crypto.rs, quiche/src/packet.rs, quiche/src/tls.rs
In some cases we are turning Vec values into slices to pass them to functions that will then turn the slice back into a Vec.
Instead just pass `Vec`s around to avoid some unnecessary allocations.
=> crypto: avoid unnecessary allocations when generating keys

quiche/src/h3/ffi.rs
An event was removed in 48aac48a1882631ecaf1c04c06235102631bfcf1 but the enum wasn't renumbered, so the Rust values didn't match the C ones anymore.
Fixes #1650
=> h3: fix event type conversion to FFI enum

catalog-info.yaml
The system key is not mandatory, and add BoringSSL to dependencies while at it.
=> backstage: update ctaalog entry

qlog/src/events/mod.rs
=> qlog: Added MtuUpdated event missing from EventImportance implementation

quiche/include/quiche.h
Motivation:
socklen_t should be used for passing the length of sockaddr. This was already done in the ffi code but not in the c header file
Modifications:
Use socklen_t
Result:
Correct type in c header file
=> Use socklen_t when passing sockaddr to c functions

quiche/src/cid.rs
Motivation:
ConnectionIdIter is not used, let's just remove it.
Modifications:
Remove unused code
Result:
Cleanup
=> Remove unused ConnectionIdIter

apps/src/bin/quiche-server.rs, apps/src/client.rs, quiche/src/lib.rs
Motivation:
Some of the methods used *source_cid* and *destination_cid* in the name while most others uses *scid* and *dcid*. Naming of methods should be consistent to make it easier to discover things.
Modifications:
Add new methods with consistent naming and deprecate the old ones
Result:
Cleanup of public API
=> Rename methods to be more consistent and deprecate the old ones

quiche/include/quiche.h, quiche/src/ffi.rs
Motivation:
At the moment its impossible to call retire_dcid(...) via the C API.
Modifications:
Add quiche_conn_retire_dcid to header file and also add the implementation to ffi.
Result:
Be able to retire destination connection id
=> Expose quiche_conn_retire_dcid(...)

quiche/include/quiche.h, quiche/src/ffi.rs
Motivation:
At the moment its impossible to get all source ids via the C api.
Modifications:
Add C / ffi impl to get all source ids
Result:
Fix gap between rust and C api
=> Expose connection source ids via c API

quiche/include/quiche.h, quiche/src/ffi.rs
Motivation:
There was no C api exposed to allow handling PathEvent.
Modifications:
Expose c functions to handle PathEvent
Result:
Be able to handle and consume PathEvent
=> Expose C api to handle PathEvent

quiche/include/quiche.h, quiche/src/ffi.rs
Motivation:
Quiche didnt expose all methods via c functions that are required to start connection migration.
Modifications:
Add missing ffi implementatins and add functions to c header file.
Result:
Be able to do connection migration on the client side.
=> Expose functions related to client side connection migration via c API

quiche/include/quiche.h, quiche/src/ffi.rs
Motivation:
set_disable_dcid_reuse(...) and quiche_config_set_ticket_key(...) are not exposed via the c API.
Modifications:
Add FFI implementation and add functions to c header file.
Result:
Add missing config methods
=> FFI: Add missing API for config

qlog/src/events/mod.rs
Extend `impl From<EventType> for EventImportance` for all `TransportEventType` `enum` variants.
=> feat(qlog): extend `From<EventType> for EventImportance`

qlog/src/events/mod.rs
Fixes a copy&paste error in the serde rename attribute of the `EventData::PacketsAcked` `enum` variant.
=> fix(qlog): update serde rename of `PacketsAcked`

qlog/src/streamer.rs, quiche/src/lib.rs
I was debugging some connection problems and enabled qlog; however, often I did not get output. My use-case is going through the FFI layer which instantiates a `BufferedWriter` for the file. After looking through the code a bit it appears that the `QLogStreamer` is not flushed on all close paths which can lead to missing logs.
Make sure that on every close path the streamer is flushed and closed as well.
=> Flush qlog streamer before closing the connection

qlog/src/events/mod.rs, qlog/src/streamer.rs, quiche/src/lib.rs
Previously, the QlogStream API only supported concrete qlog::events::Event
objects. This limited the ability to stream ad-hoc types, which could be useful
for various use cases such as implementing extension Events or augmenting a
standard event with additional custom date.
This change modifies the API by replacing the Event type parameter with traits.
The new Eventable trait provides basic features need for qlog, and it is paired
with serde::Serialize to support convention.
A new JsonEvent is defined to leverage the new API. The data field is a
serde_json::Value, allow callers to construct arbitrary structured data that
can then be logged in an ad-hoc manner. This approach ensures that the QLOG-SEQ
serialization is a valid format that can also be parsed back in a structured
manner. …
=> qlog: extend serializer to support arbitrary types of event

qlog/src/lib.rs, qlog/src/reader.rs
QlogStreamer is a helper to support serializing qlog to the JSON-SEQ
format. This change adds the QlogSeqReader helper for reading JSON-SEQ.
=> qlog: Add QlogSeqReader helper

quiche/src/lib.rs
If a quiche connection is configured to log using qlog (via set_qlog()
or set_qlog_with_level()) internally it creates a qlog streamer object
and using that to write out events.
This change adds a getter for the streamer, which allows library users
to also write their own events.
=> lib: add getter for qlog streamer

quiche/src/h3/mod.rs
grease_value() generates an HTTP/3 GREASE value. Applications can
find this useful, so make it public.
=> h3: make grease_value() public

quiche/Cargo.toml, quiche/src/h3/mod.rs
The quiche::h3::frame module is by default private because low-level
details are abstracted behind higher-layer APIs. However, for some
situations, such as testing, it can be helpful to have direct access
to frame types and their serialization/deserialization code.
This change adds a new 'internal' feature that when enables makes
the frame module public. There are no guarantees of API stability
for things exposed in this way.
=> h3: allow the frame module to be public under a new feature

qlog/src/events/mod.rs, qlog/src/streamer.rs
This change allows additional JSON fields to be contained in qlog events
without needing to change the core definitions.
=> qlog: add ex_data to Event

quiche/src/crypto.rs, quiche/src/tls.rs
Looks like a new warning in nightly.
=> fix dead code warnings for FFI types

apps/Cargo.toml, apps/src/bin/quiche-client.rs, apps/src/bin/quiche-server.rs, tools/http3_test/Cargo.toml, tools/http3_test/tests/httpbin_tests.rs
This dependency update removes usage of the unmaintained and unsound `atty` crate.
=> Update env_logger to mitigate RUSTSEC-2021-0145

fuzz/src/packet_recv_client.rs, fuzz/src/qpack_decode.rs, tools/http3_test/tests/httpbin_tests.rs
Because this code is excluded from the workspace, it hasn't been linted recently.
=> Clippy fixes for code excluded from workspace

quiche/src/stream/mod.rs, quiche/src/stream/send_buf.rs
lib: minimise calls to SendBuf off_front()
There were several places where off_front() would be called in rapid succession.
off_front() potentially has to iterate a large queue to find the "front" value.
In rapid succession, that value is identical, leading to wasted work.
This change removes the ready() function (which called off_front) and refactors
code to minimise off _front() calls.
=> lib: minimise calls to SendBuf off_front() during emit()

quiche/src/frame.rs, quiche/src/lib.rs
RFC 9000 has some low-level requirements for who is allowed to send
a NEW_TOKEN frame, and what the token value can be.
This change adds stricter NEW_TOKEN frame checks. It leaves any
more advanced handling of the Retry mechanism as continuing TODO.
=> lib: stricter NEW_TOKEN frame checks

quiche/src/lib.rs
Follow-up to 1684118a979276428ce9f994b028463b26465698.
This error was added in the previous commit, but we can use a more specific error instead, also to be more consistent with existing code (e.g. see HANDSHAKE_DONE case).
=> remove ProtocolViolation error

octets/src/lib.rs
This pull request proposes a minor fix to the lifetime annotations in the octets crate.
The `slice` and `slice_last` methods defined for `Octets` return a subslice from a slice stored
inside the method's receiver. As such the returned reference should share the lifetime of the 
originating slice.
Due to the current lifetime annotations the returned lifetime is bounded by the method's receiver.
This has the implication that the returned slice can not be used after the receiver
used to produce the slice goes out of scope even though the returned reference to the underlying data
may still be valid.
```
struct Capsule<'a> {
kind: u64,
data: &'a [u8],
}
impl<'a> Capsule<'a> {
fn from_bytes(buf: &'a [u8]) -> std::result::Result<Self, BufferTooShortError> {
let mut octets = …
```
=> Crate octets: Fix incorrect lifetime annotation

qlog/src/events/h3.rs, quiche/src/h3/mod.rs
Adds a missing field, see See https://quicwg.org/qlog/draft-ietf-quic-qlog-h3-events.html#name-stream_type_set
=> qlog: add stream_type_value for unknown streams

apps/Cargo.toml, quiche/Cargo.toml, tools/http3_test/Cargo.toml
This reverts commit 45b59aa8f2d6f2e97c2af74f562848fcd0092062.
Dependabot stepped in seemed to have builds work on https://github.com/cloudflare/quiche/pull/1727, so maybe it was a transient issue, lets see how CI deals with it
=> Revert "constrain ring version to avoid Windows issues" and bump ring in http3_test

quiche/src/lib.rs
Currently we treat any PING frame loss as a PMTUD signal, but PING frames are used for many other things (including PTO probes), so the PMTUD logic should not react to PING losses unconditionally.
=> avoid reacting to non-PMTUD PING losses

quiche/src/h3/frame.rs, quiche/src/h3/mod.rs, quiche/src/h3/stream.rs
Using additional settings, an application can configure and set H3 settings that are not explicitly handled by quiche.
This can be useful to develop some apps atop quiche's h3 without needing quiche to explicitly support it.
For instance, I use it in my webtransport implementation atop quiche: https://github.com/francoismichel/webtransport-quiche/blob/269d8fcba3e874c1984ec65c6dfd653cce4c15eb/src/lib.rs#L97C13-L97C13
Let me know your thoughts and comments.
Cheers,
François
=> h3: allow applications to set additional settings

apps/run_endpoint.sh
In the 0-RTT test there are more than 2 requests, and we are supposed to only run the first one in 1-RTT and the remaining ones in the resumed 0-RTT connection.
=> apps: fix 0-RTT and resumption interop tests for the client

qlog/src/events/quic.rs, qlog/src/lib.rs, quiche/src/frame.rs
The qlog spec includes these fields and we didn't; see https://quicwg.org/qlog/draft-ietf-quic-qlog-quic-events.html#name-quic-frames
=> qlog: add length and payload_length fields to QUCI frames

qlog/src/events/mod.rs, quiche/src/lib.rs
There are situations where connections are closed but no CONNECTION_CLOSE
frames were exchanged, for example handshake failures or idle timeouts.
This change adds the connectivity::connection_closed event to the mark_closed()
method, just before we blow away the qlog serializer.
I've chosen to have it log an event even if we did send or receive
CONNECTION_CLOSE frames, which is a minor duplication. My rationale is
that in future we might want to have filters that would omit detailed
frame information while key connection state changes are interesting.
=> lib: add qlogging of connection close

quiche/src/h3/mod.rs, quiche/src/lib.rs
Applications currently have to redefine these error codes whenever they want to use them. It'd be nice to export them from Quiche so that they don't have to.
=> Publicize error codes

quiche/src/lib.rs, quiche/src/stream/send_buf.rs
An application can buffer stream data but not have the opportunity to prepare
the packets that would send that data. Within this window of time, the stream
might get reset either in reaction to receiving a STOP_SENDING frame, or due to
the application resetting the stream themselves via stream_shutdown(). Once this
occurs, no stream data will be sent. Instead, a RESET_STREAM will be emitted
when packets are next prepared that contains a final size of whatever bytes
_had_ been sent.
Quiche needs to keep a reference to such a stream for as long as it is "active".
For a bidi stream, that means that the receive side has been finished, and the
send side closure (RESET_STREAM) has been acknowledged and validated. Only when
both these conditions are true will the stream be collected. Stream …
=> lib: fix resetting of streams with buffered but unsent data

.github/workflows/deploy.yml, .github/workflows/nightly.yml, .github/workflows/stable.yml
- Deprecate use of action-rs (no longer maintained)
- Update macos runner type (x86_64 and M1)
- Upgrade checkout from v3 (Node.js version warning)
- Upgrade ghaction-chocolatey to v3 (Node.js version warning)
=> ci: deprecate action-rs and other ci fix

quiche/src/recovery/rtt.rs
Follow-up to 3b758cb122d2cde6c197947b027bab630f8c0f21 which changed the initial min_rtt value from Duration::ZERO to Duration::MAX.
This could potentially cause an overflow, for example if there is no previous RTT sample, and the CUBIC congestion avoidance logic is triggered.
Switch back the initial value to ZERO.
=> rtt: initialize min_rtt to zero

.github/workflows/stable.yml
- A new cargo-ndk release requires Cargo.toml of a package, not a workspace.
- Current ubuntu image(22.04) already has NDK 25, use a builtin ndk instead to remove warning and improve build time.
https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md
=> ci: fix android build

quiche/src/h3/mod.rs
send_headers() can fail if there is not enough stream capacity to buffer
encoded headers. Applications are expected to try again later.
Previously, send_response_with_priority() would update
the stream priority prior to send_headers(), which might surprise
some types of applications relying on the writable() iterator.
This change swaps the ordering around so that priority is only changed
after headers have been successfully buffered.
=> h3: set stream priority after headers buffered

quiche/src/h3/mod.rs
If an H3 stream gets into a Data state that is not cleared for the stream (for example because downward backpressure), and a ResetStream arrives, the poll will transition the stream to finished and never clear the readable state of the stream, it will forever stuck in the readable state. This will mean that poll will return Finished and not Reset for the stream, and will have a somewhat significant performance impact, as for long lived connections it will take longer and longer to poll before the iterator reaches a stream that is actually readable.
=> H3: if readable after Finished, call recv again

quiche/src/h3/qpack/mod.rs
Looks like newer nightly rustfmt does this now.
=> h3: fix format in qpack test

quiche/src/ffi.rs, quiche/src/h3/ffi.rs, quiche/src/rand.rs
=> Fix clippy legacy_numeric_constants warning

quiche/Cargo.toml, quiche/src/build.rs
Using cdylib-link-lines, add soname to the generated shlibs.
It will add the following to libquiche.so:
```
% readelf -d target/debug/libquiche.so
...
0x000000000000000e (SONAME)             Library soname: [libquiche.so.0]
```
For linux, *bsd, android, ios and macos.
Fixes #598
Fixes #165
=> Add soname to libquiche.so

quiche/include/quiche.h
This helps in using Quiche as a dependency in a Swift project.
Basically, the issue is that Swift does not support mixing C and C++ code when using interop, it has to use either C or C++, so if someone already has a C++ dependency in their project, Swift will try to import Quiche as Objective-C++, but this will cause issues due to #includes.
This technically is a shortcoming of Swift, not specifically an issue with Quiche, but the fix is very simple and shouldn't break anything for people using Quiche from C/C++/other languages with interop.
=> Move `extern "C"` below `#include`s in C API header.

apps/src/bin/quiche-server.rs
If a connection doesn't have any more packets to send, we should keep processing other connections, rather than going back to polling.
=> apps: keep processing connections after draining one

quiche/src/h3/mod.rs
Even though the `Session` struct is technically `hidden`, sometimes it's useful for testing. Currently, it's impossible to use `new()` from a different location because the `examples/cert` files aren't findable. 
Also a stray format change from running `cargo +nightly fmt`
=> testing: make example cert/key files relative to Cargo.toml

quiche/src/h3/mod.rs
Previously, quiche's poll() function would attempt to do work on control or
QPACK streams, whether they were readable or not. Since we encourage apps to
call poll() after each read loop, this could result in wasted work.
With this change, we'll return early if the stream is not actually readable.
=> h3: Avoid unnecessary work on control streams

quiche/include/quiche.h, quiche/src/h3/ffi.rs, quiche/src/h3/mod.rs
Similar to QUIC connection and path stats, this change introduces an HTTP/3
stats object and accessor method. Initially, only some QPACK counters are
present.
=> h3: add initial stats

h3i/Cargo.toml
Not everything has been ported to hyper/http 1.0 yet, so use the old version for now.
=> h3i: downgrade http crate to pre-1.0

nginx/nginx-1.16.patch, quiche/include/quiche.h, quiche/src/h3/ffi.rs, quiche/src/h3/mod.rs, quiche/src/h3/stream.rs, tools/http3_test/src/lib.rs
HTTP/3 request and response message exchanges allow multiple HEADERS
frames to be sent, which allows for trailer sections or non-final
responses. Previously, quiche has only supported generating a single
HEADERS frame per request or response, and didn't support receiving
them.
This change adds support for sending and receiving multiple HEADERS
frames on a request stream. It enforces the sequencing rules defined in
https://datatracker.ietf.org/doc/html/draft-ietf-quic-http-34#section-4.1.
Sending additional HEADERS is done using the new
`send_additional_headers()` method. On the receive side, rather than add
a new Event enum variant for these additional uses of HEADERS, this
change reuses Event::Headers. Previosuly, this event included a
`has_body` boolean, which has been renamed to …
=> h3: add support for additional HEADERS

quiche/src/h3/mod.rs, quiche/src/h3/stream.rs
h3: earlier checks for control and QPACK stream termination
A peer can FIN or reset a control stream at any point during the stream
lifetime. While doing so is an error in HTTP/3, our handling before this change
was a bit odd.
Previously, depending on the sequencing, an unexpected termination of such a
stream could trigger an InvalidStreamState or StreamReset error during poll().
This would bubble up to the app, which is weird and unexpected because the
quiche h3 layer is supposed to deal with all the control stream details. While
both those errors contain a stream ID, the app isn't given any info that the ID
is a control stream.
While any subsequent call to poll() would then cause the stream_finished
detection to kick in and enforce the RFC rules to close the connection with …
=> h3: earlier check for control and QPACK stream termination

quiche/src/h3/mod.rs
We recently added the `send_additional_headers()` method to support sending
mupltiple HEADERS for a single request or response. However, it remained
possible to call `send_response()` or `send_response_with_priority()`
multiple times for the same stream ID, which is now unintuitive.
This change enforces that `send_response()` or `send_response_with_priority()`
can only be called once per stream.
=> h3: prevent multiple calls to send_response | send_response_with_priority

quiche/src/crypto/boringssl.rs, quiche/src/crypto/mod.rs, quiche/src/crypto/openssl_quictls.rs, quiche/src/packet.rs, quiche/src/tls/mod.rs
Calling Prk::new_less_safe results in at least 4 rounds of SHA-256.
This change reuses previosly created instances of Prk to reduce cost of key derivation.
=> Reduce amount of SHA-256 operations when deriving keys

qlog/src/reader.rs
By adding an explicit lifetime parameter to QlogSeqReader the lifetime of the Box'd BufReader's inner does not need to be 'static.
=> qlog: Add explicit lifetime parameter to QlogSeqReader

h3i/src/actions/h3.rs, h3i/src/main.rs, h3i/src/recordreplay/qlog.rs
One use case for replaying a recorded session with the h3i CLI is to execture
the same sequence of actions to different target servers. Many servers will
validate that there is a provided "host" or ":authority" header field, and that
it matches the certificate SAN.
This change adds the "--replay-host-override" option that can be used in
combination with the --qlog-input option. It replaces any "host" or ":authority"
header in a HEADERS frame, with the provided value.
note: the diff looks huge but most of what its doing is swapping a From impl to a function so the host_override value can be passed to the correct place
=> h3i: add --replay-host-override option

quiche/src/lib.rs
The RFC states that an endpoint can immediately close a connection by
sending a CONNECTION_CLOSE frame during the handshake:
> However, prior to confirming the handshake, it is possible that more
advanced packet protection keys are not available to the peer, so
another CONNECTION_CLOSE frame MAY be sent in a packet that uses a lower
packet protection level.
Currently, when we decide the packet epoch when a CC frame is present,
we always choose Application. This commit downgrades the epoch to
Handshake if the handshake wasn't confirmed.
The test added in this PR fails without this patch - since the packet is
sent in the Application space without keys, the server can't decrypt it,
so its `peer_error` is None.
=> Force Handshake packet epoch if handshake hasn't been confirmed

h3i/src/client/mod.rs, h3i/src/client/sync_client.rs, h3i/src/main.rs
Most of the diff is just copy-pasting the function from one place to another. This will deduplicate a bunch of code between the sync and async versions
=> h3i: extract connection creation to its own function

quiche/src/lib.rs
Small typo in `Connection`'s `new_scid` documentation.
=> lib: Fix typo in Connection new_scid documentation

qlog/src/streamer.rs
One of the features of JSON-SEQ is that it can support newlines embedded
in records. Prior to this commit, the qlog streamer only supported a
"condensed mode" of writing events on a single JSON line, which can affect
the usability in some circumstances.
This change adds support for discretionary logging of each individual event
using condensed or pretty formats. A new set of "_pretty" suffixed methods
are provided to allow callers to select the format, without breaking
backwards capability. This design also mimics serde's approach.
=> qlog: add optional pretty-printing for JSON-SEQ streaming

h3i/examples/content_length_mismatch.rs, h3i/src/client/connection_summary.rs, h3i/src/client/mod.rs, h3i/src/client/sync_client.rs
We originally had plans to completely deprecate the sync client once the async one was finished, but we've since found a use for the sync client.
This gets rid of the ugly hacks we originally implemented to speed up development by converting all sync/async conditional compilation into a trait object. This means that we can simply implement the Client trait for the async client
=> h3i: make Client a trait object

.github/workflows/nightly.yml, .github/workflows/stable.yml, Dockerfile, h3i/Cargo.toml, qlog/Cargo.toml, quiche/Cargo.toml
Per the comments, when doing a qlog release we end up in a situation where quiche or h3i might be updated to a new qlog version in the same PR as the qlog version bump itself, which requires the qlog release to be published before the PR is merged (and _not_ bumping the version would break other builds that use the `path = ../qlog` as dependency).
Also includes https://github.com/cloudflare/quiche/pull/1885 to test, and bumps MSRV to 1.70 to fix builds.
=> ci: disable cargo package builds

quiche/src/lib.rs, quiche/src/packet.rs
Instead of keeping separate sequences for each packet number space, use the same sequence.
This is needed to make it easier to support FIPS. This is because FIPS mandates that the crypto module (e.g. BoringCrypto) has to validate that the AEAD counter (which in QUIC corresponds to the packet number) is stricly monotonically increasing (so that counters are not reused).
Because BoringCrypto saves the counter inside its own AEAD context, and because new paths currently require starting from packet number 0 again, the FIPS requirement would require us to maintain separate AEAD contexts for each path, which we currently don't do (and would probably be messy to implement).
This reverts commit 40e2433300d5bf57e3046a09e81974effb4697d7.
=> generate packet numbers from a single sequence

quiche/src/crypto/boringssl.rs, quiche/src/crypto/mod.rs
The main difference is that the _tls13() AEAD follows the FIPS requirements, the main one being that AEAD counters are strictly monotonically incresing for each seal operation.
=> crypto: use the FIPS-compliant AEAD from BoringCrypto

.github/workflows/stable.yml, qlog/Cargo.toml, tools/http3_test/Cargo.toml
Run cargo-machete for unused dependency check, only on
a default ssl target. Also removed unused dependencies 
recommended by an initial run of cargo-machete.
=> ci: add cargo-machete in the workflow

h3i/examples/content_length_mismatch.rs, h3i/src/client/connection_summary.rs, h3i/src/client/mod.rs, h3i/src/client/sync_client.rs, h3i/src/config.rs, h3i/src/frame.rs, h3i/src/lib.rs, h3i/src/main.rs
Close trigger frames allow the user to specify a list of frames that the h3i client expects to receive over a given connection.
If h3i sees all of the close trigger frames over the course of the connection, it will pre-emptively close the connection with a CONNECTION_CLOSE frame. If h3i does _not_ see all of the trigger frames, the resulting ConnectionSummary will contain a list of the missing target frames for future inspection.
This gives users a way to close tests out without waiting for the idle timeout, or adding Wait/ConnectionClose actions to the end of each test. This should vastly speed up test suites that have a large number of h3i tests.
In the absence of full-fledged integration tests, I modified the `content_length_mismatch` example to expect a `400`, and remove the existing …
=> h3i: implement close trigger frames

quiche/src/crypto/mod.rs, quiche/src/lib.rs, quiche/src/packet.rs
Both BoringCrypto and OpenSSL provide `CRYPTO_memcmp()` for constant-time comparisons, so there's no point in pulling a whole dependency just for that.
=> crypto: replace ring constant-time comparison API

quiche/Cargo.toml
This doesn't seem to be necessary, and was probably a copy-pasta from qlog since that one does require the feature to be enabled.
=> disable 'serde' feature for smallvec

quiche/include/quiche.h, quiche/src/ffi.rs
Changes `quiche_conn_path_event_next` so that it returns a mutable pointer on both the C and Rust side. This fixes issue #1905.
Also added `const` to the `quiche_path_event*` parameters in the following functions from  `quiche.h` in order to match their mutability in `ffi.rs`:
- `quiche_path_event_type`
- `quiche_path_event_new`
- `quiche_path_event_validated`
- `quiche_path_event_failed_validation`
- `quiche_path_event_closed`
- `quiche_path_event_reused_source_connection_id`
- `quiche_path_event_peer_migrated`
=> ffi: make `quiche_conn_path_event_next` return `mut` pointer (fix #1905)

quiche/Cargo.toml, quiche/src/crypto/boringssl.rs, quiche/src/crypto/mod.rs, quiche/src/crypto/openssl_quictls.rs
This is currently only used for generating header protection masks, which, again, doesn't seem like something worth pulling a whole dependency for. This may or may not fall under FIPS scope.
Note that the ring dependency itself is still needed to build examples, but it can be downgraded to `dev-dependencies`.
=> crypto: replace ring AEAD API for header protection

quiche/src/ffi.rs
Functions `quiche_conn_close` and `quiche_conn_stream_send` now check to make sure the passed pointers are not null before creating a slice with them. If they are null, `&[]` is used instead. Length must be 0 when the buffer is null, of course.
- Fixes issue #1914.
- Allows passing null to `quiche_conn_stream_send` for convenience to trigger FIN STREAM.
=> ffi: quiche_conn_close and quiche_conn_stream_send check for null pointers (fix #1914)

quiche/src/lib.rs, quiche/src/path.rs
This PR tracks the number of sent and received DATAGRAM frames on the connection-level and on individual paths. It provides more visibility into what has been transferred over the connection. Currently only the number of sent and received packets is tracked.
=> Maintain DATAGRAM sent/received statistics

Dockerfile, README.md, quiche/Cargo.toml, quiche/src/recovery/congestion/prr.rs, quiche/src/tls/mod.rs
We can drop the once_cell dependency since the same functionality is implemented in std now.
Requires bumping MSRV to 1.80.
=> replace once_cell with LazyLock

qlog/src/events/quic.rs, quiche/src/lib.rs
Track (and make available to qlog for logging) transport parameters and their values that this implementation does not specifically recognize.
=> lib, qlog: Track and Log Unknown Transport Parameters

quiche/src/crypto/boringssl.rs, quiche/src/crypto/mod.rs, quiche/src/lib.rs
Follow-up to b17904e522777746b2a6b12667d85283e1df368c.
Currently the dummy seal operation done to prime the AEAD context is done in `Seal::from_secret()`, but really it needs to be done as part of `PacketKey::from_secret()` to make sure every code path is covered, including the key update one which doesn't call `Seal::from_secret()`.
It's not entirely clear why, but the problem (i.e. seal operation fail when trying to encrypt a packet) seems to only appear after several packets have already been encrypted with the new key, which is why this wasn't caught by the existing key update test.
To cover that, the test is expanded by making the server send additional packets which from local testing seems to trigger the issue.
=> crypto/boringssl: do dummy seal on key update too

Dockerfile, quiche/src/crypto/boringssl.rs, quiche/src/crypto/mod.rs, quiche/src/crypto/openssl_quictls.rs
`AES_ecb_encrypt()` will always write 16 bytes (an AES block length), but the new header protection code was passing in only 5 bytes... fun ensued.
This also refactors the header protection methods somewhat to not hard-code the mask length all over the place.
Closes #1924.
=> crypto/boringssl: don't overwrite mask

apps/src/bin/quiche-server.rs, apps/src/client.rs
This can be useful to debug address rebinding problems.
=> apps: log both source and destination addresses

h3i/src/client/connection_summary.rs, h3i/src/frame.rs
The ConnectionSummary can be serialized to help other tooling consume
the output of h3i. Previously we didn't support the seralization of
DATA frame payloads. Furthermore, we were a bit inconsistent with how
we serialize frames with binary payloads.
This change adds support for logging DATA frame payloads and ensures
that all frames consistently have a `_len` field to indicate the true
length of the frame. Documentation has been added with a pointer to
the hexstring qlog definition that we use here.
Closes #1917
=> h3i: Improve ConnectionSummary stream_map serialization

apps/run_endpoint.sh
Currently the max active CIDs limit controls both the number of active CIDs as well as the number of active paths, so while during rebinding tests the CIDs don't change, we are still prevented from creating new paths because of the limit, causing the interop rebinding tests to fail.
=> qns: increase active CIDs limit for interop

Dockerfile
- Resolve the `WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match`.
Build Logs:
```plaintext
#1 WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 1)
#1 WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 17)
#1 WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 35)
```
=> Fix the build warning

qlog/src/events/quic.rs
Which either (IMO) have a natural default, or that only consist of `Option`s.
This makes initialization of these types less verbose for the user.
=> chore: Derive `default` for a bunch of types

h3i/src/client/mod.rs, h3i/src/lib.rs, h3i/src/recordreplay/qlog.rs, qlog/src/events/h3.rs, qlog/src/events/security.rs, qlog/src/lib.rs, qlog/src/streamer.rs, quiche/src/h3/mod.rs, quiche/src/lib.rs, quiche/src/recovery/mod.rs
In followup to https://github.com/cloudflare/quiche/pull/1931, we can cut down on boilerplate internally
=> chore: use qlog PacketSent default inside quiche

.github/workflows/stable.yml, Cargo.toml, h3i/Cargo.toml, tokio-quiche/Cargo.toml, tokio-quiche/src/http3/driver/datagram.rs, tokio-quiche/src/http3/driver/mod.rs, tokio-quiche/src/lib.rs, tokio-quiche/src/quic/router/mod.rs, tokio-quiche/tests/fixtures/h3i_fixtures.rs
Newer quiche had a breaking API change compared to the gcongestion branch that needs to be handled explicitly. gcongestion also can't use the workspace octets dependency.
h3i is updated to use the workspace quiche dependency as well.
=> tokio-quiche: use workspace quiche, octets and h3i dependencies

h3i/Cargo.toml, h3i/src/actions/h3.rs, h3i/src/client/sync_client.rs
This bumps serde_with and url to match the versions specified in the workspace.
It also appears that the `serde_with` dependency was entirely unnecessary, as the `serde_as` use in the code never actually worked properly and it triggers a warning with newer versions (https://github.com/jonasbb/serde_with/pull/502) so I just removed it.
---
This depends on https://github.com/cloudflare/quiche/pull/1941.
=> h3i: more workspace dependencies

tokio-quiche/Cargo.toml
This is required to publish to crates.io.
=> tokio-quiche: add `license` field to metadata

h3i/Cargo.toml, h3i/src/actions/h3.rs, h3i/src/recordreplay/qlog.rs
Currently the Duration type is serialized as a struct. This changes it to a simple number of milliseconds.
=> h3i: encode WaitType(Duration) as number

h3i/src/frame_parser.rs
This PR replaces the manual session setup in `h3i/src/frame_parser.rs` with `Session::new()`, as #1805 has been merged for a while.
=> refactor(h3i): replace manual config with `Session::new()`

tokio-quiche/Cargo.toml, tokio-quiche/src/quic/addr_validation_token.rs, tokio-quiche/src/quic/connection/id.rs, tokio-quiche/src/quic/connection/mod.rs, tokio-quiche/tests/integration_tests/timeouts.rs
The same functionality is already provided by the `boring` crate anyway, which also happens to be FIPS validated (if built appropriately), so not much point in having additional dependencies.
=> tokio-quiche: replace ring/rand with boring

tokio-quiche/src/http3/driver/mod.rs, tokio-quiche/src/http3/driver/streams.rs, tokio-quiche/tests/integration_tests/headers.rs, tokio-quiche/tests/integration_tests/mod.rs
Since quiche will reject multiple calls to `send_response*()` on the same stream, we need to call `send_additional_headers()` after the initial headers are sent.
=> tokio-quiche: add support for sending additional headers

Dockerfile, README.md, h3i/Cargo.toml, quiche/Cargo.toml
The Docker builds are failing due to litemap and zerofrom crates
requiring rust 1.81.
=> Bump rust version in Dockerfile

quiche/src/lib.rs
We've been always producing a value of either `None` or
`Some(_algo name_)`, which is unexpected. This commit
ensures the field is only generated if the input Option
is some.
=> lib: fix qlog parameters_set tls_cipher field

quiche/src/crypto/mod.rs, quiche/src/lib.rs, quiche/src/packet.rs
This is yet more fallout from b17904e5 (also see 7d686e1). This time the missing dummy seal is for clients, after the initial epoch is reset (e.g. due to retry or version negotiation), which also causes the initial key material to be dervied again.
When that happens, and if the client's PTO fires (e.g. because the server is slow to respond) that will trigger the client to create a new Initial packet that will fail to seal because the initial seal context expects a packet number of 0, while the actual packet number is greater than that as it's a retransmission.
This only happens when the client's initial PTO fires because otherwise it would just send a Handshake packet instead, without using the initial key material.
=> crypto/boringssl: perform dummy seal when client resets keys too

tokio-quiche/Cargo.toml, tokio-quiche/README.md, tokio-quiche/src/lib.rs, tokio-quiche/src/settings/config.rs
Whether to capture keylogs (i.e., secrets) should only be decided by the final binary that incorporates tokio-quiche somewhere in its dependency graph. Using a feature allows any dependency to enable keylog capturing, whereas a cfg flag must be explicitly set in RUSTFLAGS or similar.
I've opted to keep the feature flag around for now. We can remove it on the next major bump. This makes the migration a bit easier.
=> Switch from feature to cfg flag for tokio-quiche's capture_keylogs

qlog/src/events/mod.rs
=> fix: Derive an additional `default`

quiche/src/tls/mod.rs
The function was always logging a 1024 byte long buffer padded with nullbytes. This doesn't look intentional, and may cause trouble for some logger implementations that don't expect nulls in &str.
See also: rust-mobile/android_logger-rs#90
=> tls: don't log nullbytes from log_ssl_error

tokio-quiche/src/metrics/labels.rs, tokio-quiche/src/quic/router/mod.rs
I checked the last 7 days of these logs. While there are a few ten thousand of them, they were all instances of
`quiche::Error::InvalidPacket`. Those are not unexpected errors, so I added an entry for them to QuicInvalidInitialPacketError.
No other unexpected errors were observed at all in the last 7 days. I feel confident to remove the trial logging and pass those errors up to users of tokio-quiche now.
=> tokio-quiche: Clean up packet router logging TODO

tokio-quiche/src/http3/driver/hooks.rs, tokio-quiche/src/quic/router/connector.rs, tokio-quiche/src/quic/router/mod.rs
Our CI jobs run lints on rustdoc. Warnings and errors get inserted inline
into unrelated PRs, which is annoying.
This change fixes doc warnings as best I could figure out. Run locally
using:
```
cargo doc --document-private-items
```
=> tokio-quiche: fix private documentation

quiche/src/lib.rs, quiche/src/path.rs, quiche/src/recovery/mod.rs, quiche/src/tls/mod.rs
It can be useful to tweak a specific connection's configuration based on information like SNI. However this is only available after the client's ClientHello is fully processed, which is not entirely apparent from an application PoV (e.g. ClientHello can be split across multiple Initial packets).
BoringSSL provides a number of callbacks called during the TLS handshake and sometimes even before any packet has been sent (e.g. `select_cert_cb`) which is useful to tweak congestion control settings or transport parameters,  that provide the required information, but the underlying quiche connection is not exposed to application code from inside these callbacks currently.
This change adds a mechanism to allow applications to change specific connection settings from inside these BoringSSL …
=> add mechanism to change connection settings from BoringSSL handshake callbacks

quiche/src/lib.rs, quiche/src/recovery/congestion/recovery.rs, quiche/src/recovery/mod.rs
Changes in preparation for gcongestion integration.  Functional no-op since new methods are not used yet.
=> [gcongestion] Add get_next_release_time and on_app_limited methods to RecoveryOps

quiche/Cargo.toml, quiche/src/lib.rs, quiche/src/recovery/congestion/mod.rs, quiche/src/recovery/congestion/recovery.rs, quiche/src/recovery/gcongestion/bbr/bandwidth_sampler.rs, quiche/src/recovery/gcongestion/mod.rs, quiche/src/recovery/gcongestion/recovery.rs, quiche/src/recovery/mod.rs, tokio-quiche/Cargo.toml, tokio-quiche/src/quic/io/worker.rs
This PR hooks the implementation in the gcongestion subdirectory into the Recovery object defined in the `quiche/src/recovery/mod.rs`
Also, update `tokio-quiche/src/quic/io/worker.rs` to use get_next_release_time when using the gcongestion BBRv2 implementation even in cases where the "gcongestion" feature is disabled.
=> [gcongestion] Add bbr2_congestion algorithm which uses the gcongestion BBRv2 implementation.

quiche/src/lib.rs, quiche/src/recovery/gcongestion/bbr2.rs, quiche/src/recovery/gcongestion/recovery.rs, quiche/src/recovery/mod.rs, quiche/src/recovery/rtt.rs
After this change most of the functionality from quiche-mallard should be available from mainline quiche.  The exception being the "zero-copy" feature.
=> [gcongestion] Apply fixes to gcongestion implementation from the cloudflare/quiche-mallard repo.

Cargo.toml, h3i/Cargo.toml, qlog/Cargo.toml
Previously `qlog` `<= v0.15.0` dependet on `serde_with` without `default-features`. It would only enable `serde_with`'s `macro` feature. See `crates.io` link below, hovering over the `serde_with` `1 EXTRA FEATURE` field.
https://crates.io/crates/qlog/0.15.0/dependencies
https://github.com/cloudflare/quiche/pull/1938 introduced the `serde_with` workspace dependency. Note that this workspace dependency does not disable `serde_with` `default-features`.
https://github.com/cloudflare/quiche/pull/1953 updated `qlog` to use the `serde_with` workspace import, instead of the previous crate specific import in `qlog/Cargo.toml`. Effectively, this enabled `serde_with` `default-features` for `qlog`. See `crates.io` link below, this time for `qlog` `v0.15.1`: …
=> chore(Cargo.toml): disable serde_with default-features

quiche/src/lib.rs, tokio-quiche/src/settings/config.rs, tokio-quiche/src/settings/quic.rs
Needed for async h3i to use the same arguments as sync h3i. 
The docs change is something I noticed while investigating `verify_peer`.
=> tokio-quiche: expose additional Quiche settings in QuicSettings

Cargo.toml, quiche/Cargo.toml, quiche/src/recovery/gcongestion/bbr/bandwidth_sampler.rs
bandwidth_sampler_tests::app_limited required some adjustments when overestimate_avoidance == true, further investigation is needed.
=> [gcongestion] parametrize bandwidth_sampler tests by overestimate_avoidance

quiche/src/recovery/congestion/bbr/mod.rs, quiche/src/recovery/congestion/bbr/per_ack.rs
For example, due to pacing offload some packets might be buffered in the fq qdisc queue and not yet sent on the network.
This is more or less meant to be equivalent to Linux' `bbr_packets_in_net_at_edt()` function.
---
This is an alternative to https://github.com/cloudflare/quiche/pull/1636 and instead of walking the list of sent packets which is quite expensive, we just sort of estimate the amount of bytes by looking at BW and pacing rate.
=> bbr: account for bytes buffered at lower layers

tokio-quiche/src/http3/driver/mod.rs
Change the return value of h3::Connection::send_body() to return Ok(0) if a zero-length body *without* FIN is sent (from Err(Done)).
Two reasons why:
* It eliminiates a possible infinte loop in tokio-quiche. If TQ gets a Err(Done) it will retry the send, which will never succeed. But if it gets an Ok(n) TQ will move on if `n == body.len()`.
* It brings the behavior in line with what send_stream() does, which also returns Ok(0) if a zero-length write w/o fin is attempted.
=> tokio-quiche: Handle zero-length HTTP bodies without FIN

octets/Cargo.toml, octets/src/lib.rs
The `put_u` and `peek_u` macros in `octets` contains unsafe blocks. This commit adds a safety check to make sure the length we are being passed is within the proper bounds. Without this check it's possible to access invalid memory.
Note that the macro is not exported and all current uses of it are safe. So this commits just prevents future issues.
=> Add bounds check in un-safe code in octets macros

quiche/src/recovery/gcongestion/bbr2.rs, quiche/src/recovery/gcongestion/bbr2/drain.rs, quiche/src/recovery/gcongestion/bbr2/mode.rs, quiche/src/recovery/gcongestion/bbr2/network_model.rs, quiche/src/recovery/gcongestion/bbr2/probe_bw.rs, quiche/src/recovery/gcongestion/bbr2/probe_rtt.rs, quiche/src/recovery/gcongestion/bbr2/startup.rs
Stop accessing global params struct from the gcongestion implementation so we can override these params per connection
=> refactor: pass bbr2 parameters to components

quiche/src/lib.rs, quiche/src/recovery/gcongestion/bbr2.rs, quiche/src/recovery/gcongestion/mod.rs, quiche/src/recovery/gcongestion/recovery.rs, quiche/src/recovery/mod.rs
This PR expose methods for providing custom BBR2 params and changing algorithm behavior. I have marked these APIs as internal since they are for experimental purposes only.
[refactor: pass bbr settings to components](https://github.com/cloudflare/quiche/pull/2023) is a refactor change. With this change we end up passing the Bbr Settings object rather than referencing the const value, which makes it easier to reasoning about overrides.
=> [gcongestion] allow customizing BBR2 params

h3i/examples/content_length_mismatch.rs, h3i/src/actions/h3.rs, h3i/src/lib.rs, h3i/src/prompts/h3/headers.rs, h3i/src/prompts/h3/mod.rs, h3i/src/recordreplay/qlog.rs, quiche/src/h3/qpack/encoder.rs, quiche/src/h3/qpack/mod.rs
This PR adds support for literal headers, such as header names with upper-case letters, to h3i.
It does not affect the existing functions, instead introducing a new one (`send_headers_frame_literal`) that can be used when testing specifically for these invalid headers.
I made sure that the internal quiche functions and constants that needed to be exposed to h3i are hidden behind the `internal` feature.
=> Add support for literal headers for h3i

tokio-quiche/src/settings/config.rs, tokio-quiche/src/settings/quic.rs, tokio-quiche/tests/fixtures/mod.rs, tokio-quiche/tests/integration_tests/connection_close.rs, tokio-quiche/tests/integration_tests/mod.rs, tokio-quiche/tests/integration_tests/timeouts.rs
I opted to not change to a builder pattern for API consistency's sake. If we include one on `QuicSettings`, we should also include one on `Http3Settings`, which would significantly increase the scope of this PR.
If we really want to do that, I'm fine doing it as a separate commit/follow-up
=> tokio-quiche: expose quiche settings

quiche/Cargo.toml, quiche/src/recovery/mod.rs
This makes quiche a drop in replacement for quiche-mallard
=> [gcongestion] Use gcongestion BBRv2 when BBRv2 is requested if gcongestion feature is enabled

tokio-quiche/Cargo.toml, tokio-quiche/README.md, tokio-quiche/src/http3/driver/mod.rs, tokio-quiche/src/lib.rs
Quiche has all the required functionality, so mallard can switch over to mainline quiche.
=> Drop dependency on quiche-mallard

tokio-quiche/src/settings/config.rs
This can interfere with other APIs called on the BoringSSL context directly.
=> tokio-quiche: don't call Config::verify_peer() unless necessary

quiche/src/lib.rs
In cases the RTT is very low, the old logic prevents use of TxTime to schedule send for packets on low RTT connections, which results in instability due to wakeup timing granularity.  epoll_wait accepts a timeout in milliseconds.
=> Allow queueing at least 1 millisecond worth of packets in advance.

Cargo.toml, quiche/Cargo.toml
Changes:
a8d5999645787db722d903bbedbac4587fc74be1 Allow queueing at least 1 millisecond worth of packets in advance.
49f2f5288778c5593eeb209d44310757537cebcd remove unnecessary &mut
=> quiche: release 0.24.2

quiche/src/lib.rs, quiche/src/recovery/congestion/recovery.rs, quiche/src/recovery/gcongestion/recovery.rs, quiche/src/recovery/mod.rs
As a pre-requisite, add Instant::now as an argument to get_packet_send_time so it can be driven by the test.
=> Parameterize recovery module tests so they run against all congestion control algorithms.

.github/workflows/nightly.yml, .github/workflows/semgrep.yml, .github/workflows/stable.yml
Mostly so security scanner stops complaining...
=> ci: limit CI jobs to read-only contents

quiche/src/lib.rs, quiche/src/tls/mod.rs
Currently we buffer outgoing data up to `min(cwnd, flow_control)`, but this can be lead to starving a connection while waiting for additional data from the application.
This change adds a configuration option to change the send capacity "factor", that is multiplied to the existing send capacity calculation (so e.g. instead of `min(cwnd, flow_control)` once could change that to `2 * min(cwnd, flow_control)`).
Making this configurable rather than a fixed value lets application experiment with different values depending on their needs.
=> introduce tx_cap factor

quiche/src/lib.rs, quiche/src/packet.rs, quiche/src/tls/mod.rs
Currently we track sensitive crypto context along with general packet related context which makes it difficult to track its usage. This PR separates crypto context into its own structure, which should make it easier to reason about how the crypto context is initialized, accessed and freed.
=> Separate crypto ctx from pkt number space

quiche/src/h3/mod.rs, tokio-quiche/src/http3/driver/mod.rs, tokio-quiche/tests/fixtures/mod.rs, tokio-quiche/tests/integration_tests/headers.rs
Currently tokio-quiche always sets the same default ptiority for all h3 responses. This change adds support for applications to specify an optional priority on a response-by-response basis instead, while still keeping the current default priority for backwards compatibility.
This is done by adding a new `Option<Priority>` field to `OutboundFrame::Headers()`. Applications that don't want to provide any priority can simply set this to `None`, in which case the existing default priority logic applies.
In order to allow setting priorities for additional headers as well, a new method `send_additional_headers_with_priority()` is also added. This is required because the `Priority` fields are private, which means it would not be possible to call the lower level `stream_priority()` method with …
=> tokio-quiche: add support for setting per-response h3 priorities

Cargo.toml, tokio-quiche/Cargo.toml, tokio-quiche/src/settings/config.rs
BoringSSL does this internally when we ask it to load a PEM file, but for RPK we call `fs::read` ourselves. The error message is not very helpful in those cases, as we simply bubble up an io::Error without any context.
`anyhow` is already an implicit dependency via foundations, so I figured using it was fine.
=> tokio-quiche: Add input path to file errors

quiche/src/lib.rs, quiche/src/path.rs, quiche/src/recovery/bandwidth.rs, quiche/src/recovery/congestion/bbr/mod.rs, quiche/src/recovery/congestion/bbr/per_ack.rs, quiche/src/recovery/congestion/bbr2/mod.rs, quiche/src/recovery/congestion/bbr2/per_ack.rs, quiche/src/recovery/congestion/bbr2/per_loss.rs, quiche/src/recovery/congestion/delivery_rate.rs, quiche/src/recovery/congestion/mod.rs, quiche/src/recovery/congestion/recovery.rs, quiche/src/recovery/gcongestion/bbr/bandwidth_sampler.rs, quiche/src/recovery/gcongestion/bbr2.rs, quiche/src/recovery/gcongestion/bbr2/network_model.rs, quiche/src/recovery/gcongestion/mod.rs, quiche/src/recovery/gcongestion/pacer.rs, quiche/src/recovery/gcongestion/recovery.rs, quiche/src/recovery/mod.rs
This PR updates the gcongestion's delivery_rate so the units match the congestion implementation.
**Reasoning**
`recovery.delivery_rate()` is only [used](https://github.com/cloudflare/quiche/commit/e7dba7c39109e6e5d71f0d91418af2905188e9f1) for PathStats and qlog. Therefore as noted on [PathStats](https://github.com/cloudflare/quiche/blob/master/quiche/src/path.rs#L910), the units should be bytes/s
=> Update delivery_rate units for gcongestion

Dockerfile, README.md, h3i/Cargo.toml, quiche/Cargo.toml, quiche/src/lib.rs
Fixes some CI failure where packages fail to build due to 1.81 being outdated
Successful build output:
```
❯ docker build --tag 'quiche' .
[+] Building 127.8s (24/24) FINISHED                                  docker:desktop-linux
=> [internal] load build definition from Dockerfile                                  0.0s
=> => transferring dockerfile: 1.43kB                                                0.0s
=> [internal] load metadata for docker.io/martenseemann/quic-network-simulator-endp  0.1s
=> [internal] load metadata for docker.io/library/rust:1.82                         55.1s
=> [internal] load .dockerignore                                                     0.0s
=> => transferring context: 2B                                                       0.0s
=> [build  1/14] FROM …
```
=> docker: update Rust version to 1.82

quiche/src/recovery/congestion/delivery_rate.rs, quiche/src/recovery/congestion/recovery.rs, quiche/src/recovery/gcongestion/recovery.rs
With this PR, congestion delivery_rate matches the Linux implementation.
Q: How does TCP calculate delivery rate?
A: The TCP delivery rate consider if the connection is app limited.
- If NOT app_limited, record the latest value.
- If app_limited, record the max value `max(previous_rate, new_app_limited_rate)`.
This [blog](https://blog.mygraphql.com/en/notes/low-tec/network/tcp-inspect/) + this [linux commit](https://github.com/torvalds/linux/commit/eb8329e0a04db0061f714f033b4454326ba147f4) provides the answer:
> tcpi_delivery_rate: The most recent goodput, as measured by
tcp_rate_gen(). If the socket is limited by the sending
application (e.g., no data to send), it reports the highest
measurement instead of the most recent. The unit is bytes per
second (like other rate fields in …
=> Consider app_limited when generating new delivery_rate values

tokio-quiche/src/lib.rs, tokio-quiche/src/quic/io/gso.rs, tokio-quiche/src/quic/io/worker.rs, tokio-quiche/src/quic/router/acceptor.rs, tokio-quiche/src/socket/capabilities.rs, tokio-quiche/src/socket/connected.rs, tokio-quiche/src/socket/listener.rs
Current logic avoids setting the UDP_SEGMENT cmsg on sendmsg() calls when sending a single packet over the wire. However, there are niche cases where it's desirable to update the segment size after a socket has been created. If the updated segment size is greater than what the socket was initialized with, and we omit the UDP_SEGMENT cmsg, then the kernel will fall back to the segment size that is configured on the socket and erroneously truncate the packet on the way out.
We now set the UDP_SEGMENT cmsg on each packet no matter what.
To help avoid this footgun, we now initialize GSO on the socket with the maximum possible segment size.
=> tokio-quiche: always set UDP_SEGMENT cmsg when calling sendmsg()

datagram-socket/src/socket_stats.rs, quiche/src/lib.rs, quiche/src/path.rs, quiche/src/recovery/congestion/recovery.rs, quiche/src/recovery/gcongestion/bbr2.rs, quiche/src/recovery/gcongestion/bbr2/drain.rs, quiche/src/recovery/gcongestion/bbr2/mode.rs, quiche/src/recovery/gcongestion/bbr2/probe_bw.rs, quiche/src/recovery/gcongestion/bbr2/probe_rtt.rs, quiche/src/recovery/gcongestion/bbr2/startup.rs, quiche/src/recovery/gcongestion/mod.rs, quiche/src/recovery/gcongestion/pacer.rs, quiche/src/recovery/gcongestion/recovery.rs, quiche/src/recovery/mod.rs, tokio-quiche/src/quic/connection/mod.rs
This PR emits stats from when a CCA exits the startup phase. Its currently only implemented for gcongestion (BBR).
**How to review**
Its probably best to review this code one commit at a time. The second commit modified the `startup.rs` and the most important piece. The other two commits are essentially the glue.
**Callouts**
This replaces https://github.com/cloudflare/quiche/pull/2057 and https://github.com/cloudflare/quiche/pull/2061. Those were trying to refactor the code, which has a lot of side effects and were introducing bugs in the process. This PR avoids refactoring the code to avoid that pitfall.
=> Emit statistics from when a CCA exits Startup

datagram-socket/src/socket_stats.rs, tokio-quiche/src/quic/io/worker.rs
Currently these values are only exposed as metrics, but it can be useful to collect them on a per-connection basis (rather than aggreagte metrics), so expose them via audit log stats.
Regarding max loss percentage, the underlying value is `f32` but it's converted to integer (`u8`) to allow using atomic operations like for the rest of the `QuicAuditStats` fields.
=> tokio-quiche: expose max bandwidth and max loss percentage as stats

quiche/src/recovery/gcongestion/bbr2.rs, quiche/src/recovery/gcongestion/bbr2/network_model.rs, quiche/src/recovery/gcongestion/mod.rs
Currently rounds without growth that are app limited are counted towards the threshold for number of rounds without growth.
=> gcongestion: don't consider app limited rounds for bw growth

quiche/src/lib.rs, quiche/src/stream/mod.rs, quiche/src/tls/mod.rs
This adds support for changing some transport parameters during the QUIC hanshake from inside BoringSSL callbacks (e.g. `select_cert_cb`). Currently only `max_idle_timeout` and `initial_max_streams_bidi` are supported, but more can be added later if needed.
Each parameter is configured with its own method rather than having a single method taking a new `TransportParameters` value to allow applications to overwrite specific parameters rather than having to provide an entire new set of parameters.
In the future we might consider adding a new `TransportParameters`-like type with optional fields, but that didn't seem necessary here as we are only interested in a few TPs at this point.
Because the server's TPs are sent in the first flight inside TLS messages generated by BoringSSL itself, they …
=> support changing transport params from BoringSSL handshake callbacks

tokio-quiche/Cargo.toml, tokio-quiche/src/quic/router/mod.rs
On macOS with a quiche client in low MTU situations the incoming packet router should be able to gracefully handle packets marked with fragmentation needed
=> Handle low PMTU on macOS

datagram-socket/src/socket_stats.rs, octets/src/lib.rs, quiche/src/cid.rs, quiche/src/ffi.rs, quiche/src/lib.rs, quiche/src/path.rs, quiche/src/stream/mod.rs, tokio-quiche/src/quic/connection/mod.rs, tokio-quiche/src/quic/io/gso.rs, tokio-quiche/src/socket/listener.rs
Loss usually happens in burst so the number of packets lost will depend on the volume of inflight packets at the time of loss (which can be arbitrary). RTO count measures the number of loss events and provide a normalized loss metric.
=> Emit RTO count statistics to estimate loss events

quiche/src/recovery/gcongestion/bbr/bandwidth_sampler.rs, quiche/src/recovery/gcongestion/bbr2.rs, quiche/src/recovery/gcongestion/bbr2/network_model.rs, quiche/src/recovery/gcongestion/mod.rs
This code doesn't seem to be working well, and we would like to compare results with and without the fix.  It seems that overestimation avoidance is a work in progress and we should recommend disabling the code for now.
Original change: https://github.com/cloudflare/quiche/pull/2073
=> Config protect fixes to a0 choice used in BW overestimation avoidance code

quiche/src/crypto/mod.rs
A timeout with a [quinn](https://github.com/quinn-rs/quinn) client was reported in:
https://github.com/seanmonstar/reqwest/issues/2610 and also #2025 
While debugging i noticed, that after a attempted key update from quinn incoming packets could not be decrypted. Also the new secret was shorter than the old one.
Quinn performs the early key update by design https://github.com/quinn-rs/quinn/blob/64139181e0fcdf337737d32dac077e96391d9d52/quinn-proto/src/connection/mod.rs#L299-L305
This PR ensures, that the buffer is large enough to support the current key size.
=> Key update with TLS_AES_256_GCM_SHA384 trunkates bytes from the next secret. Incoming packets get discarded. 

apps/src/args.rs, apps/src/bin/quiche-server.rs, apps/src/client.rs, quiche/src/lib.rs, quiche/src/recovery/congestion/bbr/init.rs, quiche/src/recovery/congestion/bbr2/init.rs, quiche/src/recovery/congestion/bbr2/pacing.rs, quiche/src/recovery/congestion/bbr2/per_ack.rs, quiche/src/recovery/congestion/mod.rs, quiche/src/recovery/congestion/recovery.rs, quiche/src/recovery/congestion/test_sender.rs, quiche/src/recovery/gcongestion/bbr2.rs, quiche/src/recovery/gcongestion/bbr2/network_model.rs, quiche/src/recovery/gcongestion/mod.rs, quiche/src/recovery/gcongestion/recovery.rs, quiche/src/recovery/mod.rs, quiche/src/recovery/rtt.rs
Before this change, the initial RTT was hardcoded to `333`. With this change, it's now possible for the user to configure that value through `Config::set_initial_rtt`. This is important for high-latency networks.
Context: I'm collaborating with the [tiptop IETF working group](https://datatracker.ietf.org/doc/charter-ietf-tiptop/) to test QUIC in a deep-space setting.
cc @marcblanchet
=> Make initial RTT configurable

tokio-quiche/src/http3/driver/mod.rs
Applications built on top of H3Driver process events by spinning on the `UnboundedReceiver` corresponding to H3Driver's `h3_event_sender`. When they no longer need to listen for these events, they typically terminate their event loop and clean up their state.
The problem is that tokio-quiche doesn't always know about that. We currently kill the connection in a few places by propagating `H3ConnectionError::ControllerWentAway` up to the event loop. This doesn't happen deterministically at the moment. Specifically, if the client doesn't send any data, the RunningApplication IOW can spin until idle timeout in certain cases.
Instead, tokio-quiche should know when the application can no longer process `H3Event`s and immediately tear down its own state when the `H3Event` receiver closes.
=> tokio-quiche: close connection when H3Event receiver closes

quiche/src/recovery/gcongestion/mod.rs, quiche/src/recovery/gcongestion/pacer.rs, quiche/src/recovery/gcongestion/recovery.rs
The original impl had a bunch of abstraction to support bbr1/bbr2/bbr3. Making pacer implement CongestionControl, using enum_dispatch, etc were some of the abstractions. We are only using bbr3 so we need to get rid of the weird stuff like pacer implementing CongestionControl trait (which makes no sense).
=> refactor: remove impl CongestionControl for Pacer

quiche/src/recovery/gcongestion/bbr2.rs, quiche/src/recovery/gcongestion/mod.rs, quiche/src/recovery/mod.rs, quiche/src/test_utils.rs
Extracted from https://github.com/cloudflare/quiche/pull/2113, while not addressing the more controversial fixes to reduce the delta between the implementation and the BBR draft RFC.
=> Add option to override initial pacing rate

.github/workflows/stable.yml, quiche/src/recovery/gcongestion/bbr2.rs, quiche/src/recovery/gcongestion/bbr2/mode.rs, quiche/src/recovery/gcongestion/bbr2/startup.rs
Deref makes it difficult to tell what component is being modified/accessed. Deref-ing to network is also surprising, makes the code harder to read and could potentially introduce mistakes.
=> refactor: Remove deref to network_model for mode.

quiche/src/recovery/gcongestion/mod.rs, quiche/src/recovery/gcongestion/pacer.rs, quiche/src/recovery/gcongestion/recovery.rs
Now that pacer no longer implements the CongestionControl trait, the enum_dispatch abstraction serves no purpose.
=> refactor: remove enum_dispatch indirection from CongestionControl trait now that it is not needed

quiche/src/recovery/mod.rs
`set_custom_bbr_params` is gated on `internal`, so the test that uses it should be as well.
=> ci: properly gate internal feature

quiche/src/cid.rs, quiche/src/lib.rs, quiche/src/tests.rs
This change improves sender side handling of RETIRE_CONNECTION_ID frames, especially when there may be multiple paths available to use.
=> lib: improve connection ID retirement

quiche/src/recovery/gcongestion/bbr2.rs, quiche/src/recovery/gcongestion/bbr2/mode.rs, quiche/src/recovery/gcongestion/bbr2/probe_bw.rs, quiche/src/recovery/gcongestion/bbr2/probe_rtt.rs, quiche/src/recovery/gcongestion/mod.rs
* Split ProbeBW cwnd_gain parameter for ProbeBW_UP phase from param used for other ProbeBW phases.
* Add parameters for ProbeRTT pacing gain and cwnd gain.
Some of these params are inconsistent with the BBR RFC draft.  Having them as config is the first step towards getting the inconsistency fixed.
=> BbrParams for BBR ProbeBw and ProbeRtt stages

tokio-quiche/src/quic/io/worker.rs, tokio-quiche/src/quic/raw.rs, tokio-quiche/src/quic/router/mod.rs, tokio-quiche/tests/integration_tests/migration.rs, tokio-quiche/tests/integration_tests/mod.rs
Currently tokio-quiche depends on the `send()` method to pick the network path to send packets on. This can mean that only packets for a single path end being flushed to the network.
In addition to that, the destination address for `sendmsg()` calls is fixed to the peer's initial address, initialized when a connection is established.
These issues end up preventing connections from migrating correctly when the peer's address changes (e.g. due to NAT rebinding) because packets for any new path would have to be flushed too, and in any case the original peer address would be used to send packets to anyway, rather than the new address the peer migrated to.
This change fixes both of those issues, but note that while this allows "passive" migration of peers, it does not allow "active" migration, …
=> tokio-quiche: round-robin send over all network paths

quiche/src/recovery/congestion/recovery.rs, quiche/src/recovery/gcongestion/recovery.rs, quiche/src/recovery/mod.rs
Dynamic time threshold logic from
https://github.com/cloudflare/quiche/pull/470 was accidentally removed.
The goal is to make time-based detection less sensitive when a spurious loss is detected.
It would be best to review this change as separate commits:
- 1st commit adds the time_thresh change
- 2nd commit refactors an existing reordering tests to make it easier to read
- 3rd commit adds the new test to test the time_thresh change
I also added the same test to the [previous version (0.21.0)](https://github.com/cloudflare/quiche/compare/akothari/test_time_thresh_0.21.0?expand=1) of code to confirm the behavior.
I did some simulation testing to measure the effectiveness of this fix for BBRv3 in the gconsgestion branch. Because reordering is hard to control for there is a lot of …
=> fix: dynamically adjust time threshold on packet reordering

quiche/src/lib.rs, quiche/src/recovery/congestion/recovery.rs, quiche/src/recovery/gcongestion/recovery.rs, quiche/src/recovery/mod.rs
Packet re-ordering (spurious loss) is common to certain networks and can
cause severe degradation to a connection.  When enabled, the relaxed
mode will disable pkt_thresh loss detection on the first spurious loss
and then double time_thresh on subsequent spurious losses.
Review commit by commit.
- The first commit is a refactor which abstracts out the loss threshold logic.
- The second introduces the new relaxed logic.
=> feat: expose configuration to enable relaxed loss threshold detection on spurious loss

h3i/src/client/async_client.rs
This prevents panics in cases where work_loop has to continue to iterate even after seeing all CloseTriggerFrames.
=> h3i: Add else branch to wait_for_data in async client

tokio-quiche/src/http3/driver/mod.rs
This reverts commit bc31516462ec73035bab26641f3205dfad36ff1c.
It looks like this commit can cause issues with connections that use tunneling to communicate directly with the IOW, out-of-band with the Server. Since we need to unblock some feature work, let's just revert for now.
=> Revert "tokio-quiche: close connection when H3Event receiver closes"

quiche/src/lib.rs, quiche/src/path.rs
Two small fixes
1. No longer update max datagram size from PMTUD on every sent packet. This was unnecessary to begin with but not harmful in most cases, however, in some cases this sets the max datagram size to 1200 if there wasn't a successful probe which can interfere with the PMTUD process.
2. Remove a condition on when PMTUD probing should happen as pmtud.should_probe() handles this and the current condition blocks revalidation of PMTUD from occurring.
=> PMTUD Fixes

quiche/src/recovery/gcongestion/bbr2.rs, quiche/src/recovery/gcongestion/bbr2/probe_bw.rs, quiche/src/recovery/gcongestion/mod.rs
BBRv3 probeDown currently exits based on time duration. This is Google experimental code which is not mentioned in the BBR RFC. This PR introduces an option to disable the experimental behavior.
=> feat: expose option to disable probeDown early-exit behavior

tokio-quiche/src/http3/driver/mod.rs, tokio-quiche/src/http3/driver/streams.rs, tokio-quiche/src/http3/stats.rs
Sending headers in quiche means buffering from the application
layer into quiche. It is not always possible to do this due to
capacity at any moment in time.
Tokio-quiche currently sends response headers by processing the
writable frame queue (process_write_frame()) and acting on an
OutboundFrame::Headers. This supports informational headers,
final headers, and trailing headers. Each type might fail,
which results in leaving the OutboundFrame on the queue to be
retried later.
This change adds some time tracking to each stream. If the first
attempt to send headers fails, the time is marked. On completion,
a duration is calculated and the stream's aggregate flushing
time is incremented. This ensures retrying of any/all response
messages is accounted for.
=> tq: add monitoring of time taken to flush response headers

Cargo.toml, tokio-quiche/Cargo.toml
0.8.0 grabbed `datagram-socket 0.4.0`, since `0.5.0` wasn't published at the time that 0.8.0 was (even though `datagram-socket` is a workspace dependency)
=> tokio-quiche: release 0.9.0

tokio-quiche/src/quic/router/mod.rs
slog doesn't guard log statements by log-level. Instead it relies on arguments to its logging macros to defer work until needed.
=> Defer log formatting until it's actually used
